// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_contacts.sql

package personal_contact_store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptContactRequest = `-- name: AcceptContactRequest :one
WITH updated AS (
    UPDATE contact_requests AS cr
    SET status = 'accepted'
    WHERE cr.requester_user_id = $1
      AND cr.receiver_user_id = $2
      AND cr.status = 'pending'
    RETURNING cr.id
), existing AS (
    SELECT cr.status
    FROM contact_requests AS cr
    WHERE cr.requester_user_id = $1
      AND cr.receiver_user_id = $2
    LIMIT 1
)
SELECT
    (CASE
        WHEN EXISTS (SELECT 1 FROM updated) THEN 'accepted'
        WHEN (SELECT status FROM existing) IS NULL THEN 'not_found'
        ELSE 'processed'
    END)::TEXT AS outcome
`

type AcceptContactRequestParams struct {
	RequesterUserID uuid.UUID `json:"requester_user_id"`
	ReceiverUserID  uuid.UUID `json:"receiver_user_id"`
}

func (q *Queries) AcceptContactRequest(ctx context.Context, arg AcceptContactRequestParams) (string, error) {
	row := q.db.QueryRow(ctx, acceptContactRequest, arg.RequesterUserID, arg.ReceiverUserID)
	var outcome string
	err := row.Scan(&outcome)
	return outcome, err
}

const deleteAndInsertContactRequest = `-- name: DeleteAndInsertContactRequest :exec
WITH deleted AS (
    DELETE FROM contact_requests
    WHERE requester_user_id = $2 AND receiver_user_id = $3
    RETURNING requester_user_id
)
INSERT INTO contact_requests (id, requester_user_id, receiver_user_id, status, nickname)
SELECT $1, $2, $3, 'pending', $4
WHERE EXISTS (SELECT 1 FROM deleted) OR NOT EXISTS (
    SELECT 1 FROM contact_requests 
    WHERE requester_user_id = $2 AND receiver_user_id = $3
)
`

type DeleteAndInsertContactRequestParams struct {
	ID              uuid.UUID `json:"id"`
	RequesterUserID uuid.UUID `json:"requester_user_id"`
	ReceiverUserID  uuid.UUID `json:"receiver_user_id"`
	Nickname        *string   `json:"nickname"`
}

func (q *Queries) DeleteAndInsertContactRequest(ctx context.Context, arg DeleteAndInsertContactRequestParams) error {
	_, err := q.db.Exec(ctx, deleteAndInsertContactRequest,
		arg.ID,
		arg.RequesterUserID,
		arg.ReceiverUserID,
		arg.Nickname,
	)
	return err
}

const deleteContact = `-- name: DeleteContact :one
WITH deleted AS (
    DELETE FROM user_contacts AS uc
    WHERE uc.owner_user_id = $1
      AND uc.contact_user_id = ANY($2::uuid[])
    RETURNING uc.contact_user_id
)
SELECT COUNT(*) AS removed
FROM deleted
`

type DeleteContactParams struct {
	OwnerUserID    uuid.UUID   `json:"owner_user_id"`
	ContactUserIds []uuid.UUID `json:"contact_user_ids"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteContact, arg.OwnerUserID, arg.ContactUserIds)
	var removed int64
	err := row.Scan(&removed)
	return removed, err
}

const getContactRequestStatus = `-- name: GetContactRequestStatus :one
SELECT status::text FROM contact_requests
WHERE requester_user_id = $1 AND receiver_user_id = $2
LIMIT 1
`

type GetContactRequestStatusParams struct {
	RequesterUserID uuid.UUID `json:"requester_user_id"`
	ReceiverUserID  uuid.UUID `json:"receiver_user_id"`
}

func (q *Queries) GetContactRequestStatus(ctx context.Context, arg GetContactRequestStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getContactRequestStatus, arg.RequesterUserID, arg.ReceiverUserID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getPendingContactRequestsLite = `-- name: GetPendingContactRequestsLite :many
SELECT
    cr.requester_user_id AS id,
    cr.nickname,
    cr.created_at AS request_created_at,
    cr.updated_at AS request_updated_at,
    cr.status::text AS status
FROM contact_requests cr
WHERE cr.receiver_user_id = $1
  AND cr.status = 'pending'
ORDER BY cr.created_at DESC
`

type GetPendingContactRequestsLiteRow struct {
	ID               uuid.UUID `json:"id"`
	Nickname         *string   `json:"nickname"`
	RequestCreatedAt time.Time `json:"request_created_at"`
	RequestUpdatedAt time.Time `json:"request_updated_at"`
	Status           string    `json:"status"`
}

func (q *Queries) GetPendingContactRequestsLite(ctx context.Context, receiverUserID uuid.UUID) ([]GetPendingContactRequestsLiteRow, error) {
	rows, err := q.db.Query(ctx, getPendingContactRequestsLite, receiverUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingContactRequestsLiteRow
	for rows.Next() {
		var i GetPendingContactRequestsLiteRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.RequestCreatedAt,
			&i.RequestUpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSentContactRequestsLite = `-- name: GetSentContactRequestsLite :many
SELECT
    cr.receiver_user_id AS id,
    cr.nickname,
    cr.created_at AS request_created_at,
    cr.updated_at AS request_updated_at,
    cr.status::text AS status
FROM contact_requests cr
WHERE cr.requester_user_id = $1
  AND cr.status IN ('pending', 'declined')
ORDER BY cr.created_at DESC
`

type GetSentContactRequestsLiteRow struct {
	ID               uuid.UUID `json:"id"`
	Nickname         *string   `json:"nickname"`
	RequestCreatedAt time.Time `json:"request_created_at"`
	RequestUpdatedAt time.Time `json:"request_updated_at"`
	Status           string    `json:"status"`
}

func (q *Queries) GetSentContactRequestsLite(ctx context.Context, requesterUserID uuid.UUID) ([]GetSentContactRequestsLiteRow, error) {
	rows, err := q.db.Query(ctx, getSentContactRequestsLite, requesterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSentContactRequestsLiteRow
	for rows.Next() {
		var i GetSentContactRequestsLiteRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.RequestCreatedAt,
			&i.RequestUpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSingleUserContactLite = `-- name: GetSingleUserContactLite :one
SELECT
    uc.contact_user_id AS id,
    uc.nickname,
    uc.created_at AS contact_created_at,
    uc.updated_at AS contact_updated_at
FROM user_contacts uc
WHERE uc.owner_user_id = $1
  AND uc.contact_user_id = $2
LIMIT 1
`

type GetSingleUserContactLiteParams struct {
	OwnerUserID   uuid.UUID `json:"owner_user_id"`
	ContactUserID uuid.UUID `json:"contact_user_id"`
}

type GetSingleUserContactLiteRow struct {
	ID               uuid.UUID `json:"id"`
	Nickname         *string   `json:"nickname"`
	ContactCreatedAt time.Time `json:"contact_created_at"`
	ContactUpdatedAt time.Time `json:"contact_updated_at"`
}

func (q *Queries) GetSingleUserContactLite(ctx context.Context, arg GetSingleUserContactLiteParams) (GetSingleUserContactLiteRow, error) {
	row := q.db.QueryRow(ctx, getSingleUserContactLite, arg.OwnerUserID, arg.ContactUserID)
	var i GetSingleUserContactLiteRow
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.ContactCreatedAt,
		&i.ContactUpdatedAt,
	)
	return i, err
}

const getUserContactsLite = `-- name: GetUserContactsLite :many



SELECT
    uc.contact_user_id AS id,
    uc.nickname,
    uc.created_at AS contact_created_at,
    uc.updated_at AS contact_updated_at
FROM user_contacts uc
WHERE uc.owner_user_id = $1
ORDER BY uc.created_at DESC
`

type GetUserContactsLiteRow struct {
	ID               uuid.UUID `json:"id"`
	Nickname         *string   `json:"nickname"`
	ContactCreatedAt time.Time `json:"contact_created_at"`
	ContactUpdatedAt time.Time `json:"contact_updated_at"`
}

// ===========================================
// Contact existence helpers
// ===========================================
func (q *Queries) GetUserContactsLite(ctx context.Context, ownerUserID uuid.UUID) ([]GetUserContactsLiteRow, error) {
	rows, err := q.db.Query(ctx, getUserContactsLite, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserContactsLiteRow
	for rows.Next() {
		var i GetUserContactsLiteRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.ContactCreatedAt,
			&i.ContactUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWhoAddedYouLite = `-- name: GetUsersWhoAddedYouLite :many
SELECT
    uc.owner_user_id AS id,
    my_uc.nickname,
    uc.created_at AS contact_created_at,
    uc.updated_at AS contact_updated_at
FROM user_contacts uc
LEFT JOIN user_contacts my_uc
    ON my_uc.owner_user_id = $1
   AND my_uc.contact_user_id = uc.owner_user_id
WHERE uc.contact_user_id = $1
ORDER BY uc.created_at DESC
`

type GetUsersWhoAddedYouLiteRow struct {
	ID               uuid.UUID `json:"id"`
	Nickname         *string   `json:"nickname"`
	ContactCreatedAt time.Time `json:"contact_created_at"`
	ContactUpdatedAt time.Time `json:"contact_updated_at"`
}

func (q *Queries) GetUsersWhoAddedYouLite(ctx context.Context, ownerUserID uuid.UUID) ([]GetUsersWhoAddedYouLiteRow, error) {
	rows, err := q.db.Query(ctx, getUsersWhoAddedYouLite, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWhoAddedYouLiteRow
	for rows.Next() {
		var i GetUsersWhoAddedYouLiteRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.ContactCreatedAt,
			&i.ContactUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPendingRequest = `-- name: HasPendingRequest :one
SELECT EXISTS(
    SELECT 1 FROM contact_requests
    WHERE requester_user_id = $1 AND receiver_user_id = $2 AND status = 'pending'
)
`

type HasPendingRequestParams struct {
	RequesterUserID uuid.UUID `json:"requester_user_id"`
	ReceiverUserID  uuid.UUID `json:"receiver_user_id"`
}

func (q *Queries) HasPendingRequest(ctx context.Context, arg HasPendingRequestParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingRequest, arg.RequesterUserID, arg.ReceiverUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertContactRequest = `-- name: InsertContactRequest :exec
INSERT INTO contact_requests (id, requester_user_id, receiver_user_id, status, nickname)
VALUES ($1, $2, $3, 'pending', $4)
ON CONFLICT DO NOTHING
`

type InsertContactRequestParams struct {
	ID              uuid.UUID `json:"id"`
	RequesterUserID uuid.UUID `json:"requester_user_id"`
	ReceiverUserID  uuid.UUID `json:"receiver_user_id"`
	Nickname        *string   `json:"nickname"`
}

func (q *Queries) InsertContactRequest(ctx context.Context, arg InsertContactRequestParams) error {
	_, err := q.db.Exec(ctx, insertContactRequest,
		arg.ID,
		arg.RequesterUserID,
		arg.ReceiverUserID,
		arg.Nickname,
	)
	return err
}

const insertUserContact = `-- name: InsertUserContact :exec
INSERT INTO user_contacts (owner_user_id, contact_user_id, nickname)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertUserContactParams struct {
	OwnerUserID   uuid.UUID `json:"owner_user_id"`
	ContactUserID uuid.UUID `json:"contact_user_id"`
	Nickname      *string   `json:"nickname"`
}

func (q *Queries) InsertUserContact(ctx context.Context, arg InsertUserContactParams) error {
	_, err := q.db.Exec(ctx, insertUserContact, arg.OwnerUserID, arg.ContactUserID, arg.Nickname)
	return err
}

const isAlreadyContact = `-- name: IsAlreadyContact :one








SELECT EXISTS(
    SELECT 1 FROM user_contacts
    WHERE owner_user_id = $1 AND contact_user_id = $2
)
`

type IsAlreadyContactParams struct {
	OwnerUserID   uuid.UUID `json:"owner_user_id"`
	ContactUserID uuid.UUID `json:"contact_user_id"`
}

// ===========================================
// Contacts Queries for sqlc
// ===========================================
// ===========================================
// People Who Added You Query
// ===========================================
// ===========================================
// Avatar Privacy Circuit Breaker Logic
// ===========================================
// Both queries return RAW restriction flags for Go to process.
// Go applies the following priority order (circuit breaker pattern):
//
// Priority 1: Global PROFILE restriction
//
//	→ If restrict_profile = TRUE AND exception_profile = FALSE → HIDE avatar
//	→ If restrict_profile = TRUE AND exception_profile = TRUE → SHOW avatar
//	→ Otherwise, continue to Priority 2
//
// Priority 2: Global AVATAR restriction
//
//	→ If restrict_avatar = TRUE AND exception_avatar = FALSE → HIDE avatar
//	→ If restrict_avatar = TRUE AND exception_avatar = TRUE → SHOW avatar
//	→ Otherwise, continue to Priority 3
//
// Priority 3: User-level PROFILE restriction
//
//	→ If user_restrict_profile = TRUE → HIDE avatar
//	→ Otherwise, continue to Priority 4
//
// Priority 4: User-level AVATAR restriction
//
//	→ If user_restrict_avatar = TRUE → HIDE avatar
//	→ Otherwise, SHOW avatar
//
// Each level short-circuits evaluation (circuit breaker pattern).
// Privacy checks work identically for both queries because:
//   - cu.id = the contact being viewed (their restrictions apply)
//   - $1 = the viewer (you, checking if you're restricted/exempted)
//   - Direction of contact relationship doesn't affect privacy logic
//
// ===========================================
// ===========================================
// Contact creation helpers
// ===========================================
func (q *Queries) IsAlreadyContact(ctx context.Context, arg IsAlreadyContactParams) (bool, error) {
	row := q.db.QueryRow(ctx, isAlreadyContact, arg.OwnerUserID, arg.ContactUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const rejectContactRequest = `-- name: RejectContactRequest :one
WITH updated AS (
    UPDATE contact_requests AS cr
    SET status = 'declined'
    WHERE cr.requester_user_id = $1
      AND cr.receiver_user_id = $2
      AND cr.status = 'pending'
    RETURNING cr.id
), existing AS (
    SELECT cr.status
    FROM contact_requests AS cr
    WHERE cr.requester_user_id = $1
      AND cr.receiver_user_id = $2
    LIMIT 1
)
SELECT
    (CASE
        WHEN EXISTS (SELECT 1 FROM updated) THEN 'declined'
        WHEN (SELECT status FROM existing) IS NULL THEN 'not_found'
        ELSE 'processed'
    END)::TEXT AS outcome
`

type RejectContactRequestParams struct {
	RequesterUserID uuid.UUID `json:"requester_user_id"`
	ReceiverUserID  uuid.UUID `json:"receiver_user_id"`
}

func (q *Queries) RejectContactRequest(ctx context.Context, arg RejectContactRequestParams) (string, error) {
	row := q.db.QueryRow(ctx, rejectContactRequest, arg.RequesterUserID, arg.ReceiverUserID)
	var outcome string
	err := row.Scan(&outcome)
	return outcome, err
}

const undoContactRequest = `-- name: UndoContactRequest :one
WITH deleted AS (
    DELETE FROM contact_requests AS cr
    WHERE cr.requester_user_id = $1
      AND cr.receiver_user_id = $2
      AND cr.status = 'pending'
    RETURNING cr.id
)
SELECT
    (CASE
        WHEN EXISTS (SELECT 1 FROM deleted) THEN 'undone'
        ELSE 'not_found'
    END)::TEXT AS outcome
`

type UndoContactRequestParams struct {
	RequesterUserID uuid.UUID `json:"requester_user_id"`
	ReceiverUserID  uuid.UUID `json:"receiver_user_id"`
}

func (q *Queries) UndoContactRequest(ctx context.Context, arg UndoContactRequestParams) (string, error) {
	row := q.db.QueryRow(ctx, undoContactRequest, arg.RequesterUserID, arg.ReceiverUserID)
	var outcome string
	err := row.Scan(&outcome)
	return outcome, err
}

const updateContactNickname = `-- name: UpdateContactNickname :one
UPDATE user_contacts
SET nickname = $3,
    updated_at = now()
WHERE owner_user_id = $1
  AND contact_user_id = $2
RETURNING true AS updated
`

type UpdateContactNicknameParams struct {
	OwnerUserID   uuid.UUID `json:"owner_user_id"`
	ContactUserID uuid.UUID `json:"contact_user_id"`
	Nickname      *string   `json:"nickname"`
}

func (q *Queries) UpdateContactNickname(ctx context.Context, arg UpdateContactNicknameParams) (bool, error) {
	row := q.db.QueryRow(ctx, updateContactNickname, arg.OwnerUserID, arg.ContactUserID, arg.Nickname)
	var updated bool
	err := row.Scan(&updated)
	return updated, err
}
