// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package personal_contact_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptContactRequest(ctx context.Context, arg AcceptContactRequestParams) (string, error)
	DeleteAndInsertContactRequest(ctx context.Context, arg DeleteAndInsertContactRequestParams) error
	DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error)
	GetContactRequestStatus(ctx context.Context, arg GetContactRequestStatusParams) (string, error)
	GetPendingContactRequestsLite(ctx context.Context, receiverUserID uuid.UUID) ([]GetPendingContactRequestsLiteRow, error)
	GetSentContactRequestsLite(ctx context.Context, requesterUserID uuid.UUID) ([]GetSentContactRequestsLiteRow, error)
	GetSingleUserContactLite(ctx context.Context, arg GetSingleUserContactLiteParams) (GetSingleUserContactLiteRow, error)
	// ===========================================
	// Contact existence helpers
	// ===========================================
	GetUserContactsLite(ctx context.Context, ownerUserID uuid.UUID) ([]GetUserContactsLiteRow, error)
	GetUsersWhoAddedYouLite(ctx context.Context, ownerUserID uuid.UUID) ([]GetUsersWhoAddedYouLiteRow, error)
	HasPendingRequest(ctx context.Context, arg HasPendingRequestParams) (bool, error)
	InsertContactRequest(ctx context.Context, arg InsertContactRequestParams) error
	InsertUserContact(ctx context.Context, arg InsertUserContactParams) error
	// ===========================================
	// Contacts Queries for sqlc
	// ===========================================
	// ===========================================
	// People Who Added You Query
	// ===========================================
	// ===========================================
	// Avatar Privacy Circuit Breaker Logic
	// ===========================================
	// Both queries return RAW restriction flags for Go to process.
	// Go applies the following priority order (circuit breaker pattern):
	//
	// Priority 1: Global PROFILE restriction
	//   → If restrict_profile = TRUE AND exception_profile = FALSE → HIDE avatar
	//   → If restrict_profile = TRUE AND exception_profile = TRUE → SHOW avatar
	//   → Otherwise, continue to Priority 2
	//
	// Priority 2: Global AVATAR restriction
	//   → If restrict_avatar = TRUE AND exception_avatar = FALSE → HIDE avatar
	//   → If restrict_avatar = TRUE AND exception_avatar = TRUE → SHOW avatar
	//   → Otherwise, continue to Priority 3
	//
	// Priority 3: User-level PROFILE restriction
	//   → If user_restrict_profile = TRUE → HIDE avatar
	//   → Otherwise, continue to Priority 4
	//
	// Priority 4: User-level AVATAR restriction
	//   → If user_restrict_avatar = TRUE → HIDE avatar
	//   → Otherwise, SHOW avatar
	//
	// Each level short-circuits evaluation (circuit breaker pattern).
	// Privacy checks work identically for both queries because:
	//   - cu.id = the contact being viewed (their restrictions apply)
	//   - $1 = the viewer (you, checking if you're restricted/exempted)
	//   - Direction of contact relationship doesn't affect privacy logic
	// ===========================================
	// ===========================================
	// Contact creation helpers
	// ===========================================
	IsAlreadyContact(ctx context.Context, arg IsAlreadyContactParams) (bool, error)
	RejectContactRequest(ctx context.Context, arg RejectContactRequestParams) (string, error)
	UndoContactRequest(ctx context.Context, arg UndoContactRequestParams) (string, error)
	UpdateContactNickname(ctx context.Context, arg UpdateContactNicknameParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
