// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_profile.sql

package personal_profile_store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAloneUsername = `-- name: CreateAloneUsername :one
INSERT INTO
    alone_username (id, username)
VALUES ($1, $2)
RETURNING
    id, username, created_at, updated_at
`

type CreateAloneUsernameParams struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

func (q *Queries) CreateAloneUsername(ctx context.Context, arg CreateAloneUsernameParams) (AloneUsername, error) {
	row := q.db.QueryRow(ctx, createAloneUsername, arg.ID, arg.Username)
	var i AloneUsername
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAvatar = `-- name: CreateAvatar :one
INSERT INTO
    avatars (
        id,
        user_id,
        file_id,
        avatar_type,
        token_id,
        token_secret,
        token_expiry
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, user_id, file_id, avatar_type, token_id, token_secret, token_expiry, created_at, updated_at
`

type CreateAvatarParams struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	FileID      *string    `json:"file_id"`
	AvatarType  string     `json:"avatar_type"`
	TokenID     *string    `json:"token_id"`
	TokenSecret *string    `json:"token_secret"`
	TokenExpiry *time.Time `json:"token_expiry"`
}

// Inserts a new avatar and returns all columns
func (q *Queries) CreateAvatar(ctx context.Context, arg CreateAvatarParams) (Avatar, error) {
	row := q.db.QueryRow(ctx, createAvatar,
		arg.ID,
		arg.UserID,
		arg.FileID,
		arg.AvatarType,
		arg.TokenID,
		arg.TokenSecret,
		arg.TokenExpiry,
	)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileID,
		&i.AvatarType,
		&i.TokenID,
		&i.TokenSecret,
		&i.TokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO
    users (
        id,
        name,
        b64_cipher_chacha20poly1305_username,
        hmac_sha256_hex_username,
        profile_type
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, name, bio, profile_type, is_admin_blocked, admin_block_reason, hmac_sha256_hex_username, b64_cipher_chacha20poly1305_username, created_at, updated_at
`

type CreateUserParams struct {
	ID                                uuid.UUID `json:"id"`
	Name                              string    `json:"name"`
	B64CipherChacha20poly1305Username string    `json:"b64_cipher_chacha20poly1305_username"`
	HmacSha256HexUsername             string    `json:"hmac_sha256_hex_username"`
	ProfileType                       string    `json:"profile_type"`
}

// ======================================
// Profile Table Queries for sqlc
// ======================================
// Inserts a new user and returns all columns
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.B64CipherChacha20poly1305Username,
		arg.HmacSha256HexUsername,
		arg.ProfileType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.ProfileType,
		&i.IsAdminBlocked,
		&i.AdminBlockReason,
		&i.HmacSha256HexUsername,
		&i.B64CipherChacha20poly1305Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAvatar = `-- name: DeleteAvatar :exec
DELETE FROM avatars WHERE user_id = $1 AND avatar_type = 'profile'
`

// Deletes the main profile avatar for a user (called from ConfirmAvatarUpload tx when replacing)
func (q *Queries) DeleteAvatar(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAvatar, userID)
	return err
}

const getActiveAvatar = `-- name: GetActiveAvatar :one
SELECT id, file_id FROM avatars WHERE user_id = $1 AND avatar_type = 'profile'
`

type GetActiveAvatarRow struct {
	ID     uuid.UUID `json:"id"`
	FileID *string   `json:"file_id"`
}

// Fetches the id and file_id for the main profile avatar
func (q *Queries) GetActiveAvatar(ctx context.Context, userID uuid.UUID) (GetActiveAvatarRow, error) {
	row := q.db.QueryRow(ctx, getActiveAvatar, userID)
	var i GetActiveAvatarRow
	err := row.Scan(&i.ID, &i.FileID)
	return i, err
}

const getAvatarFileID = `-- name: GetAvatarFileID :one
SELECT file_id FROM avatars WHERE user_id = $1 AND avatar_type = 'profile'
`

// Fetches the storage file_id for the main profile avatar
func (q *Queries) GetAvatarFileID(ctx context.Context, userID uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getAvatarFileID, userID)
	var file_id *string
	err := row.Scan(&file_id)
	return file_id, err
}

const getContactableProfilesForViewer = `-- name: GetContactableProfilesForViewer :many
SELECT
    u.id,
    u.name,
    u.b64_cipher_chacha20poly1305_username AS username,
    u.bio,
    u.profile_type,
    a.file_id,
    a.token_id,
    a.token_secret,
    a.token_expiry,
    au.keys_revision,
    COALESCE(ugr.restrict_profile, FALSE) AS global_restrict_profile,
    COALESCE(ugr.restrict_avatar, FALSE) AS global_restrict_avatar,
    COALESCE(ugre.exception_profile, FALSE) AS exception_global_profile,
    COALESCE(ugre.exception_avatar, FALSE) AS exception_global_avatar,
    COALESCE(ur.restrict_profile, FALSE) AS user_restrict_profile,
    COALESCE(ur.restrict_avatar, FALSE) AS user_restrict_avatar
FROM
    users u
    INNER JOIN auth_users au ON u.id = au.id
    LEFT JOIN avatars a ON u.id = a.user_id
    AND a.avatar_type = 'profile'
    LEFT JOIN user_global_restrictions ugr ON u.id = ugr.user_id
    LEFT JOIN user_global_restriction_exemptions ugre ON u.id = ugre.user_id
    AND ugre.exempted_user_id = $1
    LEFT JOIN user_restrictions ur ON u.id = ur.user_id
    AND ur.restricted_user_id = $1
WHERE
    u.id = ANY (
        $2::uuid []
    )
    AND u.is_admin_blocked IS FALSE
    AND u.profile_type IN ('public', 'personal')
    AND NOT EXISTS (
        SELECT 1 FROM user_blocks ub
        WHERE (ub.blocker_user_id = $1 AND ub.blocked_user_id = u.id)
           OR (ub.blocker_user_id = u.id AND ub.blocked_user_id = $1)
    )
ORDER BY u.id
`

type GetContactableProfilesForViewerParams struct {
	ViewerUserID  uuid.UUID   `json:"viewer_user_id"`
	TargetUserIds []uuid.UUID `json:"target_user_ids"`
}

type GetContactableProfilesForViewerRow struct {
	ID                     uuid.UUID  `json:"id"`
	Name                   string     `json:"name"`
	Username               string     `json:"username"`
	Bio                    *string    `json:"bio"`
	ProfileType            string     `json:"profile_type"`
	FileID                 *string    `json:"file_id"`
	TokenID                *string    `json:"token_id"`
	TokenSecret            *string    `json:"token_secret"`
	TokenExpiry            *time.Time `json:"token_expiry"`
	KeysRevision           int32      `json:"keys_revision"`
	GlobalRestrictProfile  bool       `json:"global_restrict_profile"`
	GlobalRestrictAvatar   bool       `json:"global_restrict_avatar"`
	ExceptionGlobalProfile bool       `json:"exception_global_profile"`
	ExceptionGlobalAvatar  bool       `json:"exception_global_avatar"`
	UserRestrictProfile    bool       `json:"user_restrict_profile"`
	UserRestrictAvatar     bool       `json:"user_restrict_avatar"`
}

// GetContactableProfilesForViewer fetches profiles for contact enrichment with privacy filtering.
func (q *Queries) GetContactableProfilesForViewer(ctx context.Context, arg GetContactableProfilesForViewerParams) ([]GetContactableProfilesForViewerRow, error) {
	rows, err := q.db.Query(ctx, getContactableProfilesForViewer, arg.ViewerUserID, arg.TargetUserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactableProfilesForViewerRow
	for rows.Next() {
		var i GetContactableProfilesForViewerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Bio,
			&i.ProfileType,
			&i.FileID,
			&i.TokenID,
			&i.TokenSecret,
			&i.TokenExpiry,
			&i.KeysRevision,
			&i.GlobalRestrictProfile,
			&i.GlobalRestrictAvatar,
			&i.ExceptionGlobalProfile,
			&i.ExceptionGlobalAvatar,
			&i.UserRestrictProfile,
			&i.UserRestrictAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactableUserIDs = `-- name: GetContactableUserIDs :many
SELECT u.id
FROM users u
WHERE
    u.id = ANY (
        $1::uuid []
    )
    AND u.is_admin_blocked IS FALSE
    AND NOT EXISTS (
        SELECT 1 FROM user_blocks ub
        WHERE (ub.blocker_user_id = $2 AND ub.blocked_user_id = u.id)
           OR (ub.blocker_user_id = u.id AND ub.blocked_user_id = $2)
    )
ORDER BY u.id
`

type GetContactableUserIDsParams struct {
	TargetUserIds []uuid.UUID `json:"target_user_ids"`
	ViewerUserID  uuid.UUID   `json:"viewer_user_id"`
}

// Checks which target user IDs are contactable for a viewer (not blocked, not admin-blocked).
func (q *Queries) GetContactableUserIDs(ctx context.Context, arg GetContactableUserIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getContactableUserIDs, arg.TargetUserIds, arg.ViewerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByHashedUsernameForContact = `-- name: GetUserByHashedUsernameForContact :one
SELECT id, name, bio, profile_type, is_admin_blocked, admin_block_reason, hmac_sha256_hex_username, b64_cipher_chacha20poly1305_username, created_at, updated_at
FROM users
WHERE
    hmac_sha256_hex_username = $1
    AND is_admin_blocked IS NOT TRUE
`

func (q *Queries) GetUserByHashedUsernameForContact(ctx context.Context, hmacSha256HexUsername string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByHashedUsernameForContact, hmacSha256HexUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.ProfileType,
		&i.IsAdminBlocked,
		&i.AdminBlockReason,
		&i.HmacSha256HexUsername,
		&i.B64CipherChacha20poly1305Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCoreProfile = `-- name: GetUserCoreProfile :one
SELECT id, is_admin_blocked, profile_type
FROM users
WHERE id = $1
`

type GetUserCoreProfileRow struct {
	ID             uuid.UUID `json:"id"`
	IsAdminBlocked bool      `json:"is_admin_blocked"`
	ProfileType    string    `json:"profile_type"`
}

// Fetches minimal user info for eligibility checks
func (q *Queries) GetUserCoreProfile(ctx context.Context, id uuid.UUID) (GetUserCoreProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserCoreProfile, id)
	var i GetUserCoreProfileRow
	err := row.Scan(&i.ID, &i.IsAdminBlocked, &i.ProfileType)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT u.id, u.name, u.bio, u.profile_type, u.is_admin_blocked, u.admin_block_reason, u.hmac_sha256_hex_username, u.b64_cipher_chacha20poly1305_username, u.created_at, u.updated_at, a.file_id, a.token_id, a.token_secret, a.token_expiry
FROM users u
    LEFT JOIN avatars a ON a.user_id = u.id
    AND a.avatar_type = 'profile'
WHERE
    u.id = $1
`

type GetUserProfileRow struct {
	ID                                uuid.UUID  `json:"id"`
	Name                              string     `json:"name"`
	Bio                               *string    `json:"bio"`
	ProfileType                       string     `json:"profile_type"`
	IsAdminBlocked                    bool       `json:"is_admin_blocked"`
	AdminBlockReason                  *string    `json:"admin_block_reason"`
	HmacSha256HexUsername             string     `json:"hmac_sha256_hex_username"`
	B64CipherChacha20poly1305Username string     `json:"b64_cipher_chacha20poly1305_username"`
	CreatedAt                         time.Time  `json:"created_at"`
	UpdatedAt                         time.Time  `json:"updated_at"`
	FileID                            *string    `json:"file_id"`
	TokenID                           *string    `json:"token_id"`
	TokenSecret                       *string    `json:"token_secret"`
	TokenExpiry                       *time.Time `json:"token_expiry"`
}

// Returns full user record along with its profile avatar file_id
func (q *Queries) GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.ProfileType,
		&i.IsAdminBlocked,
		&i.AdminBlockReason,
		&i.HmacSha256HexUsername,
		&i.B64CipherChacha20poly1305Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileID,
		&i.TokenID,
		&i.TokenSecret,
		&i.TokenExpiry,
	)
	return i, err
}

const isUserAdminBlocked = `-- name: IsUserAdminBlocked :one
SELECT EXISTS (
        SELECT 1
        FROM users
        WHERE
            id = $1
            AND is_admin_blocked IS TRUE
    )
`

// Returns true if the user is admin-blocked
func (q *Queries) IsUserAdminBlocked(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAdminBlocked, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUserExists = `-- name: IsUserExists :one
SELECT EXISTS ( SELECT 1 FROM users WHERE id = $1 )
`

func (q *Queries) IsUserExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateAvatarFileID = `-- name: UpdateAvatarFileID :exec
UPDATE avatars
SET file_id = $2
WHERE user_id = $1 AND avatar_type = 'profile'
`

type UpdateAvatarFileIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	FileID *string   `json:"file_id"`
}

// Updates only the file_id for the main profile avatar (token columns unused per spec §3.C).
func (q *Queries) UpdateAvatarFileID(ctx context.Context, arg UpdateAvatarFileIDParams) error {
	_, err := q.db.Exec(ctx, updateAvatarFileID, arg.UserID, arg.FileID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET
    name = COALESCE($2, name),
    bio = COALESCE($3, bio),
    profile_type = COALESCE($4, profile_type)
WHERE
    id = $1
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID `json:"id"`
	Name        *string   `json:"name"`
	Bio         *string   `json:"bio"`
	ProfileType *string   `json:"profile_type"`
}

// Updates user profile fields
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.Bio,
		arg.ProfileType,
	)
	return err
}
