// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package personal_profile_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAloneUsername(ctx context.Context, arg CreateAloneUsernameParams) (AloneUsername, error)
	// Inserts a new avatar and returns all columns
	CreateAvatar(ctx context.Context, arg CreateAvatarParams) (Avatar, error)
	// ======================================
	// Profile Table Queries for sqlc
	// ======================================
	// Inserts a new user and returns all columns
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserBlock(ctx context.Context, arg CreateUserBlockParams) error
	// Deletes the main profile avatar for a user (called from ConfirmAvatarUpload tx when replacing)
	DeleteAvatar(ctx context.Context, userID uuid.UUID) error
	// Fetches the id and file_id for the main profile avatar
	GetActiveAvatar(ctx context.Context, userID uuid.UUID) (GetActiveAvatarRow, error)
	// Fetches the storage file_id for the main profile avatar
	GetAvatarFileID(ctx context.Context, userID uuid.UUID) (*string, error)
	// Fetches profiles for the block list. Admin-blocked and private targets are
	// omitted as whole items; a target-side block is returned so the service can
	// retain identity fields while hiding bio and avatar fields.
	GetBlockListProfilesForViewer(ctx context.Context, arg GetBlockListProfilesForViewerParams) ([]GetBlockListProfilesForViewerRow, error)
	// GetContactableProfilesForViewer fetches profiles for contact enrichment with
	// privacy filtering. The returned rows are used by the chat list, contact list,
	// contact requests, and other surfaces to populate the "other user" identity
	// block (name, username, bio, profile_type, avatar trio, keys revision).
	//
	// Privacy exclusion is binary per user: a user is either IN the result set
	// (all six identity fields returned) or OUT of it (no row at all, the
	// caller treats them as missing). An excluded user means the wire payload
	// the caller builds will have name/username/profile_type as `""` and
	// bio/avatar_url/avatar_file_id as `null`. The frontend
	// (upsertFromServer in $userProfilesState) treats these wire encodings
	// differently on purpose:
	//   - `""` on name/username is "no data this round" (frontend preserves the
	//     owner's prior-known identity so the chat list stays identifiable).
	//   - `""` on profile_type IS authoritative clear (frontend would otherwise
	//     render a misleading "Public" badge on the user profile screen).
	//   - `null` on bio/avatar_url/avatar_file_id IS authoritative clear.
	//   - Omitted keys preserve the prior value (partial-payload case).
	// This split is what lets the chat list keep showing a prior-known name
	// while the user profile screen shows no stale profile state.
	//
	// The WHERE clause is the privacy contract. Each condition excludes a
	// different privacy-exclusion case; the caller does not need to know which
	// one fired, the wire shape is identical for all of them:
	//   - `u.is_admin_blocked IS FALSE`           : admin removed this user.
	//   - `u.profile_type IN ('public', 'personal')` : the user switched to a
	//                                                  private profile.
	//   - `NOT EXISTS (... user_blocks ...)`      : either side user-blocked
	//                                                  the other.
	GetContactableProfilesForViewer(ctx context.Context, arg GetContactableProfilesForViewerParams) ([]GetContactableProfilesForViewerRow, error)
	// Returns just the subset of target_user_ids that pass the contactable
	// filter for chat message filtering. It uses the same bidirectional block
	// exclusion as GetContactableProfilesForViewer; the chat endpoint needs to
	// hide messages from users blocked in either direction.
	// Also excludes admin-blocked users.
	GetContactableUserIDs(ctx context.Context, arg GetContactableUserIDsParams) ([]uuid.UUID, error)
	// Returns the users blocked by a given blocker, newest first.
	GetUserBlocks(ctx context.Context, blockerUserID uuid.UUID) ([]GetUserBlocksRow, error)
	GetUserByHashedUsernameForContact(ctx context.Context, hmacSha256HexUsername string) (User, error)
	// Fetches minimal user info for eligibility checks
	GetUserCoreProfile(ctx context.Context, id uuid.UUID) (GetUserCoreProfileRow, error)
	// Returns full user record along with its profile avatar file_id
	GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error)
	// Returns block status flags between two users as individual boolean columns.
	IsBlockedBetweenUsers(ctx context.Context, arg IsBlockedBetweenUsersParams) (IsBlockedBetweenUsersRow, error)
	// Returns block status flags per target user for a requester and target user list.
	IsBlockedBetweenUsersBatch(ctx context.Context, arg IsBlockedBetweenUsersBatchParams) ([]IsBlockedBetweenUsersBatchRow, error)
	// Returns 0 if no block, 1 if blocker is $1 (requester blocked target), 2 if blocker is $2 (target blocked requester)
	IsEitherBlocked(ctx context.Context, arg IsEitherBlockedParams) (int32, error)
	// Returns true if the user is admin-blocked
	IsUserAdminBlocked(ctx context.Context, id uuid.UUID) (bool, error)
	IsUserExists(ctx context.Context, id uuid.UUID) (bool, error)
	// Updates only the file_id for the main profile avatar (token columns unused per spec §3.C).
	UpdateAvatarFileID(ctx context.Context, arg UpdateAvatarFileIDParams) error
	// Updates user profile fields
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
