// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package personal_profile_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAloneUsername(ctx context.Context, arg CreateAloneUsernameParams) (AloneUsername, error)
	// Inserts a new avatar and returns all columns
	CreateAvatar(ctx context.Context, arg CreateAvatarParams) (Avatar, error)
	// ======================================
	// Profile Table Queries for sqlc
	// ======================================
	// Inserts a new user and returns all columns
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserBlock(ctx context.Context, arg CreateUserBlockParams) error
	// Deletes the main profile avatar for a user (called from ConfirmAvatarUpload tx when replacing)
	DeleteAvatar(ctx context.Context, userID uuid.UUID) error
	// Fetches the id and file_id for the main profile avatar
	GetActiveAvatar(ctx context.Context, userID uuid.UUID) (GetActiveAvatarRow, error)
	// Fetches the storage file_id for the main profile avatar
	GetAvatarFileID(ctx context.Context, userID uuid.UUID) (*string, error)
	// GetContactableProfilesForViewer fetches profiles for contact enrichment with privacy filtering.
	GetContactableProfilesForViewer(ctx context.Context, arg GetContactableProfilesForViewerParams) ([]GetContactableProfilesForViewerRow, error)
	// Checks which target user IDs are contactable for a viewer (not blocked, not admin-blocked).
	GetContactableUserIDs(ctx context.Context, arg GetContactableUserIDsParams) ([]uuid.UUID, error)
	GetUserByHashedUsernameForContact(ctx context.Context, hmacSha256HexUsername string) (User, error)
	// Fetches minimal user info for eligibility checks
	GetUserCoreProfile(ctx context.Context, id uuid.UUID) (GetUserCoreProfileRow, error)
	// Returns full user record along with its profile avatar file_id
	GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error)
	// Returns block status flags between two users as individual boolean columns.
	IsBlockedBetweenUsers(ctx context.Context, arg IsBlockedBetweenUsersParams) (IsBlockedBetweenUsersRow, error)
	// Returns block status flags per target user for a requester and target user list.
	IsBlockedBetweenUsersBatch(ctx context.Context, arg IsBlockedBetweenUsersBatchParams) ([]IsBlockedBetweenUsersBatchRow, error)
	// Returns 0 if no block, 1 if blocker is $1 (requester blocked target), 2 if blocker is $2 (target blocked requester)
	IsEitherBlocked(ctx context.Context, arg IsEitherBlockedParams) (int32, error)
	// Returns true if the user is admin-blocked
	IsUserAdminBlocked(ctx context.Context, id uuid.UUID) (bool, error)
	IsUserExists(ctx context.Context, id uuid.UUID) (bool, error)
	// Updates only the file_id for the main profile avatar (token columns unused per spec §3.C).
	UpdateAvatarFileID(ctx context.Context, arg UpdateAvatarFileIDParams) error
	// Updates user profile fields
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
