// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_profile.sql

package personal_profile_store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAloneUsername = `-- name: CreateAloneUsername :one
INSERT INTO
    alone_username (id, username)
VALUES ($1, $2)
RETURNING
    id, username, created_at, updated_at
`

type CreateAloneUsernameParams struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

func (q *Queries) CreateAloneUsername(ctx context.Context, arg CreateAloneUsernameParams) (AloneUsername, error) {
	row := q.db.QueryRow(ctx, createAloneUsername, arg.ID, arg.Username)
	var i AloneUsername
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAvatar = `-- name: CreateAvatar :one
INSERT INTO
    avatars (
        id,
        user_id,
        file_id,
        avatar_type,
        token_id,
        token_secret,
        token_expiry
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, user_id, file_id, avatar_type, token_id, token_secret, token_expiry, created_at, updated_at
`

type CreateAvatarParams struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	FileID      string             `json:"file_id"`
	AvatarType  string             `json:"avatar_type"`
	TokenID     *string            `json:"token_id"`
	TokenSecret *string            `json:"token_secret"`
	TokenExpiry pgtype.Timestamptz `json:"token_expiry"`
}

// Inserts a new avatar and returns all columns
func (q *Queries) CreateAvatar(ctx context.Context, arg CreateAvatarParams) (Avatar, error) {
	row := q.db.QueryRow(ctx, createAvatar,
		arg.ID,
		arg.UserID,
		arg.FileID,
		arg.AvatarType,
		arg.TokenID,
		arg.TokenSecret,
		arg.TokenExpiry,
	)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileID,
		&i.AvatarType,
		&i.TokenID,
		&i.TokenSecret,
		&i.TokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO
    users (
        id,
        name,
        b64_cipher_chacha20poly1305_username,
        hmac_sha256_hex_username,
        profile_type
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, name, bio, profile_type, is_admin_blocked, admin_block_reason, hmac_sha256_hex_username, b64_cipher_chacha20poly1305_username, created_at, updated_at
`

type CreateUserParams struct {
	ID                                uuid.UUID `json:"id"`
	Name                              string    `json:"name"`
	B64CipherChacha20poly1305Username string    `json:"b64_cipher_chacha20poly1305_username"`
	HmacSha256HexUsername             string    `json:"hmac_sha256_hex_username"`
	ProfileType                       string    `json:"profile_type"`
}

// ======================================
// Profile Table Queries for sqlc
// ======================================
// Inserts a new user and returns all columns
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.B64CipherChacha20poly1305Username,
		arg.HmacSha256HexUsername,
		arg.ProfileType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.ProfileType,
		&i.IsAdminBlocked,
		&i.AdminBlockReason,
		&i.HmacSha256HexUsername,
		&i.B64CipherChacha20poly1305Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAvatar = `-- name: DeleteAvatar :exec
DELETE FROM avatars WHERE user_id = $1 AND file_id = $1::TEXT
`

// Deletes the main profile avatar for a user
func (q *Queries) DeleteAvatar(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAvatar, userID)
	return err
}

const getProfilesForContactViewer = `-- name: GetProfilesForContactViewer :many
SELECT
    u.id,
    u.name,
    u.b64_cipher_chacha20poly1305_username AS username,
    u.bio,
    a.file_id,
    a.token_id,
    a.token_secret,
    a.token_expiry,
    COALESCE(ugr.restrict_profile, FALSE) AS global_restrict_profile,
    COALESCE(ugr.restrict_avatar, FALSE) AS global_restrict_avatar,
    COALESCE(ugre.exception_profile, FALSE) AS exception_global_profile,
    COALESCE(ugre.exception_avatar, FALSE) AS exception_global_avatar,
    COALESCE(ur.restrict_profile, FALSE) AS user_restrict_profile,
    COALESCE(ur.restrict_avatar, FALSE) AS user_restrict_avatar
FROM users u
LEFT JOIN avatars a
    ON u.id = a.user_id
   AND a.avatar_type = 'profile'
LEFT JOIN user_global_restrictions ugr
    ON u.id = ugr.user_id
LEFT JOIN user_global_restriction_exemptions ugre
    ON u.id = ugre.user_id
   AND ugre.exempted_user_id = $1
LEFT JOIN user_restrictions ur
    ON u.id = ur.user_id
   AND ur.restricted_user_id = $1
WHERE u.id = ANY($2::uuid[])
  AND u.is_admin_blocked IS FALSE
ORDER BY u.id
`

type GetProfilesForContactViewerParams struct {
	ViewerUserID  uuid.UUID   `json:"viewer_user_id"`
	TargetUserIds []uuid.UUID `json:"target_user_ids"`
}

type GetProfilesForContactViewerRow struct {
	ID                     uuid.UUID          `json:"id"`
	Name                   string             `json:"name"`
	Username               string             `json:"username"`
	Bio                    *string            `json:"bio"`
	FileID                 *string            `json:"file_id"`
	TokenID                *string            `json:"token_id"`
	TokenSecret            *string            `json:"token_secret"`
	TokenExpiry            pgtype.Timestamptz `json:"token_expiry"`
	GlobalRestrictProfile  bool               `json:"global_restrict_profile"`
	GlobalRestrictAvatar   bool               `json:"global_restrict_avatar"`
	ExceptionGlobalProfile bool               `json:"exception_global_profile"`
	ExceptionGlobalAvatar  bool               `json:"exception_global_avatar"`
	UserRestrictProfile    bool               `json:"user_restrict_profile"`
	UserRestrictAvatar     bool               `json:"user_restrict_avatar"`
}

func (q *Queries) GetProfilesForContactViewer(ctx context.Context, arg GetProfilesForContactViewerParams) ([]GetProfilesForContactViewerRow, error) {
	rows, err := q.db.Query(ctx, getProfilesForContactViewer, arg.ViewerUserID, arg.TargetUserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfilesForContactViewerRow
	for rows.Next() {
		var i GetProfilesForContactViewerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Bio,
			&i.FileID,
			&i.TokenID,
			&i.TokenSecret,
			&i.TokenExpiry,
			&i.GlobalRestrictProfile,
			&i.GlobalRestrictAvatar,
			&i.ExceptionGlobalProfile,
			&i.ExceptionGlobalAvatar,
			&i.UserRestrictProfile,
			&i.UserRestrictAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByHashedUsernameForContact = `-- name: GetUserByHashedUsernameForContact :one
SELECT id, name, bio, profile_type, is_admin_blocked, admin_block_reason, hmac_sha256_hex_username, b64_cipher_chacha20poly1305_username, created_at, updated_at
FROM users
WHERE hmac_sha256_hex_username = $1
  AND is_admin_blocked IS NOT TRUE
`

func (q *Queries) GetUserByHashedUsernameForContact(ctx context.Context, hmacSha256HexUsername string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByHashedUsernameForContact, hmacSha256HexUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.ProfileType,
		&i.IsAdminBlocked,
		&i.AdminBlockReason,
		&i.HmacSha256HexUsername,
		&i.B64CipherChacha20poly1305Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCoreProfile = `-- name: GetUserCoreProfile :one
SELECT id, name, bio, profile_type, is_admin_blocked, admin_block_reason, hmac_sha256_hex_username, b64_cipher_chacha20poly1305_username, created_at, updated_at FROM users WHERE id = $1
`

// Minimal user profile without avatar join
func (q *Queries) GetUserCoreProfile(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserCoreProfile, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.ProfileType,
		&i.IsAdminBlocked,
		&i.AdminBlockReason,
		&i.HmacSha256HexUsername,
		&i.B64CipherChacha20poly1305Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT u.id, u.name, u.bio, u.profile_type, u.is_admin_blocked, u.admin_block_reason, u.hmac_sha256_hex_username, u.b64_cipher_chacha20poly1305_username, u.created_at, u.updated_at, a.file_id, a.token_id, a.token_secret, a.token_expiry
FROM users u
    LEFT JOIN avatars a ON a.user_id = u.id
    AND a.file_id = u.id::TEXT -- main profile avatar (file_id == user_id)
WHERE
    u.id = $1
`

type GetUserProfileRow struct {
	ID                                uuid.UUID          `json:"id"`
	Name                              string             `json:"name"`
	Bio                               *string            `json:"bio"`
	ProfileType                       string             `json:"profile_type"`
	IsAdminBlocked                    bool               `json:"is_admin_blocked"`
	AdminBlockReason                  *string            `json:"admin_block_reason"`
	HmacSha256HexUsername             string             `json:"hmac_sha256_hex_username"`
	B64CipherChacha20poly1305Username string             `json:"b64_cipher_chacha20poly1305_username"`
	CreatedAt                         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                         pgtype.Timestamptz `json:"updated_at"`
	FileID                            *string            `json:"file_id"`
	TokenID                           *string            `json:"token_id"`
	TokenSecret                       *string            `json:"token_secret"`
	TokenExpiry                       pgtype.Timestamptz `json:"token_expiry"`
}

// Returns full user record along with its profile avatar tokens and file_id
func (q *Queries) GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.ProfileType,
		&i.IsAdminBlocked,
		&i.AdminBlockReason,
		&i.HmacSha256HexUsername,
		&i.B64CipherChacha20poly1305Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileID,
		&i.TokenID,
		&i.TokenSecret,
		&i.TokenExpiry,
	)
	return i, err
}

const isUserAdminBlocked = `-- name: IsUserAdminBlocked :one
SELECT EXISTS (
        SELECT 1
        FROM users
        WHERE
            id = $1
            AND is_admin_blocked IS TRUE
    )
`

// Returns true if the user is admin-blocked
func (q *Queries) IsUserAdminBlocked(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAdminBlocked, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUserExists = `-- name: IsUserExists :one
SELECT EXISTS ( SELECT 1 FROM users WHERE id = $1 )
`

func (q *Queries) IsUserExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUserProfilePicExists = `-- name: IsUserProfilePicExists :one
SELECT EXISTS (
        SELECT 1
        FROM users u
            JOIN avatars a ON a.user_id = u.id
        WHERE
            u.id = $1
            AND a.file_id = u.id::TEXT
    )
`

// Checks if the user exists and has a main profile picture
func (q *Queries) IsUserProfilePicExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserProfilePicExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUsersAfter = `-- name: ListUsersAfter :many
SELECT id, name, bio, profile_type, is_admin_blocked, admin_block_reason, hmac_sha256_hex_username, b64_cipher_chacha20poly1305_username, created_at, updated_at
FROM users
WHERE
    created_at < $1
ORDER BY created_at DESC
LIMIT $2
`

type ListUsersAfterParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

// Returns users created before a certain timestamp (keyset pagination)
func (q *Queries) ListUsersAfter(ctx context.Context, arg ListUsersAfterParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersAfter, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.ProfileType,
			&i.IsAdminBlocked,
			&i.AdminBlockReason,
			&i.HmacSha256HexUsername,
			&i.B64CipherChacha20poly1305Username,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvatarTokens = `-- name: UpdateAvatarTokens :one
UPDATE avatars
SET
    token_id = $2,
    token_secret = $3,
    token_expiry = $4
WHERE
    user_id = $1
    AND file_id = $1::TEXT
RETURNING
    id, user_id, file_id, avatar_type, token_id, token_secret, token_expiry, created_at, updated_at
`

type UpdateAvatarTokensParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	TokenID     *string            `json:"token_id"`
	TokenSecret *string            `json:"token_secret"`
	TokenExpiry pgtype.Timestamptz `json:"token_expiry"`
}

// Updates token_id, token_secret, and token_expiry for the main profile avatar (where user_id == file_id)
func (q *Queries) UpdateAvatarTokens(ctx context.Context, arg UpdateAvatarTokensParams) (Avatar, error) {
	row := q.db.QueryRow(ctx, updateAvatarTokens,
		arg.UserID,
		arg.TokenID,
		arg.TokenSecret,
		arg.TokenExpiry,
	)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileID,
		&i.AvatarType,
		&i.TokenID,
		&i.TokenSecret,
		&i.TokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    name = COALESCE($2, name),
    bio = COALESCE($3, bio),
    profile_type = COALESCE(
        $4,
        profile_type
    )
WHERE
    id = $1
RETURNING
    id, name, bio, profile_type, is_admin_blocked, admin_block_reason, hmac_sha256_hex_username, b64_cipher_chacha20poly1305_username, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID `json:"id"`
	Name        *string   `json:"name"`
	Bio         *string   `json:"bio"`
	ProfileType *string   `json:"profile_type"`
}

// Updates user profile fields conditionally based on provided values (NULL values are ignored)
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.Bio,
		arg.ProfileType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.ProfileType,
		&i.IsAdminBlocked,
		&i.AdminBlockReason,
		&i.HmacSha256HexUsername,
		&i.B64CipherChacha20poly1305Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
