// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package personal_profile_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAloneUsername(ctx context.Context, arg CreateAloneUsernameParams) (AloneUsername, error)
	// Inserts a new avatar and returns all columns
	CreateAvatar(ctx context.Context, arg CreateAvatarParams) (Avatar, error)
	// ======================================
	// Profile Table Queries for sqlc
	// ======================================
	// Inserts a new user and returns all columns
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Deletes the main profile avatar for a user
	DeleteAvatar(ctx context.Context, userID uuid.UUID) error
	// Minimal user profile without avatar join
	GetUserCoreProfile(ctx context.Context, id uuid.UUID) (User, error)
	// Returns full user record along with its profile avatar tokens and file_id
	GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error)
	// Returns true if the user is admin-blocked
	IsUserAdminBlocked(ctx context.Context, id uuid.UUID) (bool, error)
	IsUserExists(ctx context.Context, id uuid.UUID) (bool, error)
	// Checks if the user exists and has a main profile picture
	IsUserProfilePicExists(ctx context.Context, id uuid.UUID) (bool, error)
	// Returns users created before a certain timestamp (keyset pagination)
	ListUsersAfter(ctx context.Context, arg ListUsersAfterParams) ([]User, error)
	// Updates token_id, token_secret, and token_expiry for the main profile avatar (where user_id == file_id)
	UpdateAvatarTokens(ctx context.Context, arg UpdateAvatarTokensParams) (Avatar, error)
	// Updates user profile fields conditionally based on provided values (NULL values are ignored)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
