-- +migrate Up
-- ======================================
-- Table: history_sync
--        Tracks end-to-end encrypted chat history synchronization requests.
--        Allows a secondary device to request history from a primary device.
-- ======================================
CREATE TABLE IF NOT EXISTS history_sync (
    id          UUID         PRIMARY KEY,                       -- Request ID generated by the backend
    user_id     UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id  UUID         NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    chats_json  JSONB        NOT NULL,                          -- V3 envelope ciphertext (secondary's encrypted request payload)
    payload     JSONB,                                          -- V3 envelope ciphertext (primary's encrypted response payload); NULL until uploaded
    expires_at  TIMESTAMPTZ  NOT NULL,                          -- 10-minute TTL; swept by background worker
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);

-- Ensure only one active history sync request per secondary session
CREATE UNIQUE INDEX IF NOT EXISTS idx_history_sync_session
    ON history_sync (session_id);

-- Index for locating sync requests by user ID (used for primary notifications and upload authorization)
CREATE INDEX IF NOT EXISTS idx_history_sync_user
    ON history_sync (user_id);

-- Index for the periodic TTL cleanup sweeper
CREATE INDEX IF NOT EXISTS idx_history_sync_expires
    ON history_sync (expires_at);

-- Index to find unanswered sync requests (payload is NULL) to replay if the primary device was offline
CREATE INDEX IF NOT EXISTS idx_history_sync_pending
    ON history_sync (user_id)
    WHERE payload IS NULL;

-- Drop existing trigger if already present
DROP TRIGGER IF EXISTS history_sync_timestamps_trigger ON history_sync;

-- Attach auto timestamp trigger (matches pattern of all other tables)
CREATE TRIGGER history_sync_timestamps_trigger
BEFORE INSERT OR UPDATE ON history_sync
FOR EACH ROW
EXECUTE FUNCTION set_timestamps();

-- ======================================
-- End of history_sync table section
-- ======================================
