// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package auth

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS ( SELECT 1 FROM auth_users WHERE email = $1 )
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkSessionIsValid = `-- name: CheckSessionIsValid :one

SELECT EXISTS (
        SELECT 1
        FROM sessions
        WHERE
            token_hash = $1
            AND auth_user_id = $2
            AND expires_at > now()
    )
`

type CheckSessionIsValidParams struct {
	TokenHash  string    `json:"token_hash"`
	AuthUserID uuid.UUID `json:"auth_user_id"`
}

// ======================================
// Auth Queries
// ======================================
// Checks if a session is valid for a specific user and not expired
func (q *Queries) CheckSessionIsValid(ctx context.Context, arg CheckSessionIsValidParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSessionIsValid, arg.TokenHash, arg.AuthUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO
    auth_users (
        id,
        name,
        email,
        password_hash,
        is_email_verified
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, name, email, password_hash, is_email_verified, created_at, updated_at
`

type CreateAuthUserParams struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Email           string    `json:"email"`
	PasswordHash    string    `json:"password_hash"`
	IsEmailVerified bool      `json:"is_email_verified"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createAuthUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.IsEmailVerified,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO
    sessions (
        id,
        auth_user_id,
        token_hash,
        user_agent,
        ip_address,
        expires_at
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, auth_user_id, token_hash, user_agent, ip_address, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID         uuid.UUID          `json:"id"`
	AuthUserID uuid.UUID          `json:"auth_user_id"`
	TokenHash  string             `json:"token_hash"`
	UserAgent  *string            `json:"user_agent"`
	IpAddress  *string            `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AuthUserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO
    verification_codes (id, email, code_hash, type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO
UPDATE
SET
    email = EXCLUDED.email,
    code_hash = EXCLUDED.code_hash,
    type = EXCLUDED.type,
    created_at = now()
RETURNING
    id, update_id, email, code_hash, type, created_at, updated_at
`

type CreateVerificationCodeParams struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	CodeHash string    `json:"code_hash"`
	Type     string    `json:"type"`
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCode,
		arg.ID,
		arg.Email,
		arg.CodeHash,
		arg.Type,
	)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UpdateID,
		&i.Email,
		&i.CodeHash,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationCodeWithUpdateID = `-- name: CreateVerificationCodeWithUpdateID :one
INSERT INTO
    verification_codes (
        id,
        update_id,
        email,
        code_hash,
        type
    )
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO
UPDATE
SET
    update_id = EXCLUDED.update_id,
    email = EXCLUDED.email,
    code_hash = EXCLUDED.code_hash,
    type = EXCLUDED.type,
    created_at = now()
RETURNING
    id, update_id, email, code_hash, type, created_at, updated_at
`

type CreateVerificationCodeWithUpdateIDParams struct {
	ID       uuid.UUID   `json:"id"`
	UpdateID pgtype.UUID `json:"update_id"`
	Email    string      `json:"email"`
	CodeHash string      `json:"code_hash"`
	Type     string      `json:"type"`
}

func (q *Queries) CreateVerificationCodeWithUpdateID(ctx context.Context, arg CreateVerificationCodeWithUpdateIDParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCodeWithUpdateID,
		arg.ID,
		arg.UpdateID,
		arg.Email,
		arg.CodeHash,
		arg.Type,
	)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UpdateID,
		&i.Email,
		&i.CodeHash,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
DELETE FROM sessions WHERE auth_user_id = $1
`

func (q *Queries) DeleteAllUserSessions(ctx context.Context, authUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserSessions, authUserID)
	return err
}

const deleteAllVerificationCodesForEmail = `-- name: DeleteAllVerificationCodesForEmail :exec
DELETE FROM verification_codes WHERE email = $1 AND type = $2
`

type DeleteAllVerificationCodesForEmailParams struct {
	Email string `json:"email"`
	Type  string `json:"type"`
}

func (q *Queries) DeleteAllVerificationCodesForEmail(ctx context.Context, arg DeleteAllVerificationCodesForEmailParams) error {
	_, err := q.db.Exec(ctx, deleteAllVerificationCodesForEmail, arg.Email, arg.Type)
	return err
}

const deleteAuthUser = `-- name: DeleteAuthUser :exec
DELETE FROM auth_users WHERE id = $1
`

// Delete auth user (cascade will automatically delete sessions and verification_codes)
func (q *Queries) DeleteAuthUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthUser, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1 AND auth_user_id = $2
`

type DeleteSessionParams struct {
	ID         uuid.UUID `json:"id"`
	AuthUserID uuid.UUID `json:"auth_user_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.AuthUserID)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions WHERE token_hash = $1 AND auth_user_id = $2
`

type DeleteSessionByTokenParams struct {
	TokenHash  string    `json:"token_hash"`
	AuthUserID uuid.UUID `json:"auth_user_id"`
}

func (q *Queries) DeleteSessionByToken(ctx context.Context, arg DeleteSessionByTokenParams) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, arg.TokenHash, arg.AuthUserID)
	return err
}

const deleteVerificationCode = `-- name: DeleteVerificationCode :exec
DELETE FROM verification_codes WHERE id = $1
`

func (q *Queries) DeleteVerificationCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationCode, id)
	return err
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one
SELECT id, name, email, password_hash, is_email_verified, created_at, updated_at FROM auth_users WHERE email = $1
`

func (q *Queries) GetAuthUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, name, email, password_hash, is_email_verified, created_at, updated_at FROM auth_users WHERE id = $1
`

// Returns auth user by ID
func (q *Queries) GetAuthUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationCode = `-- name: GetVerificationCode :one
SELECT id, update_id, email, code_hash, type, created_at, updated_at FROM verification_codes WHERE id = $1 AND type = $2
`

type GetVerificationCodeParams struct {
	ID   uuid.UUID `json:"id"`
	Type string    `json:"type"`
}

// Get the verification code by User ID (PK) and Type
func (q *Queries) GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerificationCode, arg.ID, arg.Type)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UpdateID,
		&i.Email,
		&i.CodeHash,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAuthUserEmail = `-- name: UpdateAuthUserEmail :exec
UPDATE auth_users
SET
    email = $2,
    is_email_verified = $3
WHERE
    id = $1
`

type UpdateAuthUserEmailParams struct {
	ID              uuid.UUID `json:"id"`
	Email           string    `json:"email"`
	IsEmailVerified bool      `json:"is_email_verified"`
}

func (q *Queries) UpdateAuthUserEmail(ctx context.Context, arg UpdateAuthUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserEmail, arg.ID, arg.Email, arg.IsEmailVerified)
	return err
}

const updateAuthUserEmailVerified = `-- name: UpdateAuthUserEmailVerified :exec
UPDATE auth_users SET is_email_verified = $2 WHERE id = $1
`

type UpdateAuthUserEmailVerifiedParams struct {
	ID              uuid.UUID `json:"id"`
	IsEmailVerified bool      `json:"is_email_verified"`
}

func (q *Queries) UpdateAuthUserEmailVerified(ctx context.Context, arg UpdateAuthUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserEmailVerified, arg.ID, arg.IsEmailVerified)
	return err
}

const updateAuthUserPassword = `-- name: UpdateAuthUserPassword :exec
UPDATE auth_users SET password_hash = $2 WHERE id = $1
`

type UpdateAuthUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateAuthUserPassword(ctx context.Context, arg UpdateAuthUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserPassword, arg.ID, arg.PasswordHash)
	return err
}
