// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package auth_db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthUser = `-- name: CreateAuthUser :one

INSERT INTO
    auth_users (
        id,
        name,
        email,
        password_hash,
        is_email_verified
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, name, email, password_hash, is_email_verified, created_at, updated_at
`

type CreateAuthUserParams struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Email           string    `json:"email"`
	PasswordHash    string    `json:"password_hash"`
	IsEmailVerified bool      `json:"is_email_verified"`
}

// ======================================
// Auth Tables Queries for sqlc
// ======================================
// Inserts a new auth user and returns all columns
func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createAuthUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.IsEmailVerified,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO
    sessions (
        id,
        auth_user_id,
        token_hash,
        user_agent,
        ip_address,
        expires_at
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, auth_user_id, token_hash, user_agent, ip_address, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID         uuid.UUID          `json:"id"`
	AuthUserID uuid.UUID          `json:"auth_user_id"`
	TokenHash  string             `json:"token_hash"`
	UserAgent  *string            `json:"user_agent"`
	IpAddress  *string            `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// ======================================
// Sessions Table Queries
// ======================================
// Creates a new session and returns all columns
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AuthUserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationCode = `-- name: CreateVerificationCode :one

INSERT INTO
    verification_codes (
        id,
        auth_user_id,
        email,
        code_hash,
        type,
        expires_at
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, auth_user_id, email, code_hash, type, expires_at, created_at, updated_at
`

type CreateVerificationCodeParams struct {
	ID         uuid.UUID          `json:"id"`
	AuthUserID pgtype.UUID        `json:"auth_user_id"`
	Email      string             `json:"email"`
	CodeHash   string             `json:"code_hash"`
	Type       string             `json:"type"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// ======================================
// Verification Codes Table Queries
// ======================================
// Creates a new verification code and returns all columns
func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCode,
		arg.ID,
		arg.AuthUserID,
		arg.Email,
		arg.CodeHash,
		arg.Type,
		arg.ExpiresAt,
	)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Email,
		&i.CodeHash,
		&i.Type,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllSessionsForUser = `-- name: DeleteAllSessionsForUser :exec
DELETE FROM sessions WHERE auth_user_id = $1
`

// Deletes all sessions for a user (for logout from all devices)
func (q *Queries) DeleteAllSessionsForUser(ctx context.Context, authUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsForUser, authUserID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

// Cleanup query: deletes expired sessions
func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteExpiredVerificationCodes = `-- name: DeleteExpiredVerificationCodes :exec
DELETE FROM verification_codes WHERE expires_at < now()
`

// Cleanup query: deletes expired verification codes
func (q *Queries) DeleteExpiredVerificationCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredVerificationCodes)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

// Deletes a session by ID (for logout)
func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteVerificationCode = `-- name: DeleteVerificationCode :exec
DELETE FROM verification_codes WHERE id = $1
`

// Deletes a verification code by ID
func (q *Queries) DeleteVerificationCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationCode, id)
	return err
}

const deleteVerificationCodesByEmailAndType = `-- name: DeleteVerificationCodesByEmailAndType :exec
DELETE FROM verification_codes WHERE email = $1 AND type = $2
`

type DeleteVerificationCodesByEmailAndTypeParams struct {
	Email string `json:"email"`
	Type  string `json:"type"`
}

// Deletes all verification codes for email and type (cleanup after verification)
func (q *Queries) DeleteVerificationCodesByEmailAndType(ctx context.Context, arg DeleteVerificationCodesByEmailAndTypeParams) error {
	_, err := q.db.Exec(ctx, deleteVerificationCodesByEmailAndType, arg.Email, arg.Type)
	return err
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one
SELECT id, name, email, password_hash, is_email_verified, created_at, updated_at FROM auth_users WHERE email = $1
`

// Returns auth user by email (for login)
func (q *Queries) GetAuthUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, name, email, password_hash, is_email_verified, created_at, updated_at FROM auth_users WHERE id = $1
`

// Returns auth user by ID (same as user ID)
func (q *Queries) GetAuthUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, auth_user_id, token_hash, user_agent, ip_address, expires_at, created_at, updated_at FROM sessions WHERE token_hash = $1
`

// Returns session by token hash (for session validation)
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationCodeByEmailAndType = `-- name: GetVerificationCodeByEmailAndType :one
SELECT id, auth_user_id, email, code_hash, type, expires_at, created_at, updated_at
FROM verification_codes
WHERE
    email = $1
    AND type = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetVerificationCodeByEmailAndTypeParams struct {
	Email string `json:"email"`
	Type  string `json:"type"`
}

// Returns the latest verification code for email and type
func (q *Queries) GetVerificationCodeByEmailAndType(ctx context.Context, arg GetVerificationCodeByEmailAndTypeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerificationCodeByEmailAndType, arg.Email, arg.Type)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Email,
		&i.CodeHash,
		&i.Type,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAuthUserEmailVerified = `-- name: UpdateAuthUserEmailVerified :exec
UPDATE auth_users SET is_email_verified = $2 WHERE id = $1
`

type UpdateAuthUserEmailVerifiedParams struct {
	ID              uuid.UUID `json:"id"`
	IsEmailVerified bool      `json:"is_email_verified"`
}

// Marks user email as verified
func (q *Queries) UpdateAuthUserEmailVerified(ctx context.Context, arg UpdateAuthUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserEmailVerified, arg.ID, arg.IsEmailVerified)
	return err
}
