// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package personal

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AloneUsername struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Avatar struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	FileID      string             `json:"file_id"`
	AvatarType  string             `json:"avatar_type"`
	TokenID     *string            `json:"token_id"`
	TokenSecret *string            `json:"token_secret"`
	TokenExpiry pgtype.Timestamptz `json:"token_expiry"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Chat struct {
	ID             uuid.UUID `json:"id"`
	Participant1ID uuid.UUID `json:"participant_1_id"`
	Participant2ID uuid.UUID `json:"participant_2_id"`
	// Unread count for participant_1_id
	P1UnreadCount int32 `json:"p1_unread_count"`
	// Unread count for participant_2_id
	P2UnreadCount int32              `json:"p2_unread_count"`
	P1LastReadAt  pgtype.Timestamptz `json:"p1_last_read_at"`
	P2LastReadAt  pgtype.Timestamptz `json:"p2_last_read_at"`
	// Content of the last message (persisted for preview)
	LastMessageContent   *string            `json:"last_message_content"`
	LastMessageCreatedAt pgtype.Timestamptz `json:"last_message_created_at"`
	LastMessageType      *string            `json:"last_message_type"`
	LastMessageSenderID  pgtype.UUID        `json:"last_message_sender_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	// UUID of the message currently displayed as the preview
	LastMessageID pgtype.UUID `json:"last_message_id"`
}

type ContactRequest struct {
	ID              uuid.UUID          `json:"id"`
	RequesterUserID uuid.UUID          `json:"requester_user_id"`
	ReceiverUserID  uuid.UUID          `json:"receiver_user_id"`
	Status          interface{}        `json:"status"`
	Nickname        *string            `json:"nickname"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Message struct {
	ID                          uuid.UUID          `json:"id"`
	ChatID                      uuid.UUID          `json:"chat_id"`
	SenderID                    uuid.UUID          `json:"sender_id"`
	RecipientID                 uuid.UUID          `json:"recipient_id"`
	Content                     string             `json:"content"`
	MessageType                 string             `json:"message_type"`
	FileID                      *string            `json:"file_id"`
	FileName                    *string            `json:"file_name"`
	FileSize                    *int64             `json:"file_size"`
	FileMimeType                *string            `json:"file_mime_type"`
	FileTokenID                 *string            `json:"file_token_id"`
	FileTokenSecret             *string            `json:"file_token_secret"`
	FileTokenExpiry             pgtype.Timestamptz `json:"file_token_expiry"`
	ThumbnailFileID             *string            `json:"thumbnail_file_id"`
	ThumbnailTokenID            *string            `json:"thumbnail_token_id"`
	ThumbnailTokenSecret        *string            `json:"thumbnail_token_secret"`
	DeliveredToRecipient        bool               `json:"delivered_to_recipient"`
	SyncedToSenderPrimary       bool               `json:"synced_to_sender_primary"`
	DeliveryAttempts            int32              `json:"delivery_attempts"`
	ExpiresAt                   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	DeliveredToRecipientPrimary *bool              `json:"delivered_to_recipient_primary"`
}

type MessageDeliveryLog struct {
	ID            uuid.UUID          `json:"id"`
	MessageID     uuid.UUID          `json:"message_id"`
	AttemptNumber int32              `json:"attempt_number"`
	Status        string             `json:"status"`
	ErrorReason   *string            `json:"error_reason"`
	AttemptedAt   pgtype.Timestamptz `json:"attempted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MessageSyncAction struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	ActionType         string             `json:"action_type"`
	Payload            []byte             `json:"payload"`
	DeliveredToPrimary bool               `json:"delivered_to_primary"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Token struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	Sha256HexSessionID string             `json:"sha256_hex_session_id"`
	Token              string             `json:"token"`
	Type               string             `json:"type"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                                uuid.UUID          `json:"id"`
	Name                              string             `json:"name"`
	Bio                               *string            `json:"bio"`
	ProfileType                       string             `json:"profile_type"`
	IsAdminBlocked                    bool               `json:"is_admin_blocked"`
	AdminBlockReason                  *string            `json:"admin_block_reason"`
	HmacSha256HexUsername             string             `json:"hmac_sha256_hex_username"`
	B64CipherChacha20poly1305Username string             `json:"b64_cipher_chacha20poly1305_username"`
	CreatedAt                         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                         pgtype.Timestamptz `json:"updated_at"`
}

type UserBlock struct {
	ID            uuid.UUID          `json:"id"`
	BlockerUserID uuid.UUID          `json:"blocker_user_id"`
	BlockedUserID uuid.UUID          `json:"blocked_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserContact struct {
	OwnerUserID   uuid.UUID          `json:"owner_user_id"`
	ContactUserID uuid.UUID          `json:"contact_user_id"`
	Nickname      *string            `json:"nickname"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserGlobalRestriction struct {
	UserID          uuid.UUID          `json:"user_id"`
	RestrictAvatar  bool               `json:"restrict_avatar"`
	RestrictStatus  bool               `json:"restrict_status"`
	RestrictProfile bool               `json:"restrict_profile"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserGlobalRestrictionExemption struct {
	UserID           uuid.UUID          `json:"user_id"`
	ExemptedUserID   uuid.UUID          `json:"exempted_user_id"`
	ExceptionAvatar  bool               `json:"exception_avatar"`
	ExceptionStatus  bool               `json:"exception_status"`
	ExceptionProfile bool               `json:"exception_profile"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type UserRestriction struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RestrictedUserID uuid.UUID          `json:"restricted_user_id"`
	RestrictProfile  bool               `json:"restrict_profile"`
	RestrictAvatar   bool               `json:"restrict_avatar"`
	RestrictStatus   bool               `json:"restrict_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
