// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_chat.sql

package personal

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const canSendMessage = `-- name: CanSendMessage :one

SELECT
    CASE
        WHEN NOT EXISTS (
            SELECT 1
            FROM users
            WHERE
                id = $2::uuid
        ) THEN 'recipient_not_found'
        WHEN NOT EXISTS (
            SELECT 1
            FROM user_contacts
            WHERE
                owner_user_id = $1::uuid
                AND contact_user_id = $2::uuid
        ) THEN 'not_in_contacts'
        WHEN EXISTS (
            SELECT 1
            FROM users
            WHERE
                id = $2::uuid
                AND profile_type = 'private'
        ) THEN 'recipient_private'
        WHEN EXISTS (
            SELECT 1
            FROM user_blocks
            WHERE
                blocker_user_id = $2::uuid
                AND blocked_user_id = $1::uuid
        ) THEN 'blocked_by_recipient'
        WHEN EXISTS (
            SELECT 1
            FROM user_blocks
            WHERE
                blocker_user_id = $1::uuid
                AND blocked_user_id = $2::uuid
        ) THEN 'blocked_by_me'
        WHEN EXISTS (
            SELECT 1
            FROM users
            WHERE
                id IN ($1::uuid, $2::uuid)
                AND is_admin_blocked = TRUE
        ) THEN 'admin_blocked'
        ELSE 'allowed'
    END AS eligibility_status
`

type CanSendMessageParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
}

// ===========================================
// Messaging Eligibility Checks
// ===========================================
func (q *Queries) CanSendMessage(ctx context.Context, arg CanSendMessageParams) (string, error) {
	row := q.db.QueryRow(ctx, canSendMessage, arg.Column1, arg.Column2)
	var eligibility_status string
	err := row.Scan(&eligibility_status)
	return eligibility_status, err
}

const clearLastMessageForParticipant = `-- name: ClearLastMessageForParticipant :exec

UPDATE chats
SET
    p1_last_message_content = CASE
        WHEN participant_1_id = $1 THEN NULL
        ELSE p1_last_message_content
    END,
    p2_last_message_content = CASE
        WHEN participant_2_id = $1 THEN NULL
        ELSE p2_last_message_content
    END,
    p1_last_message_type = CASE
        WHEN participant_1_id = $1 THEN NULL
        ELSE p1_last_message_type
    END,
    p2_last_message_type = CASE
        WHEN participant_2_id = $1 THEN NULL
        ELSE p2_last_message_type
    END,
    updated_at = now()
WHERE
    id = $2
    AND last_message_id = $3
`

type ClearLastMessageForParticipantParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	ChatID    uuid.UUID   `json:"chat_id"`
	MessageID pgtype.UUID `json:"message_id"`
}

// ===========================================
// Per-Participant Preview Operations
// ===========================================
// Clears the last message preview for a specific participant only (used by Delete for Me).
// Only fires if the deleted message is the current preview message.
func (q *Queries) ClearLastMessageForParticipant(ctx context.Context, arg ClearLastMessageForParticipantParams) error {
	_, err := q.db.Exec(ctx, clearLastMessageForParticipant, arg.UserID, arg.ChatID, arg.MessageID)
	return err
}

const consumeSyncAction = `-- name: ConsumeSyncAction :exec
DELETE FROM message_sync_actions WHERE id = $1
`

func (q *Queries) ConsumeSyncAction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeSyncAction, id)
	return err
}

const createChat = `-- name: CreateChat :one

INSERT INTO
    chats (
        id,
        participant_1_id,
        participant_2_id
    )
VALUES (
        $1,
        LEAST($2::uuid, $3::uuid),
        GREATEST($2::uuid, $3::uuid)
    )
ON CONFLICT (
    participant_1_id,
    participant_2_id
) DO
UPDATE
SET
    updated_at = now()
RETURNING
    id, participant_1_id, participant_2_id, p1_unread_count, p2_unread_count, p1_last_read_at, p2_last_read_at, last_message_created_at, last_message_sender_id, created_at, updated_at, last_message_id, p1_last_message_content, p2_last_message_content, p1_last_message_type, p2_last_message_type
`

type CreateChatParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 uuid.UUID `json:"column_2"`
	Column3 uuid.UUID `json:"column_3"`
}

// ===========================================
// Chat Queries for sqlc
// ===========================================
func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.ID, arg.Column2, arg.Column3)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Participant1ID,
		&i.Participant2ID,
		&i.P1UnreadCount,
		&i.P2UnreadCount,
		&i.P1LastReadAt,
		&i.P2LastReadAt,
		&i.LastMessageCreatedAt,
		&i.LastMessageSenderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageID,
		&i.P1LastMessageContent,
		&i.P2LastMessageContent,
		&i.P1LastMessageType,
		&i.P2LastMessageType,
	)
	return i, err
}

const createDeliveryLog = `-- name: CreateDeliveryLog :exec

INSERT INTO
    message_delivery_log (
        id,
        message_id,
        attempt_number,
        status,
        error_reason
    )
VALUES ($1, $2, $3, $4, $5)
`

type CreateDeliveryLogParams struct {
	ID            uuid.UUID `json:"id"`
	MessageID     uuid.UUID `json:"message_id"`
	AttemptNumber int32     `json:"attempt_number"`
	Status        string    `json:"status"`
	ErrorReason   *string   `json:"error_reason"`
}

// ===========================================
// Message Delivery Log Operations
// ===========================================
func (q *Queries) CreateDeliveryLog(ctx context.Context, arg CreateDeliveryLogParams) error {
	_, err := q.db.Exec(ctx, createDeliveryLog,
		arg.ID,
		arg.MessageID,
		arg.AttemptNumber,
		arg.Status,
		arg.ErrorReason,
	)
	return err
}

const createMessage = `-- name: CreateMessage :one

INSERT INTO
    messages (
        id,
        chat_id,
        sender_id,
        recipient_id,
        content,
        message_type,
        expires_at,
        synced_to_sender_primary,
        delivered_to_recipient_primary
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
RETURNING
    id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, synced_to_sender_primary, delivery_attempts, expires_at, created_at, updated_at, delivered_to_recipient_primary
`

type CreateMessageParams struct {
	ID                          uuid.UUID          `json:"id"`
	ChatID                      uuid.UUID          `json:"chat_id"`
	SenderID                    uuid.UUID          `json:"sender_id"`
	RecipientID                 uuid.UUID          `json:"recipient_id"`
	Content                     string             `json:"content"`
	MessageType                 string             `json:"message_type"`
	ExpiresAt                   pgtype.Timestamptz `json:"expires_at"`
	SyncedToSenderPrimary       bool               `json:"synced_to_sender_primary"`
	DeliveredToRecipientPrimary *bool              `json:"delivered_to_recipient_primary"`
}

// ===========================================
// Message Operations
// ===========================================
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ChatID,
		arg.SenderID,
		arg.RecipientID,
		arg.Content,
		arg.MessageType,
		arg.ExpiresAt,
		arg.SyncedToSenderPrimary,
		arg.DeliveredToRecipientPrimary,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.RecipientID,
		&i.Content,
		&i.MessageType,
		&i.FileID,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.FileTokenID,
		&i.FileTokenSecret,
		&i.FileTokenExpiry,
		&i.ThumbnailFileID,
		&i.ThumbnailTokenID,
		&i.ThumbnailTokenSecret,
		&i.DeliveredToRecipient,
		&i.SyncedToSenderPrimary,
		&i.DeliveryAttempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredToRecipientPrimary,
	)
	return i, err
}

const createMessageWithFile = `-- name: CreateMessageWithFile :one

INSERT INTO
    messages (
        id,
        chat_id,
        sender_id,
        recipient_id,
        content,
        message_type,
        file_id,
        file_name,
        file_size,
        file_mime_type,
        file_token_id,
        file_token_secret,
        file_token_expiry,
        expires_at,
        synced_to_sender_primary,
        delivered_to_recipient_primary
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16
    )
RETURNING
    id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, synced_to_sender_primary, delivery_attempts, expires_at, created_at, updated_at, delivered_to_recipient_primary
`

type CreateMessageWithFileParams struct {
	ID                          uuid.UUID          `json:"id"`
	ChatID                      uuid.UUID          `json:"chat_id"`
	SenderID                    uuid.UUID          `json:"sender_id"`
	RecipientID                 uuid.UUID          `json:"recipient_id"`
	Content                     string             `json:"content"`
	MessageType                 string             `json:"message_type"`
	FileID                      *string            `json:"file_id"`
	FileName                    *string            `json:"file_name"`
	FileSize                    *int64             `json:"file_size"`
	FileMimeType                *string            `json:"file_mime_type"`
	FileTokenID                 *string            `json:"file_token_id"`
	FileTokenSecret             *string            `json:"file_token_secret"`
	FileTokenExpiry             pgtype.Timestamptz `json:"file_token_expiry"`
	ExpiresAt                   pgtype.Timestamptz `json:"expires_at"`
	SyncedToSenderPrimary       bool               `json:"synced_to_sender_primary"`
	DeliveredToRecipientPrimary *bool              `json:"delivered_to_recipient_primary"`
}

// ===========================================
// File Messaging Operations
// ===========================================
func (q *Queries) CreateMessageWithFile(ctx context.Context, arg CreateMessageWithFileParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessageWithFile,
		arg.ID,
		arg.ChatID,
		arg.SenderID,
		arg.RecipientID,
		arg.Content,
		arg.MessageType,
		arg.FileID,
		arg.FileName,
		arg.FileSize,
		arg.FileMimeType,
		arg.FileTokenID,
		arg.FileTokenSecret,
		arg.FileTokenExpiry,
		arg.ExpiresAt,
		arg.SyncedToSenderPrimary,
		arg.DeliveredToRecipientPrimary,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.RecipientID,
		&i.Content,
		&i.MessageType,
		&i.FileID,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.FileTokenID,
		&i.FileTokenSecret,
		&i.FileTokenExpiry,
		&i.ThumbnailFileID,
		&i.ThumbnailTokenID,
		&i.ThumbnailTokenSecret,
		&i.DeliveredToRecipient,
		&i.SyncedToSenderPrimary,
		&i.DeliveryAttempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredToRecipientPrimary,
	)
	return i, err
}

const createSyncAction = `-- name: CreateSyncAction :one

INSERT INTO
    message_sync_actions (
        id,
        user_id,
        action_type,
        payload,
        created_at
    )
VALUES ($1, $2, $3, $4, now())
RETURNING
    id, user_id, action_type, payload, delivered_to_primary, created_at, updated_at
`

type CreateSyncActionParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	ActionType string    `json:"action_type"`
	Payload    []byte    `json:"payload"`
}

// ===========================================
// Sync Action Operations
// ===========================================
func (q *Queries) CreateSyncAction(ctx context.Context, arg CreateSyncActionParams) (MessageSyncAction, error) {
	row := q.db.QueryRow(ctx, createSyncAction,
		arg.ID,
		arg.UserID,
		arg.ActionType,
		arg.Payload,
	)
	var i MessageSyncAction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActionType,
		&i.Payload,
		&i.DeliveredToPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeliveredMessages = `-- name: DeleteDeliveredMessages :exec
DELETE FROM messages
WHERE
    delivered_to_recipient_primary = TRUE
    AND synced_to_sender_primary = TRUE
`

func (q *Queries) DeleteDeliveredMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteDeliveredMessages)
	return err
}

const deleteExpiredMessages = `-- name: DeleteExpiredMessages :exec
DELETE FROM messages WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredMessages)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const deleteOldSyncActions = `-- name: DeleteOldSyncActions :exec
DELETE FROM message_sync_actions
WHERE
    created_at < now() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldSyncActions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldSyncActions)
	return err
}

const deletePendingMessagesBetweenUsers = `-- name: DeletePendingMessagesBetweenUsers :exec
DELETE FROM messages
WHERE (
        sender_id = $1
        AND recipient_id = $2
    )
    OR (
        sender_id = $2
        AND recipient_id = $1
    )
`

type DeletePendingMessagesBetweenUsersParams struct {
	SenderID    uuid.UUID `json:"sender_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) DeletePendingMessagesBetweenUsers(ctx context.Context, arg DeletePendingMessagesBetweenUsersParams) error {
	_, err := q.db.Exec(ctx, deletePendingMessagesBetweenUsers, arg.SenderID, arg.RecipientID)
	return err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, participant_1_id, participant_2_id, p1_unread_count, p2_unread_count, p1_last_read_at, p2_last_read_at, last_message_created_at, last_message_sender_id, created_at, updated_at, last_message_id, p1_last_message_content, p2_last_message_content, p1_last_message_type, p2_last_message_type FROM chats WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Participant1ID,
		&i.Participant2ID,
		&i.P1UnreadCount,
		&i.P2UnreadCount,
		&i.P1LastReadAt,
		&i.P2LastReadAt,
		&i.LastMessageCreatedAt,
		&i.LastMessageSenderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageID,
		&i.P1LastMessageContent,
		&i.P2LastMessageContent,
		&i.P1LastMessageType,
		&i.P2LastMessageType,
	)
	return i, err
}

const getChatByParticipants = `-- name: GetChatByParticipants :one
SELECT id, participant_1_id, participant_2_id, p1_unread_count, p2_unread_count, p1_last_read_at, p2_last_read_at, last_message_created_at, last_message_sender_id, created_at, updated_at, last_message_id, p1_last_message_content, p2_last_message_content, p1_last_message_type, p2_last_message_type
FROM chats
WHERE
    participant_1_id = LEAST($1::uuid, $2::uuid)
    AND participant_2_id = GREATEST($1::uuid, $2::uuid)
LIMIT 1
`

type GetChatByParticipantsParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) GetChatByParticipants(ctx context.Context, arg GetChatByParticipantsParams) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByParticipants, arg.Column1, arg.Column2)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Participant1ID,
		&i.Participant2ID,
		&i.P1UnreadCount,
		&i.P2UnreadCount,
		&i.P1LastReadAt,
		&i.P2LastReadAt,
		&i.LastMessageCreatedAt,
		&i.LastMessageSenderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageID,
		&i.P1LastMessageContent,
		&i.P2LastMessageContent,
		&i.P1LastMessageType,
		&i.P2LastMessageType,
	)
	return i, err
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, synced_to_sender_primary, delivery_attempts, expires_at, created_at, updated_at, delivered_to_recipient_primary
FROM messages
WHERE
    chat_id = $1
    AND expires_at > now()
ORDER BY created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetChatMessagesParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getChatMessages, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.SyncedToSenderPrimary,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveredToRecipientPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveredMessagesByChat = `-- name: GetDeliveredMessagesByChat :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, synced_to_sender_primary, delivery_attempts, expires_at, created_at, updated_at, delivered_to_recipient_primary
FROM messages
WHERE
    chat_id = $1
    AND (
        (
            recipient_id = $2
            AND delivered_to_recipient_primary = TRUE
            AND synced_to_sender_primary = TRUE
        )
        OR (
            sender_id = $2
            AND delivered_to_recipient_primary = TRUE
            AND synced_to_sender_primary = TRUE
        )
    )
`

type GetDeliveredMessagesByChatParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetDeliveredMessagesByChat(ctx context.Context, arg GetDeliveredMessagesByChatParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getDeliveredMessagesByChat, arg.ChatID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.SyncedToSenderPrimary,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveredToRecipientPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveryLogsByMessage = `-- name: GetDeliveryLogsByMessage :many
SELECT id, message_id, attempt_number, status, error_reason, attempted_at, created_at, updated_at
FROM message_delivery_log
WHERE
    message_id = $1
ORDER BY attempted_at DESC
`

func (q *Queries) GetDeliveryLogsByMessage(ctx context.Context, messageID uuid.UUID) ([]MessageDeliveryLog, error) {
	rows, err := q.db.Query(ctx, getDeliveryLogsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageDeliveryLog
	for rows.Next() {
		var i MessageDeliveryLog
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.AttemptNumber,
			&i.Status,
			&i.ErrorReason,
			&i.AttemptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredMessagesWithFiles = `-- name: GetExpiredMessagesWithFiles :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, synced_to_sender_primary, delivery_attempts, expires_at, created_at, updated_at, delivered_to_recipient_primary
FROM messages
WHERE
    expires_at < now()
    AND file_id IS NOT NULL
ORDER BY expires_at ASC
LIMIT $1
`

func (q *Queries) GetExpiredMessagesWithFiles(ctx context.Context, limit int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, getExpiredMessagesWithFiles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.SyncedToSenderPrimary,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveredToRecipientPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, synced_to_sender_primary, delivery_attempts, expires_at, created_at, updated_at, delivered_to_recipient_primary FROM messages WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.RecipientID,
		&i.Content,
		&i.MessageType,
		&i.FileID,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.FileTokenID,
		&i.FileTokenSecret,
		&i.FileTokenExpiry,
		&i.ThumbnailFileID,
		&i.ThumbnailTokenID,
		&i.ThumbnailTokenSecret,
		&i.DeliveredToRecipient,
		&i.SyncedToSenderPrimary,
		&i.DeliveryAttempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveredToRecipientPrimary,
	)
	return i, err
}

const getMessagesWithExpiredFileTokens = `-- name: GetMessagesWithExpiredFileTokens :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, synced_to_sender_primary, delivery_attempts, expires_at, created_at, updated_at, delivered_to_recipient_primary
FROM messages
WHERE
    file_id IS NOT NULL
    AND file_token_expiry IS NOT NULL
    AND file_token_expiry < now()
    AND expires_at > now()
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetMessagesWithExpiredFileTokens(ctx context.Context, limit int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesWithExpiredFileTokens, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.SyncedToSenderPrimary,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveredToRecipientPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingMessagesForRecipient = `-- name: GetPendingMessagesForRecipient :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, synced_to_sender_primary, delivery_attempts, expires_at, created_at, updated_at, delivered_to_recipient_primary
FROM messages
WHERE
    recipient_id = $1
    AND delivered_to_recipient = FALSE
    AND expires_at > now()
ORDER BY created_at ASC
LIMIT $2
`

type GetPendingMessagesForRecipientParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) GetPendingMessagesForRecipient(ctx context.Context, arg GetPendingMessagesForRecipientParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getPendingMessagesForRecipient, arg.RecipientID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.SyncedToSenderPrimary,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveredToRecipientPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingSenderSyncMessages = `-- name: GetPendingSenderSyncMessages :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, synced_to_sender_primary, delivery_attempts, expires_at, created_at, updated_at, delivered_to_recipient_primary
FROM messages
WHERE
    sender_id = $1
    AND synced_to_sender_primary = FALSE
    AND expires_at > now()
ORDER BY created_at ASC
LIMIT $2
`

type GetPendingSenderSyncMessagesParams struct {
	SenderID uuid.UUID `json:"sender_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) GetPendingSenderSyncMessages(ctx context.Context, arg GetPendingSenderSyncMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getPendingSenderSyncMessages, arg.SenderID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.SyncedToSenderPrimary,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveredToRecipientPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingSyncActions = `-- name: GetPendingSyncActions :many
SELECT id, user_id, action_type, payload, delivered_to_primary, created_at, updated_at
FROM message_sync_actions
WHERE
    user_id = $1
    AND delivered_to_primary = FALSE
ORDER BY created_at ASC
LIMIT $2
`

type GetPendingSyncActionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetPendingSyncActions(ctx context.Context, arg GetPendingSyncActionsParams) ([]MessageSyncAction, error) {
	rows, err := q.db.Query(ctx, getPendingSyncActions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageSyncAction
	for rows.Next() {
		var i MessageSyncAction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActionType,
			&i.Payload,
			&i.DeliveredToPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChats = `-- name: GetUserChats :many
SELECT
    c.id, c.participant_1_id, c.participant_2_id, c.p1_unread_count, c.p2_unread_count, c.p1_last_read_at, c.p2_last_read_at, c.last_message_created_at, c.last_message_sender_id, c.created_at, c.updated_at, c.last_message_id, c.p1_last_message_content, c.p2_last_message_content, c.p1_last_message_type, c.p2_last_message_type,
    u.name AS other_user_name,
    u.b64_cipher_chacha20poly1305_username AS other_user_username,
    u.id AS other_user_id,

CASE
    WHEN c.participant_1_id = $1 THEN c.p1_unread_count
    ELSE c.p2_unread_count
END::INT AS unread_count,

CASE
    WHEN c.participant_1_id = $1 THEN c.p1_last_message_content
    ELSE c.p2_last_message_content
END AS last_message_content,
CASE
    WHEN c.participant_1_id = $1 THEN c.p1_last_message_type
    ELSE c.p2_last_message_type
END AS last_message_type,

CASE
    WHEN c.last_message_created_at IS NULL THEN NULL
    WHEN c.last_message_created_at <= (
        CASE
            WHEN c.participant_1_id = $1 THEN c.p2_last_read_at
            ELSE c.p1_last_read_at
        END
    ) THEN 'read'
    ELSE 'sent'
END::text AS last_message_status,

a.file_id AS avatar_file_id,
a.token_id AS avatar_token_id,
a.token_secret AS avatar_token_secret,
a.token_expiry AS avatar_token_expiry,

COALESCE(ugr.restrict_profile, FALSE) AS global_restrict_profile,
COALESCE(ugr.restrict_avatar, FALSE) AS global_restrict_avatar,
COALESCE(ugre.exception_profile, FALSE) AS exception_global_profile,
COALESCE(ugre.exception_avatar, FALSE) AS exception_global_avatar,
COALESCE(ur.restrict_profile, FALSE) AS user_restrict_profile,
COALESCE(ur.restrict_avatar, FALSE) AS user_restrict_avatar
FROM
    chats c
    JOIN users u ON u.id = CASE
        WHEN c.participant_1_id = $1 THEN c.participant_2_id
        ELSE c.participant_1_id
    END
    LEFT JOIN avatars a ON u.id = a.user_id
    AND a.avatar_type = 'profile'
    LEFT JOIN user_global_restrictions ugr ON u.id = ugr.user_id
    LEFT JOIN user_global_restriction_exemptions ugre ON u.id = ugre.user_id
    AND ugre.exempted_user_id = $1
    LEFT JOIN user_restrictions ur ON u.id = ur.user_id
    AND ur.restricted_user_id = $1
WHERE
    c.participant_1_id = $1
    OR c.participant_2_id = $1
ORDER BY c.updated_at DESC
`

type GetUserChatsRow struct {
	ID                     uuid.UUID          `json:"id"`
	Participant1ID         uuid.UUID          `json:"participant_1_id"`
	Participant2ID         uuid.UUID          `json:"participant_2_id"`
	P1UnreadCount          int32              `json:"p1_unread_count"`
	P2UnreadCount          int32              `json:"p2_unread_count"`
	P1LastReadAt           pgtype.Timestamptz `json:"p1_last_read_at"`
	P2LastReadAt           pgtype.Timestamptz `json:"p2_last_read_at"`
	LastMessageCreatedAt   pgtype.Timestamptz `json:"last_message_created_at"`
	LastMessageSenderID    pgtype.UUID        `json:"last_message_sender_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	LastMessageID          pgtype.UUID        `json:"last_message_id"`
	P1LastMessageContent   *string            `json:"p1_last_message_content"`
	P2LastMessageContent   *string            `json:"p2_last_message_content"`
	P1LastMessageType      *string            `json:"p1_last_message_type"`
	P2LastMessageType      *string            `json:"p2_last_message_type"`
	OtherUserName          string             `json:"other_user_name"`
	OtherUserUsername      string             `json:"other_user_username"`
	OtherUserID            uuid.UUID          `json:"other_user_id"`
	UnreadCount            int32              `json:"unread_count"`
	LastMessageContent     interface{}        `json:"last_message_content"`
	LastMessageType        interface{}        `json:"last_message_type"`
	LastMessageStatus      string             `json:"last_message_status"`
	AvatarFileID           *string            `json:"avatar_file_id"`
	AvatarTokenID          *string            `json:"avatar_token_id"`
	AvatarTokenSecret      *string            `json:"avatar_token_secret"`
	AvatarTokenExpiry      pgtype.Timestamptz `json:"avatar_token_expiry"`
	GlobalRestrictProfile  bool               `json:"global_restrict_profile"`
	GlobalRestrictAvatar   bool               `json:"global_restrict_avatar"`
	ExceptionGlobalProfile bool               `json:"exception_global_profile"`
	ExceptionGlobalAvatar  bool               `json:"exception_global_avatar"`
	UserRestrictProfile    bool               `json:"user_restrict_profile"`
	UserRestrictAvatar     bool               `json:"user_restrict_avatar"`
}

// Unread Count (From Metadata)
// Per-Participant Last Message Preview
// Last Message Status (Calculated)
// Raw avatar data
// Privacy flags
func (q *Queries) GetUserChats(ctx context.Context, participant1ID uuid.UUID) ([]GetUserChatsRow, error) {
	rows, err := q.db.Query(ctx, getUserChats, participant1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserChatsRow
	for rows.Next() {
		var i GetUserChatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Participant1ID,
			&i.Participant2ID,
			&i.P1UnreadCount,
			&i.P2UnreadCount,
			&i.P1LastReadAt,
			&i.P2LastReadAt,
			&i.LastMessageCreatedAt,
			&i.LastMessageSenderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessageID,
			&i.P1LastMessageContent,
			&i.P2LastMessageContent,
			&i.P1LastMessageType,
			&i.P2LastMessageType,
			&i.OtherUserName,
			&i.OtherUserUsername,
			&i.OtherUserID,
			&i.UnreadCount,
			&i.LastMessageContent,
			&i.LastMessageType,
			&i.LastMessageStatus,
			&i.AvatarFileID,
			&i.AvatarTokenID,
			&i.AvatarTokenSecret,
			&i.AvatarTokenExpiry,
			&i.GlobalRestrictProfile,
			&i.GlobalRestrictAvatar,
			&i.ExceptionGlobalProfile,
			&i.ExceptionGlobalAvatar,
			&i.UserRestrictProfile,
			&i.UserRestrictAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementDeliveryAttempts = `-- name: IncrementDeliveryAttempts :exec
UPDATE messages
SET
    delivery_attempts = delivery_attempts + 1,
    updated_at = now()
WHERE
    id = $1
`

func (q *Queries) IncrementDeliveryAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementDeliveryAttempts, id)
	return err
}

const isChatParticipant = `-- name: IsChatParticipant :one
SELECT EXISTS (
        SELECT 1
        FROM chats
        WHERE
            id = $1::uuid
            AND (
                $2::uuid = participant_1_id
                OR $2::uuid = participant_2_id
            )
    )
`

type IsChatParticipantParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) IsChatParticipant(ctx context.Context, arg IsChatParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatParticipant, arg.Column1, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markChatMessagesAsRead = `-- name: MarkChatMessagesAsRead :exec
UPDATE messages
SET
    delivered_to_recipient = TRUE,
    updated_at = now()
WHERE
    chat_id = $1
    AND recipient_id = $2
    AND delivered_to_recipient = FALSE
`

type MarkChatMessagesAsReadParams struct {
	ChatID      uuid.UUID `json:"chat_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkChatMessagesAsRead(ctx context.Context, arg MarkChatMessagesAsReadParams) error {
	_, err := q.db.Exec(ctx, markChatMessagesAsRead, arg.ChatID, arg.RecipientID)
	return err
}

const markChatMessagesAsReadPrimary = `-- name: MarkChatMessagesAsReadPrimary :exec
UPDATE messages
SET
    delivered_to_recipient_primary = TRUE,
    delivered_to_recipient = TRUE, -- Implicitly true
    updated_at = now()
WHERE
    chat_id = $1
    AND recipient_id = $2
    AND delivered_to_recipient_primary = FALSE
`

type MarkChatMessagesAsReadPrimaryParams struct {
	ChatID      uuid.UUID `json:"chat_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkChatMessagesAsReadPrimary(ctx context.Context, arg MarkChatMessagesAsReadPrimaryParams) error {
	_, err := q.db.Exec(ctx, markChatMessagesAsReadPrimary, arg.ChatID, arg.RecipientID)
	return err
}

const markMessageDeliveredToRecipient = `-- name: MarkMessageDeliveredToRecipient :exec
UPDATE messages
SET
    delivered_to_recipient = TRUE,
    updated_at = now()
WHERE
    chat_id = (
        SELECT m2.chat_id
        FROM messages m2
        WHERE
            m2.id = $1
    )
    AND recipient_id = (
        SELECT m3.recipient_id
        FROM messages m3
        WHERE
            m3.id = $1
    )
    AND created_at <= (
        SELECT m4.created_at
        FROM messages m4
        WHERE
            m4.id = $1
    )
    AND delivered_to_recipient = FALSE
`

func (q *Queries) MarkMessageDeliveredToRecipient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageDeliveredToRecipient, id)
	return err
}

const markMessageDeliveredToRecipientPrimary = `-- name: MarkMessageDeliveredToRecipientPrimary :exec
UPDATE messages
SET
    delivered_to_recipient_primary = TRUE,
    delivered_to_recipient = TRUE, -- Implicitly true
    updated_at = now()
WHERE
    chat_id = (
        SELECT m2.chat_id
        FROM messages m2
        WHERE
            m2.id = $1
    )
    AND recipient_id = (
        SELECT m3.recipient_id
        FROM messages m3
        WHERE
            m3.id = $1
    )
    AND created_at <= (
        SELECT m4.created_at
        FROM messages m4
        WHERE
            m4.id = $1
    )
    AND delivered_to_recipient_primary = FALSE
`

func (q *Queries) MarkMessageDeliveredToRecipientPrimary(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageDeliveredToRecipientPrimary, id)
	return err
}

const markMessageSyncedToSenderPrimary = `-- name: MarkMessageSyncedToSenderPrimary :exec
UPDATE messages
SET
    synced_to_sender_primary = TRUE,
    updated_at = now()
WHERE
    chat_id = (
        SELECT m2.chat_id
        FROM messages m2
        WHERE
            m2.id = $1
    )
    AND sender_id = (
        SELECT m3.sender_id
        FROM messages m3
        WHERE
            m3.id = $1
    )
    AND created_at <= (
        SELECT m4.created_at
        FROM messages m4
        WHERE
            m4.id = $1
    )
    AND synced_to_sender_primary = FALSE
`

func (q *Queries) MarkMessageSyncedToSenderPrimary(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageSyncedToSenderPrimary, id)
	return err
}

const resetChatReadStatus = `-- name: ResetChatReadStatus :exec
UPDATE chats
SET
    p1_unread_count = CASE
        WHEN participant_1_id = $2 THEN 0
        ELSE p1_unread_count
    END,
    p1_last_read_at = CASE
        WHEN participant_1_id = $2 THEN now()
        ELSE p1_last_read_at
    END,
    p2_unread_count = CASE
        WHEN participant_2_id = $2 THEN 0
        ELSE p2_unread_count
    END,
    p2_last_read_at = CASE
        WHEN participant_2_id = $2 THEN now()
        ELSE p2_last_read_at
    END,
    updated_at = now()
WHERE
    id = $1
    AND (
        participant_1_id = $2
        OR participant_2_id = $2
    )
`

type ResetChatReadStatusParams struct {
	ID             uuid.UUID `json:"id"`
	Participant1ID uuid.UUID `json:"participant_1_id"`
}

func (q *Queries) ResetChatReadStatus(ctx context.Context, arg ResetChatReadStatusParams) error {
	_, err := q.db.Exec(ctx, resetChatReadStatus, arg.ID, arg.Participant1ID)
	return err
}

const updateChatStatus = `-- name: UpdateChatStatus :exec

UPDATE chats
SET
    p1_last_message_content = $2,
    p2_last_message_content = $2,
    last_message_created_at = $3,
    p1_last_message_type = $4,
    p2_last_message_type = $4,
    last_message_sender_id = $5,
    last_message_id = $6,
    p1_unread_count = CASE
        WHEN participant_1_id != $5 THEN p1_unread_count + 1
        ELSE p1_unread_count
    END,
    p2_unread_count = CASE
        WHEN participant_2_id != $5 THEN p2_unread_count + 1
        ELSE p2_unread_count
    END,
    updated_at = now()
WHERE
    id = $1
`

type UpdateChatStatusParams struct {
	ID                   uuid.UUID          `json:"id"`
	P1LastMessageContent *string            `json:"p1_last_message_content"`
	LastMessageCreatedAt pgtype.Timestamptz `json:"last_message_created_at"`
	P1LastMessageType    *string            `json:"p1_last_message_type"`
	LastMessageSenderID  pgtype.UUID        `json:"last_message_sender_id"`
	LastMessageID        pgtype.UUID        `json:"last_message_id"`
}

// ===========================================
// Chat Status Update Operations (Phase 2b)
// ===========================================
func (q *Queries) UpdateChatStatus(ctx context.Context, arg UpdateChatStatusParams) error {
	_, err := q.db.Exec(ctx, updateChatStatus,
		arg.ID,
		arg.P1LastMessageContent,
		arg.LastMessageCreatedAt,
		arg.P1LastMessageType,
		arg.LastMessageSenderID,
		arg.LastMessageID,
	)
	return err
}

const updateChatUnsendDecrement = `-- name: UpdateChatUnsendDecrement :exec
UPDATE chats
SET
    p1_unread_count = CASE
        WHEN participant_1_id = $1 THEN GREATEST(
            0,
            p1_unread_count - $2::int
        )
        ELSE p1_unread_count
    END,
    p2_unread_count = CASE
        WHEN participant_2_id = $1 THEN GREATEST(
            0,
            p2_unread_count - $2::int
        )
        ELSE p2_unread_count
    END,
    updated_at = now()
WHERE
    id = $3
`

type UpdateChatUnsendDecrementParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	Amount      int32     `json:"amount"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateChatUnsendDecrement(ctx context.Context, arg UpdateChatUnsendDecrementParams) error {
	_, err := q.db.Exec(ctx, updateChatUnsendDecrement, arg.RecipientID, arg.Amount, arg.ID)
	return err
}

const updateChatUnsendPreview = `-- name: UpdateChatUnsendPreview :exec
UPDATE chats
SET
    p1_last_message_content = 'Message unsent',
    p2_last_message_content = 'Message unsent',
    p1_last_message_type = 'unsent',
    p2_last_message_type = 'unsent',
    updated_at = now()
WHERE
    id = $1
    AND last_message_id = $2
`

type UpdateChatUnsendPreviewParams struct {
	ID            uuid.UUID   `json:"id"`
	LastMessageID pgtype.UUID `json:"last_message_id"`
}

func (q *Queries) UpdateChatUnsendPreview(ctx context.Context, arg UpdateChatUnsendPreviewParams) error {
	_, err := q.db.Exec(ctx, updateChatUnsendPreview, arg.ID, arg.LastMessageID)
	return err
}

const updateMessageFileToken = `-- name: UpdateMessageFileToken :exec
UPDATE messages
SET
    file_token_id = $2,
    file_token_secret = $3,
    file_token_expiry = $4,
    updated_at = now()
WHERE
    id = $1
`

type UpdateMessageFileTokenParams struct {
	ID              uuid.UUID          `json:"id"`
	FileTokenID     *string            `json:"file_token_id"`
	FileTokenSecret *string            `json:"file_token_secret"`
	FileTokenExpiry pgtype.Timestamptz `json:"file_token_expiry"`
}

func (q *Queries) UpdateMessageFileToken(ctx context.Context, arg UpdateMessageFileTokenParams) error {
	_, err := q.db.Exec(ctx, updateMessageFileToken,
		arg.ID,
		arg.FileTokenID,
		arg.FileTokenSecret,
		arg.FileTokenExpiry,
	)
	return err
}

const updateMessageToUnsent = `-- name: UpdateMessageToUnsent :exec
UPDATE messages
SET
    content = 'Message unsent',
    message_type = 'unsent',
    file_id = NULL,
    file_name = NULL,
    file_size = NULL,
    file_mime_type = NULL,
    file_token_id = NULL,
    file_token_secret = NULL,
    file_token_expiry = NULL,
    updated_at = now()
WHERE
    id = $1
`

func (q *Queries) UpdateMessageToUnsent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateMessageToUnsent, id)
	return err
}
