// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: e2ee.sql

package core_auth_store

import (
	"context"

	"github.com/google/uuid"
)

const countActiveKeyedSessionsForUser = `-- name: CountActiveKeyedSessionsForUser :one
SELECT COUNT(*)
FROM sessions
WHERE auth_user_id = $1
  AND e2ee_public_key IS NOT NULL
  AND expires_at > now()
`

// Count active sessions that have a key for a user
func (q *Queries) CountActiveKeyedSessionsForUser(ctx context.Context, authUserID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveKeyedSessionsForUser, authUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveSessionKeysForUser = `-- name: GetActiveSessionKeysForUser :many
SELECT id, e2ee_public_key
FROM sessions
WHERE auth_user_id = $1
  AND e2ee_public_key IS NOT NULL
  AND expires_at > now()
`

type GetActiveSessionKeysForUserRow struct {
	ID            uuid.UUID `json:"id"`
	E2eePublicKey *string   `json:"e2ee_public_key"`
}

// Fetch all active (unexpired, non-null key) public keys for a user
func (q *Queries) GetActiveSessionKeysForUser(ctx context.Context, authUserID uuid.UUID) ([]GetActiveSessionKeysForUserRow, error) {
	rows, err := q.db.Query(ctx, getActiveSessionKeysForUser, authUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveSessionKeysForUserRow
	for rows.Next() {
		var i GetActiveSessionKeysForUserRow
		if err := rows.Scan(&i.ID, &i.E2eePublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveSessionKeysForUserExcluding = `-- name: GetActiveSessionKeysForUserExcluding :many
SELECT id, e2ee_public_key
FROM sessions
WHERE auth_user_id = $1
  AND e2ee_public_key IS NOT NULL
  AND expires_at > now()
  AND id != $2
`

type GetActiveSessionKeysForUserExcludingParams struct {
	AuthUserID uuid.UUID `json:"auth_user_id"`
	ID         uuid.UUID `json:"id"`
}

type GetActiveSessionKeysForUserExcludingRow struct {
	ID            uuid.UUID `json:"id"`
	E2eePublicKey *string   `json:"e2ee_public_key"`
}

// Fetch all active (unexpired, non-null key) public keys for a user, excluding one session
func (q *Queries) GetActiveSessionKeysForUserExcluding(ctx context.Context, arg GetActiveSessionKeysForUserExcludingParams) ([]GetActiveSessionKeysForUserExcludingRow, error) {
	rows, err := q.db.Query(ctx, getActiveSessionKeysForUserExcluding, arg.AuthUserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveSessionKeysForUserExcludingRow
	for rows.Next() {
		var i GetActiveSessionKeysForUserExcludingRow
		if err := rows.Scan(&i.ID, &i.E2eePublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSessionE2EEPublicKey = `-- name: SaveSessionE2EEPublicKey :one

UPDATE sessions
SET e2ee_public_key = $1, updated_at = now()
WHERE id = $2 AND auth_user_id = $3 AND expires_at > now()
RETURNING id
`

type SaveSessionE2EEPublicKeyParams struct {
	E2eePublicKey *string   `json:"e2ee_public_key"`
	ID            uuid.UUID `json:"id"`
	AuthUserID    uuid.UUID `json:"auth_user_id"`
}

// ======================================
// E2EE Session Key Queries
// ======================================
// Save or update the E2EE public key for a specific session (must be active)
func (q *Queries) SaveSessionE2EEPublicKey(ctx context.Context, arg SaveSessionE2EEPublicKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, saveSessionE2EEPublicKey, arg.E2eePublicKey, arg.ID, arg.AuthUserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
