// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys_revision.sql

package core_auth_store

import (
	"context"

	"github.com/google/uuid"
)

const getKeysRevision = `-- name: GetKeysRevision :one

SELECT keys_revision FROM auth_users WHERE id = $1 FOR UPDATE
`

// ======================================
// Keys Revision Queries
// ======================================
// Get the current keys_revision for a user (atomic read)
func (q *Queries) GetKeysRevision(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getKeysRevision, id)
	var keys_revision int32
	err := row.Scan(&keys_revision)
	return keys_revision, err
}

const getKeysRevisions = `-- name: GetKeysRevisions :many
SELECT id, keys_revision FROM auth_users WHERE id = ANY($1::uuid[])
`

type GetKeysRevisionsRow struct {
	ID           uuid.UUID `json:"id"`
	KeysRevision int32     `json:"keys_revision"`
}

// Get keys_revision for multiple users in a single query
func (q *Queries) GetKeysRevisions(ctx context.Context, userIds []uuid.UUID) ([]GetKeysRevisionsRow, error) {
	rows, err := q.db.Query(ctx, getKeysRevisions, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetKeysRevisionsRow
	for rows.Next() {
		var i GetKeysRevisionsRow
		if err := rows.Scan(&i.ID, &i.KeysRevision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementKeysRevision = `-- name: IncrementKeysRevision :exec
UPDATE auth_users SET keys_revision = keys_revision + 1 WHERE id = $1
`

// Increment keys_revision by one (atomic)
func (q *Queries) IncrementKeysRevision(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementKeysRevision, id)
	return err
}

const resetKeysRevision = `-- name: ResetKeysRevision :exec
UPDATE auth_users SET keys_revision = 0 WHERE id = $1
`

// Reset keys_revision to zero
func (q *Queries) ResetKeysRevision(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetKeysRevision, id)
	return err
}
