// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package core_auth_store

import (
	"time"

	"github.com/google/uuid"
)

type AuthRateLimiter struct {
	AuthUserID          uuid.UUID  `json:"auth_user_id"`
	OtpHourlyCount      int32      `json:"otp_hourly_count"`
	Otp24hCount         int32      `json:"otp_24h_count"`
	LastOtpSendAt       *time.Time `json:"last_otp_send_at"`
	Otp24hWindowStartAt *time.Time `json:"otp_24h_window_start_at"`
	OtpVerifyErrors     int32      `json:"otp_verify_errors"`
	LastVerifyAttemptAt *time.Time `json:"last_verify_attempt_at"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

type AuthUser struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Email           string    `json:"email"`
	PasswordHash    string    `json:"password_hash"`
	IsEmailVerified bool      `json:"is_email_verified"`
	KeysRevision    int32     `json:"keys_revision"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type QrLoginRequest struct {
	ID         uuid.UUID  `json:"id"`
	AuthUserID *uuid.UUID `json:"auth_user_id"`
	Status     string     `json:"status"`
	ExpiresAt  time.Time  `json:"expires_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type Session struct {
	ID            uuid.UUID `json:"id"`
	AuthUserID    uuid.UUID `json:"auth_user_id"`
	TokenHash     string    `json:"token_hash"`
	DeviceToken   *string   `json:"device_token"`
	Platform      *string   `json:"platform"`
	DeviceName    *string   `json:"device_name"`
	IsCentral     bool      `json:"is_central"`
	E2eePublicKey *string   `json:"e2ee_public_key"`
	UserAgent     *string   `json:"user_agent"`
	IpAddress     *string   `json:"ip_address"`
	ExpiresAt     time.Time `json:"expires_at"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type VerificationCode struct {
	ID        uuid.UUID  `json:"id"`
	UpdateID  *uuid.UUID `json:"update_id"`
	Email     string     `json:"email"`
	CodeHash  string     `json:"code_hash"`
	Type      string     `json:"type"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}
