// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qr_login.sql

package core_auth_store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const approveQRLogin = `-- name: ApproveQRLogin :one
UPDATE qr_login_requests
SET status = 'APPROVED', auth_user_id = $2, updated_at = NOW()
WHERE id = $1 AND status = 'PENDING' AND expires_at > NOW()
RETURNING id
`

type ApproveQRLoginParams struct {
	ID         uuid.UUID  `json:"id"`
	AuthUserID *uuid.UUID `json:"auth_user_id"`
}

func (q *Queries) ApproveQRLogin(ctx context.Context, arg ApproveQRLoginParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, approveQRLogin, arg.ID, arg.AuthUserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const cleanupExpiredQRLoginRequests = `-- name: CleanupExpiredQRLoginRequests :exec
DELETE FROM qr_login_requests
WHERE expires_at < NOW()
`

func (q *Queries) CleanupExpiredQRLoginRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredQRLoginRequests)
	return err
}

const createQRLoginRequest = `-- name: CreateQRLoginRequest :one
INSERT INTO qr_login_requests (
    id, status, expires_at, created_at, updated_at
) VALUES (
    $1, 'PENDING', $2, NOW(), NOW()
) RETURNING id
`

type CreateQRLoginRequestParams struct {
	ID        uuid.UUID `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateQRLoginRequest(ctx context.Context, arg CreateQRLoginRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createQRLoginRequest, arg.ID, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const exchangeQRLogin = `-- name: ExchangeQRLogin :one
UPDATE qr_login_requests
SET status = 'EXCHANGED', updated_at = NOW()
WHERE id = $1 AND status = 'APPROVED' AND expires_at > NOW()
RETURNING auth_user_id
`

func (q *Queries) ExchangeQRLogin(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, exchangeQRLogin, id)
	var auth_user_id *uuid.UUID
	err := row.Scan(&auth_user_id)
	return auth_user_id, err
}

const getQRLoginRequest = `-- name: GetQRLoginRequest :one
SELECT id, auth_user_id, status, expires_at
FROM qr_login_requests
WHERE id = $1 AND status = 'PENDING' AND expires_at > NOW()
`

type GetQRLoginRequestRow struct {
	ID         uuid.UUID  `json:"id"`
	AuthUserID *uuid.UUID `json:"auth_user_id"`
	Status     string     `json:"status"`
	ExpiresAt  time.Time  `json:"expires_at"`
}

func (q *Queries) GetQRLoginRequest(ctx context.Context, id uuid.UUID) (GetQRLoginRequestRow, error) {
	row := q.db.QueryRow(ctx, getQRLoginRequest, id)
	var i GetQRLoginRequestRow
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const notifyQREvent = `-- name: NotifyQREvent :exec
SELECT pg_notify('qr_login_events', $1::text)
`

func (q *Queries) NotifyQREvent(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, notifyQREvent, dollar_1)
	return err
}
