// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package core_auth_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddQRLoginBrowserCandidate(ctx context.Context, arg AddQRLoginBrowserCandidateParams) (uuid.UUID, error)
	AddQRLoginMobileCandidate(ctx context.Context, arg AddQRLoginMobileCandidateParams) (uuid.UUID, error)
	ApproveQRLogin(ctx context.Context, arg ApproveQRLoginParams) (uuid.UUID, error)
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	// Checks if the user already has a central device
	CheckHasCentralDevice(ctx context.Context, authUserID uuid.UUID) (bool, error)
	// ======================================
	// Auth Queries
	// ======================================
	// Checks if a session is valid for a specific user and not expired
	CheckSessionIsValid(ctx context.Context, arg CheckSessionIsValidParams) (bool, error)
	CleanupExpiredQRLoginRequests(ctx context.Context) error
	CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error)
	CreateQRLoginRequest(ctx context.Context, arg CreateQRLoginRequestParams) (uuid.UUID, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error)
	CreateVerificationCodeWithUpdateID(ctx context.Context, arg CreateVerificationCodeWithUpdateIDParams) (VerificationCode, error)
	DeleteAllUserSessions(ctx context.Context, authUserID uuid.UUID) error
	DeleteAllVerificationCodesForEmail(ctx context.Context, arg DeleteAllVerificationCodesForEmailParams) error
	// Delete auth user (cascade will automatically delete sessions and verification_codes)
	DeleteAuthUser(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	DeleteSessionByToken(ctx context.Context, arg DeleteSessionByTokenParams) error
	DeleteVerificationCode(ctx context.Context, id uuid.UUID) error
	ExchangeQRLogin(ctx context.Context, id uuid.UUID) (*uuid.UUID, error)
	// ======================================
	// Rate Limiter Queries
	// ======================================
	GetAuthRateLimiter(ctx context.Context, authUserID uuid.UUID) (AuthRateLimiter, error)
	GetAuthUserByEmail(ctx context.Context, email string) (AuthUser, error)
	// Returns auth user by ID
	GetAuthUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error)
	// Returns the details of the central session for a user
	GetCentralSession(ctx context.Context, authUserID uuid.UUID) (Session, error)
	GetQRLoginRequest(ctx context.Context, id uuid.UUID) (GetQRLoginRequestRow, error)
	GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (Session, error)
	// Returns user's primary device session (for Phase 6 messaging eligibility)
	GetUserPrimarySession(ctx context.Context, authUserID uuid.UUID) (Session, error)
	// Get the verification code by User ID (PK) and Type
	GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error)
	NotifyQREvent(ctx context.Context, dollar_1 string) error
	// Sets is_central = false for ALL sessions of this user (Upgrade preparation)
	ResetCentralSessions(ctx context.Context, authUserID uuid.UUID) error
	ResetVerifyErrors(ctx context.Context, authUserID uuid.UUID) error
	// Sets is_central = true for a specific session
	SetSessionCentral(ctx context.Context, arg SetSessionCentralParams) error
	// Sets is_central = true for a session identified by token hash
	SetSessionCentralByToken(ctx context.Context, arg SetSessionCentralByTokenParams) error
	UpdateAuthUserEmail(ctx context.Context, arg UpdateAuthUserEmailParams) error
	UpdateAuthUserEmailVerified(ctx context.Context, arg UpdateAuthUserEmailVerifiedParams) error
	UpdateAuthUserPassword(ctx context.Context, arg UpdateAuthUserPasswordParams) error
	// Updates an existing unverified user during signup to reuse the ID and preserve rate limits
	UpdateAuthUserSignup(ctx context.Context, arg UpdateAuthUserSignupParams) error
	UpdateQRLoginSignalAnswer(ctx context.Context, arg UpdateQRLoginSignalAnswerParams) (uuid.UUID, error)
	UpdateQRLoginSignalOffer(ctx context.Context, arg UpdateQRLoginSignalOfferParams) (uuid.UUID, error)
	UpdateSessionDeviceToken(ctx context.Context, arg UpdateSessionDeviceTokenParams) error
	UpsertAuthRateLimiterSend(ctx context.Context, arg UpsertAuthRateLimiterSendParams) (AuthRateLimiter, error)
	UpsertAuthRateLimiterVerify(ctx context.Context, arg UpsertAuthRateLimiterVerifyParams) (AuthRateLimiter, error)
}

var _ Querier = (*Queries)(nil)
