// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package personal_chat_store

import (
	"time"

	"github.com/google/uuid"
)

type AloneUsername struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AuthUser struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Email           string    `json:"email"`
	PasswordHash    string    `json:"password_hash"`
	IsEmailVerified bool      `json:"is_email_verified"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Avatar struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	FileID      string     `json:"file_id"`
	AvatarType  string     `json:"avatar_type"`
	TokenID     *string    `json:"token_id"`
	TokenSecret *string    `json:"token_secret"`
	TokenExpiry *time.Time `json:"token_expiry"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type Chat struct {
	ID             uuid.UUID `json:"id"`
	Participant1ID uuid.UUID `json:"participant_1_id"`
	Participant2ID uuid.UUID `json:"participant_2_id"`
	// Unread count for participant_1_id
	P1UnreadCount int32 `json:"p1_unread_count"`
	// Unread count for participant_2_id
	P2UnreadCount int32      `json:"p2_unread_count"`
	P1LastReadAt  *time.Time `json:"p1_last_read_at"`
	P2LastReadAt  *time.Time `json:"p2_last_read_at"`
	// Timestamp of the last message delivered to participant 1
	P1LastDeliveredAt *time.Time `json:"p1_last_delivered_at"`
	// Timestamp of the last message delivered to participant 2
	P2LastDeliveredAt    *time.Time `json:"p2_last_delivered_at"`
	LastMessageCreatedAt *time.Time `json:"last_message_created_at"`
	LastMessageSenderID  *uuid.UUID `json:"last_message_sender_id"`
	// UUID of the message currently displayed as the preview
	LastMessageID *uuid.UUID `json:"last_message_id"`
	// Last message preview content for participant_1
	P1LastMessageContent *string `json:"p1_last_message_content"`
	// Last message preview content for participant_2
	P2LastMessageContent *string `json:"p2_last_message_content"`
	// Last message type for participant_1 preview
	P1LastMessageType *string `json:"p1_last_message_type"`
	// Last message type for participant_2 preview
	P2LastMessageType *string   `json:"p2_last_message_type"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type ContactRequest struct {
	ID              uuid.UUID `json:"id"`
	RequesterUserID uuid.UUID `json:"requester_user_id"`
	ReceiverUserID  uuid.UUID `json:"receiver_user_id"`
	Status          string    `json:"status"`
	Nickname        *string   `json:"nickname"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Message struct {
	ID                          uuid.UUID  `json:"id"`
	ChatID                      uuid.UUID  `json:"chat_id"`
	SenderID                    uuid.UUID  `json:"sender_id"`
	RecipientID                 uuid.UUID  `json:"recipient_id"`
	Content                     string     `json:"content"`
	MessageType                 string     `json:"message_type"`
	FileID                      *string    `json:"file_id"`
	FileName                    *string    `json:"file_name"`
	FileSize                    *int64     `json:"file_size"`
	FileMimeType                *string    `json:"file_mime_type"`
	FileTokenID                 *string    `json:"file_token_id"`
	FileTokenSecret             *string    `json:"file_token_secret"`
	FileTokenExpiry             *time.Time `json:"file_token_expiry"`
	ThumbnailFileID             *string    `json:"thumbnail_file_id"`
	ThumbnailTokenID            *string    `json:"thumbnail_token_id"`
	ThumbnailTokenSecret        *string    `json:"thumbnail_token_secret"`
	DeliveredToRecipient        bool       `json:"delivered_to_recipient"`
	DeliveredToRecipientPrimary *bool      `json:"delivered_to_recipient_primary"`
	SyncedToSenderPrimary       bool       `json:"synced_to_sender_primary"`
	DeletedBySender             bool       `json:"deleted_by_sender"`
	DeletedByRecipient          bool       `json:"deleted_by_recipient"`
	DeliveryAttempts            int32      `json:"delivery_attempts"`
	ExpiresAt                   time.Time  `json:"expires_at"`
	CreatedAt                   time.Time  `json:"created_at"`
	UpdatedAt                   time.Time  `json:"updated_at"`
}

type MessageSyncAction struct {
	ID                 uuid.UUID `json:"id"`
	UserID             uuid.UUID `json:"user_id"`
	ActionType         string    `json:"action_type"`
	Payload            []byte    `json:"payload"`
	DeliveredToPrimary bool      `json:"delivered_to_primary"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type Session struct {
	ID          uuid.UUID `json:"id"`
	AuthUserID  uuid.UUID `json:"auth_user_id"`
	TokenHash   string    `json:"token_hash"`
	DeviceToken *string   `json:"device_token"`
	Platform    *string   `json:"platform"`
	DeviceName  *string   `json:"device_name"`
	IsCentral   bool      `json:"is_central"`
	UserAgent   *string   `json:"user_agent"`
	IpAddress   *string   `json:"ip_address"`
	ExpiresAt   time.Time `json:"expires_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Token struct {
	ID                 uuid.UUID `json:"id"`
	UserID             uuid.UUID `json:"user_id"`
	Sha256HexSessionID string    `json:"sha256_hex_session_id"`
	Token              string    `json:"token"`
	Type               string    `json:"type"`
	IsActive           bool      `json:"is_active"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type User struct {
	ID                                uuid.UUID `json:"id"`
	Name                              string    `json:"name"`
	Bio                               *string   `json:"bio"`
	ProfileType                       string    `json:"profile_type"`
	IsAdminBlocked                    bool      `json:"is_admin_blocked"`
	AdminBlockReason                  *string   `json:"admin_block_reason"`
	HmacSha256HexUsername             string    `json:"hmac_sha256_hex_username"`
	B64CipherChacha20poly1305Username string    `json:"b64_cipher_chacha20poly1305_username"`
	CreatedAt                         time.Time `json:"created_at"`
	UpdatedAt                         time.Time `json:"updated_at"`
}

type UserBlock struct {
	ID            uuid.UUID `json:"id"`
	BlockerUserID uuid.UUID `json:"blocker_user_id"`
	BlockedUserID uuid.UUID `json:"blocked_user_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UserContact struct {
	OwnerUserID   uuid.UUID `json:"owner_user_id"`
	ContactUserID uuid.UUID `json:"contact_user_id"`
	Nickname      *string   `json:"nickname"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UserGlobalRestriction struct {
	UserID          uuid.UUID `json:"user_id"`
	RestrictAvatar  bool      `json:"restrict_avatar"`
	RestrictStatus  bool      `json:"restrict_status"`
	RestrictProfile bool      `json:"restrict_profile"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type UserGlobalRestrictionExemption struct {
	UserID           uuid.UUID `json:"user_id"`
	ExemptedUserID   uuid.UUID `json:"exempted_user_id"`
	ExceptionAvatar  bool      `json:"exception_avatar"`
	ExceptionStatus  bool      `json:"exception_status"`
	ExceptionProfile bool      `json:"exception_profile"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type UserRestriction struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	RestrictedUserID uuid.UUID `json:"restricted_user_id"`
	RestrictProfile  bool      `json:"restrict_profile"`
	RestrictAvatar   bool      `json:"restrict_avatar"`
	RestrictStatus   bool      `json:"restrict_status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type VerificationCode struct {
	ID        uuid.UUID  `json:"id"`
	UpdateID  *uuid.UUID `json:"update_id"`
	Email     string     `json:"email"`
	CodeHash  string     `json:"code_hash"`
	Type      string     `json:"type"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}
