// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_chat.sql

package personal_chat_store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanupMessagesForBlockedUsers = `-- name: CleanupMessagesForBlockedUsers :exec

DELETE FROM messages m
USING chats c, user_blocks ub
WHERE m.chat_id = c.id
AND (
    (c.participant_1_id = ub.blocker_user_id AND c.participant_2_id = ub.blocked_user_id)
    OR
    (c.participant_1_id = ub.blocked_user_id AND c.participant_2_id = ub.blocker_user_id)
)
`

// ===========================================
// Block Cleanup Operations (Background Worker)
// ===========================================
// Background cleanup: Deletes messages for chats where users have blocked each other.
// NOTE: This only handles DB records. Apprites file cleanup must be done in Go.
func (q *Queries) CleanupMessagesForBlockedUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupMessagesForBlockedUsers)
	return err
}

const cleanupOlderFullyAcknowledgedMessages = `-- name: CleanupOlderFullyAcknowledgedMessages :exec
DELETE FROM messages
WHERE
    chat_id = $1
    AND created_at <= $2
    AND message_type = 'text'
    AND delivered_to_recipient_primary = TRUE
    AND synced_to_sender_primary = TRUE
`

type CleanupOlderFullyAcknowledgedMessagesParams struct {
	ChatID    uuid.UUID `json:"chat_id"`
	CreatedAt time.Time `json:"created_at"`
}

// Deletes all messages in a chat that are fully acknowledged (both primary flags TRUE)
// and are older than or equal to a specific timestamp, but ONLY if they are plain text.
func (q *Queries) CleanupOlderFullyAcknowledgedMessages(ctx context.Context, arg CleanupOlderFullyAcknowledgedMessagesParams) error {
	_, err := q.db.Exec(ctx, cleanupOlderFullyAcknowledgedMessages, arg.ChatID, arg.CreatedAt)
	return err
}

const cleanupSyncActionsForBlockedUsers = `-- name: CleanupSyncActionsForBlockedUsers :exec
DELETE FROM message_sync_actions msa
USING chats c, user_blocks ub
WHERE (msa.payload::jsonb->>'chatId')::uuid = c.id
AND (
    (c.participant_1_id = ub.blocker_user_id AND c.participant_2_id = ub.blocked_user_id)
    OR
    (c.participant_1_id = ub.blocked_user_id AND c.participant_2_id = ub.blocker_user_id)
)
`

// Background cleanup: Deletes sync actions for chats where users have blocked each other.
// This handles orphaned sync actions even if the trigger (007) is not yet applied or was missed.
func (q *Queries) CleanupSyncActionsForBlockedUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupSyncActionsForBlockedUsers)
	return err
}

const clearLastMessageForParticipant = `-- name: ClearLastMessageForParticipant :exec

UPDATE chats
SET
    p1_last_message_content = CASE
        WHEN participant_1_id = $1 THEN NULL
        ELSE p1_last_message_content
    END,
    p2_last_message_content = CASE
        WHEN participant_2_id = $1 THEN NULL
        ELSE p2_last_message_content
    END,
    p1_last_message_type = CASE
        WHEN participant_1_id = $1 THEN NULL
        ELSE p1_last_message_type
    END,
    p2_last_message_type = CASE
        WHEN participant_2_id = $1 THEN NULL
        ELSE p2_last_message_type
    END,
    updated_at = now()
WHERE
    id = $2
    AND last_message_id = $3
`

type ClearLastMessageForParticipantParams struct {
	UserID    uuid.UUID  `json:"user_id"`
	ChatID    uuid.UUID  `json:"chat_id"`
	MessageID *uuid.UUID `json:"message_id"`
}

// ===========================================
// Per-Participant Preview Operations
// ===========================================
// Clears the last message preview for a specific participant only (used by Delete for Me).
// Only fires if the deleted message is the current preview message.
func (q *Queries) ClearLastMessageForParticipant(ctx context.Context, arg ClearLastMessageForParticipantParams) error {
	_, err := q.db.Exec(ctx, clearLastMessageForParticipant, arg.UserID, arg.ChatID, arg.MessageID)
	return err
}

const clearMessageFileFields = `-- name: ClearMessageFileFields :exec
UPDATE messages
SET
    file_id = NULL,
    file_name = NULL,
    file_size = NULL,
    file_mime_type = NULL,
    file_token_id = NULL,
    file_token_secret = NULL,
    file_token_expiry = NULL,
    updated_at = now()
WHERE
    id = $1
`

func (q *Queries) ClearMessageFileFields(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearMessageFileFields, id)
	return err
}

const consumeSyncAction = `-- name: ConsumeSyncAction :exec
DELETE FROM message_sync_actions WHERE id = $1
`

func (q *Queries) ConsumeSyncAction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeSyncAction, id)
	return err
}

const createChat = `-- name: CreateChat :one

INSERT INTO
    chats (
        id,
        participant_1_id,
        participant_2_id
    )
VALUES (
        $1,
        LEAST($2::uuid, $3::uuid),
        GREATEST($2::uuid, $3::uuid)
    )
ON CONFLICT (
    participant_1_id,
    participant_2_id
) DO
UPDATE
SET
    updated_at = now()
RETURNING
    id, participant_1_id, participant_2_id, p1_unread_count, p2_unread_count, p1_last_read_at, p2_last_read_at, p1_last_delivered_at, p2_last_delivered_at, last_message_created_at, last_message_sender_id, last_message_id, p1_last_message_content, p2_last_message_content, p1_last_message_type, p2_last_message_type, created_at, updated_at
`

type CreateChatParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 uuid.UUID `json:"column_2"`
	Column3 uuid.UUID `json:"column_3"`
}

// ===========================================
// Chat Queries for sqlc
// ===========================================
func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.ID, arg.Column2, arg.Column3)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Participant1ID,
		&i.Participant2ID,
		&i.P1UnreadCount,
		&i.P2UnreadCount,
		&i.P1LastReadAt,
		&i.P2LastReadAt,
		&i.P1LastDeliveredAt,
		&i.P2LastDeliveredAt,
		&i.LastMessageCreatedAt,
		&i.LastMessageSenderID,
		&i.LastMessageID,
		&i.P1LastMessageContent,
		&i.P2LastMessageContent,
		&i.P1LastMessageType,
		&i.P2LastMessageType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one

INSERT INTO
    messages (
        id,
        chat_id,
        sender_id,
        recipient_id,
        content,
        message_type,
        expires_at,
        synced_to_sender_primary,
        delivered_to_recipient_primary
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
RETURNING
    id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, delivered_to_recipient_primary, synced_to_sender_primary, deleted_by_sender, deleted_by_recipient, delivery_attempts, expires_at, created_at, updated_at
`

type CreateMessageParams struct {
	ID                          uuid.UUID `json:"id"`
	ChatID                      uuid.UUID `json:"chat_id"`
	SenderID                    uuid.UUID `json:"sender_id"`
	RecipientID                 uuid.UUID `json:"recipient_id"`
	Content                     string    `json:"content"`
	MessageType                 string    `json:"message_type"`
	ExpiresAt                   time.Time `json:"expires_at"`
	SyncedToSenderPrimary       bool      `json:"synced_to_sender_primary"`
	DeliveredToRecipientPrimary *bool     `json:"delivered_to_recipient_primary"`
}

// ===========================================
// Message Operations
// ===========================================
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ChatID,
		arg.SenderID,
		arg.RecipientID,
		arg.Content,
		arg.MessageType,
		arg.ExpiresAt,
		arg.SyncedToSenderPrimary,
		arg.DeliveredToRecipientPrimary,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.RecipientID,
		&i.Content,
		&i.MessageType,
		&i.FileID,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.FileTokenID,
		&i.FileTokenSecret,
		&i.FileTokenExpiry,
		&i.ThumbnailFileID,
		&i.ThumbnailTokenID,
		&i.ThumbnailTokenSecret,
		&i.DeliveredToRecipient,
		&i.DeliveredToRecipientPrimary,
		&i.SyncedToSenderPrimary,
		&i.DeletedBySender,
		&i.DeletedByRecipient,
		&i.DeliveryAttempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessageWithFile = `-- name: CreateMessageWithFile :one

INSERT INTO
    messages (
        id,
        chat_id,
        sender_id,
        recipient_id,
        content,
        message_type,
        file_id,
        file_name,
        file_size,
        file_mime_type,
        file_token_id,
        file_token_secret,
        file_token_expiry,
        expires_at,
        synced_to_sender_primary,
        delivered_to_recipient_primary
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16
    )
RETURNING
    id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, delivered_to_recipient_primary, synced_to_sender_primary, deleted_by_sender, deleted_by_recipient, delivery_attempts, expires_at, created_at, updated_at
`

type CreateMessageWithFileParams struct {
	ID                          uuid.UUID  `json:"id"`
	ChatID                      uuid.UUID  `json:"chat_id"`
	SenderID                    uuid.UUID  `json:"sender_id"`
	RecipientID                 uuid.UUID  `json:"recipient_id"`
	Content                     string     `json:"content"`
	MessageType                 string     `json:"message_type"`
	FileID                      *string    `json:"file_id"`
	FileName                    *string    `json:"file_name"`
	FileSize                    *int64     `json:"file_size"`
	FileMimeType                *string    `json:"file_mime_type"`
	FileTokenID                 *string    `json:"file_token_id"`
	FileTokenSecret             *string    `json:"file_token_secret"`
	FileTokenExpiry             *time.Time `json:"file_token_expiry"`
	ExpiresAt                   time.Time  `json:"expires_at"`
	SyncedToSenderPrimary       bool       `json:"synced_to_sender_primary"`
	DeliveredToRecipientPrimary *bool      `json:"delivered_to_recipient_primary"`
}

// ===========================================
// File Messaging Operations
// ===========================================
func (q *Queries) CreateMessageWithFile(ctx context.Context, arg CreateMessageWithFileParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessageWithFile,
		arg.ID,
		arg.ChatID,
		arg.SenderID,
		arg.RecipientID,
		arg.Content,
		arg.MessageType,
		arg.FileID,
		arg.FileName,
		arg.FileSize,
		arg.FileMimeType,
		arg.FileTokenID,
		arg.FileTokenSecret,
		arg.FileTokenExpiry,
		arg.ExpiresAt,
		arg.SyncedToSenderPrimary,
		arg.DeliveredToRecipientPrimary,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.RecipientID,
		&i.Content,
		&i.MessageType,
		&i.FileID,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.FileTokenID,
		&i.FileTokenSecret,
		&i.FileTokenExpiry,
		&i.ThumbnailFileID,
		&i.ThumbnailTokenID,
		&i.ThumbnailTokenSecret,
		&i.DeliveredToRecipient,
		&i.DeliveredToRecipientPrimary,
		&i.SyncedToSenderPrimary,
		&i.DeletedBySender,
		&i.DeletedByRecipient,
		&i.DeliveryAttempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSyncAction = `-- name: CreateSyncAction :one

INSERT INTO
    message_sync_actions (
        id,
        user_id,
        action_type,
        payload,
        created_at
    )
VALUES ($1, $2, $3, $4, now())
RETURNING
    id, user_id, action_type, payload, delivered_to_primary, created_at, updated_at
`

type CreateSyncActionParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	ActionType string    `json:"action_type"`
	Payload    []byte    `json:"payload"`
}

// ===========================================
// Sync Action Operations
// ===========================================
func (q *Queries) CreateSyncAction(ctx context.Context, arg CreateSyncActionParams) (MessageSyncAction, error) {
	row := q.db.QueryRow(ctx, createSyncAction,
		arg.ID,
		arg.UserID,
		arg.ActionType,
		arg.Payload,
	)
	var i MessageSyncAction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActionType,
		&i.Payload,
		&i.DeliveredToPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBlockedUserMessagesWithoutFiles = `-- name: DeleteBlockedUserMessagesWithoutFiles :exec
DELETE FROM messages m
USING chats c, user_blocks ub
WHERE m.chat_id = c.id
  AND m.file_id IS NULL
  AND (
      (c.participant_1_id = ub.blocker_user_id AND c.participant_2_id = ub.blocked_user_id)
      OR
      (c.participant_2_id = ub.blocker_user_id AND c.participant_1_id = ub.blocked_user_id)
  )
`

// Bulk-deletes messages for blocked-user chats that have no attached file_id (safe — no R2 orphans).
// Messages WITH files are handled by the batched cleanup loop.
func (q *Queries) DeleteBlockedUserMessagesWithoutFiles(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteBlockedUserMessagesWithoutFiles)
	return err
}

const deleteExpiredHistorySync = `-- name: DeleteExpiredHistorySync :exec
DELETE FROM history_sync WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredHistorySync(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredHistorySync)
	return err
}

const deleteExpiredMessagesWithoutFiles = `-- name: DeleteExpiredMessagesWithoutFiles :exec
DELETE FROM messages
WHERE expires_at < now()
  AND file_id IS NULL
`

// Bulk-deletes EXPIRED messages that have no attached file_id (safe — no R2 orphans possible).
// Messages WITH files are handled by the batched cleanup loop (file deleted first, then DB row).
func (q *Queries) DeleteExpiredMessagesWithoutFiles(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredMessagesWithoutFiles)
	return err
}

const deleteFullyAcknowledgedMessagesWithoutFiles = `-- name: DeleteFullyAcknowledgedMessagesWithoutFiles :exec
DELETE FROM messages
WHERE delivered_to_recipient_primary = TRUE
  AND synced_to_sender_primary = TRUE
  AND file_id IS NULL
`

// Bulk-deletes messages where BOTH primary devices have acknowledged (delivered to
// recipient primary AND synced to sender primary) AND the message has NO file_id.
// Safe bulk delete — no R2 orphan possible.
// For text-only messages, both devices already have a local copy, so the server
// copy is redundant and can be removed immediately.
// File-having messages are handled by the batched loop (R2 first, then DB).
func (q *Queries) DeleteFullyAcknowledgedMessagesWithoutFiles(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteFullyAcknowledgedMessagesWithoutFiles)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const deleteOldSyncActions = `-- name: DeleteOldSyncActions :exec
DELETE FROM message_sync_actions
WHERE
    created_at < now() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldSyncActions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldSyncActions)
	return err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, participant_1_id, participant_2_id, p1_unread_count, p2_unread_count, p1_last_read_at, p2_last_read_at, p1_last_delivered_at, p2_last_delivered_at, last_message_created_at, last_message_sender_id, last_message_id, p1_last_message_content, p2_last_message_content, p1_last_message_type, p2_last_message_type, created_at, updated_at FROM chats WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Participant1ID,
		&i.Participant2ID,
		&i.P1UnreadCount,
		&i.P2UnreadCount,
		&i.P1LastReadAt,
		&i.P2LastReadAt,
		&i.P1LastDeliveredAt,
		&i.P2LastDeliveredAt,
		&i.LastMessageCreatedAt,
		&i.LastMessageSenderID,
		&i.LastMessageID,
		&i.P1LastMessageContent,
		&i.P2LastMessageContent,
		&i.P1LastMessageType,
		&i.P2LastMessageType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatByParticipants = `-- name: GetChatByParticipants :one
SELECT id, participant_1_id, participant_2_id, p1_unread_count, p2_unread_count, p1_last_read_at, p2_last_read_at, p1_last_delivered_at, p2_last_delivered_at, last_message_created_at, last_message_sender_id, last_message_id, p1_last_message_content, p2_last_message_content, p1_last_message_type, p2_last_message_type, created_at, updated_at
FROM chats
WHERE
    participant_1_id = LEAST($1::uuid, $2::uuid)
    AND participant_2_id = GREATEST($1::uuid, $2::uuid)
LIMIT 1
`

type GetChatByParticipantsParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) GetChatByParticipants(ctx context.Context, arg GetChatByParticipantsParams) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByParticipants, arg.Column1, arg.Column2)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Participant1ID,
		&i.Participant2ID,
		&i.P1UnreadCount,
		&i.P2UnreadCount,
		&i.P1LastReadAt,
		&i.P2LastReadAt,
		&i.P1LastDeliveredAt,
		&i.P2LastDeliveredAt,
		&i.LastMessageCreatedAt,
		&i.LastMessageSenderID,
		&i.LastMessageID,
		&i.P1LastMessageContent,
		&i.P2LastMessageContent,
		&i.P1LastMessageType,
		&i.P2LastMessageType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, delivered_to_recipient_primary, synced_to_sender_primary, deleted_by_sender, deleted_by_recipient, delivery_attempts, expires_at, created_at, updated_at
FROM messages
WHERE
    chat_id = $1
    AND expires_at > now()
    AND created_at >= $5
    AND (
        (
            sender_id = $4
            AND deleted_by_sender = FALSE
        )
        OR (
            recipient_id = $4
            AND deleted_by_recipient = FALSE
        )
    )
ORDER BY created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetChatMessagesParams struct {
	ChatID           uuid.UUID `json:"chat_id"`
	Limit            int32     `json:"limit"`
	Offset           int32     `json:"offset"`
	SenderID         uuid.UUID `json:"sender_id"`
	SessionCreatedAt time.Time `json:"session_created_at"`
}

func (q *Queries) GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getChatMessages,
		arg.ChatID,
		arg.Limit,
		arg.Offset,
		arg.SenderID,
		arg.SessionCreatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.DeliveredToRecipientPrimary,
			&i.SyncedToSenderPrimary,
			&i.DeletedBySender,
			&i.DeletedByRecipient,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatsByUserID = `-- name: GetChatsByUserID :many
SELECT id, participant_1_id, participant_2_id, p1_unread_count, p2_unread_count, p1_last_read_at, p2_last_read_at, p1_last_delivered_at, p2_last_delivered_at, last_message_created_at, last_message_sender_id, last_message_id, p1_last_message_content, p2_last_message_content, p1_last_message_type, p2_last_message_type, created_at, updated_at
FROM chats
WHERE
    participant_1_id = $1
    OR participant_2_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetChatsByUserID(ctx context.Context, participant1ID uuid.UUID) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getChatsByUserID, participant1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Participant1ID,
			&i.Participant2ID,
			&i.P1UnreadCount,
			&i.P2UnreadCount,
			&i.P1LastReadAt,
			&i.P2LastReadAt,
			&i.P1LastDeliveredAt,
			&i.P2LastDeliveredAt,
			&i.LastMessageCreatedAt,
			&i.LastMessageSenderID,
			&i.LastMessageID,
			&i.P1LastMessageContent,
			&i.P2LastMessageContent,
			&i.P1LastMessageType,
			&i.P2LastMessageType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveredMessagesByChat = `-- name: GetDeliveredMessagesByChat :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, delivered_to_recipient_primary, synced_to_sender_primary, deleted_by_sender, deleted_by_recipient, delivery_attempts, expires_at, created_at, updated_at
FROM messages
WHERE
    chat_id = $1
    AND (
        (
            recipient_id = $2
            AND delivered_to_recipient_primary = TRUE
            AND synced_to_sender_primary = TRUE
        )
        OR (
            sender_id = $2
            AND delivered_to_recipient_primary = TRUE
            AND synced_to_sender_primary = TRUE
        )
    )
`

type GetDeliveredMessagesByChatParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetDeliveredMessagesByChat(ctx context.Context, arg GetDeliveredMessagesByChatParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getDeliveredMessagesByChat, arg.ChatID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.DeliveredToRecipientPrimary,
			&i.SyncedToSenderPrimary,
			&i.DeletedBySender,
			&i.DeletedByRecipient,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredMessagesWithFiles = `-- name: GetExpiredMessagesWithFiles :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, delivered_to_recipient_primary, synced_to_sender_primary, deleted_by_sender, deleted_by_recipient, delivery_attempts, expires_at, created_at, updated_at
FROM messages
WHERE (
        expires_at < now()
        OR (
            delivered_to_recipient_primary = TRUE
            AND synced_to_sender_primary = TRUE
        )
    )
    AND file_id IS NOT NULL
    AND id > $2
ORDER BY id ASC
LIMIT $1
`

type GetExpiredMessagesWithFilesParams struct {
	Limit  int32     `json:"limit"`
	LastID uuid.UUID `json:"last_id"`
}

func (q *Queries) GetExpiredMessagesWithFiles(ctx context.Context, arg GetExpiredMessagesWithFilesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getExpiredMessagesWithFiles, arg.Limit, arg.LastID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.DeliveredToRecipientPrimary,
			&i.SyncedToSenderPrimary,
			&i.DeletedBySender,
			&i.DeletedByRecipient,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistorySyncForDownload = `-- name: GetHistorySyncForDownload :one
SELECT payload 
FROM history_sync 
WHERE id = $1 AND session_id = $2
`

type GetHistorySyncForDownloadParams struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) GetHistorySyncForDownload(ctx context.Context, arg GetHistorySyncForDownloadParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getHistorySyncForDownload, arg.ID, arg.SessionID)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const getHistorySyncMeta = `-- name: GetHistorySyncMeta :one
SELECT user_id, session_id, expires_at 
FROM history_sync 
WHERE id = $1
`

type GetHistorySyncMetaRow struct {
	UserID    uuid.UUID `json:"user_id"`
	SessionID uuid.UUID `json:"session_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetHistorySyncMeta(ctx context.Context, id uuid.UUID) (GetHistorySyncMetaRow, error) {
	row := q.db.QueryRow(ctx, getHistorySyncMeta, id)
	var i GetHistorySyncMetaRow
	err := row.Scan(&i.UserID, &i.SessionID, &i.ExpiresAt)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, delivered_to_recipient_primary, synced_to_sender_primary, deleted_by_sender, deleted_by_recipient, delivery_attempts, expires_at, created_at, updated_at FROM messages WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.RecipientID,
		&i.Content,
		&i.MessageType,
		&i.FileID,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.FileTokenID,
		&i.FileTokenSecret,
		&i.FileTokenExpiry,
		&i.ThumbnailFileID,
		&i.ThumbnailTokenID,
		&i.ThumbnailTokenSecret,
		&i.DeliveredToRecipient,
		&i.DeliveredToRecipientPrimary,
		&i.SyncedToSenderPrimary,
		&i.DeletedBySender,
		&i.DeletedByRecipient,
		&i.DeliveryAttempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessagesWithExpiredFileTokens = `-- name: GetMessagesWithExpiredFileTokens :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, delivered_to_recipient_primary, synced_to_sender_primary, deleted_by_sender, deleted_by_recipient, delivery_attempts, expires_at, created_at, updated_at
FROM messages
WHERE
    file_id IS NOT NULL
    AND file_token_expiry IS NOT NULL
    AND file_token_expiry < now()
    AND expires_at > now()
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetMessagesWithExpiredFileTokens(ctx context.Context, limit int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesWithExpiredFileTokens, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.DeliveredToRecipientPrimary,
			&i.SyncedToSenderPrimary,
			&i.DeletedBySender,
			&i.DeletedByRecipient,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesWithFilesForBlockedUsers = `-- name: GetMessagesWithFilesForBlockedUsers :many
SELECT m.id, m.chat_id, m.sender_id, m.recipient_id, m.content, m.message_type, m.file_id, m.file_name, m.file_size, m.file_mime_type, m.file_token_id, m.file_token_secret, m.file_token_expiry, m.thumbnail_file_id, m.thumbnail_token_id, m.thumbnail_token_secret, m.delivered_to_recipient, m.delivered_to_recipient_primary, m.synced_to_sender_primary, m.deleted_by_sender, m.deleted_by_recipient, m.delivery_attempts, m.expires_at, m.created_at, m.updated_at
FROM messages m
INNER JOIN chats c ON m.chat_id = c.id
INNER JOIN user_blocks ub ON (
    (c.participant_1_id = ub.blocker_user_id AND c.participant_2_id = ub.blocked_user_id)
    OR
    (c.participant_1_id = ub.blocked_user_id AND c.participant_2_id = ub.blocker_user_id)
)
WHERE m.file_id IS NOT NULL
AND m.id > $1
ORDER BY m.id ASC
LIMIT $2
`

type GetMessagesWithFilesForBlockedUsersParams struct {
	LastID uuid.UUID `json:"last_id"`
	Limit  int32     `json:"limit"`
}

// Fetches messages with files for chats between blocked users for cleanup.
func (q *Queries) GetMessagesWithFilesForBlockedUsers(ctx context.Context, arg GetMessagesWithFilesForBlockedUsersParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesWithFilesForBlockedUsers, arg.LastID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.DeliveredToRecipientPrimary,
			&i.SyncedToSenderPrimary,
			&i.DeletedBySender,
			&i.DeletedByRecipient,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingHistorySyncForUser = `-- name: GetPendingHistorySyncForUser :many
SELECT id, session_id, chats_json 
FROM history_sync 
WHERE user_id = $1 AND payload IS NULL AND expires_at > now()
`

type GetPendingHistorySyncForUserRow struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
	ChatsJson []byte    `json:"chats_json"`
}

func (q *Queries) GetPendingHistorySyncForUser(ctx context.Context, userID uuid.UUID) ([]GetPendingHistorySyncForUserRow, error) {
	rows, err := q.db.Query(ctx, getPendingHistorySyncForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingHistorySyncForUserRow
	for rows.Next() {
		var i GetPendingHistorySyncForUserRow
		if err := rows.Scan(&i.ID, &i.SessionID, &i.ChatsJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingMessagesForRecipient = `-- name: GetPendingMessagesForRecipient :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, delivered_to_recipient_primary, synced_to_sender_primary, deleted_by_sender, deleted_by_recipient, delivery_attempts, expires_at, created_at, updated_at
FROM messages
WHERE
    recipient_id = $1
    AND deleted_by_recipient = FALSE
    AND expires_at > now()
    AND created_at >= $3
ORDER BY created_at ASC
LIMIT $2
`

type GetPendingMessagesForRecipientParams struct {
	RecipientID      uuid.UUID `json:"recipient_id"`
	Limit            int32     `json:"limit"`
	SessionCreatedAt time.Time `json:"session_created_at"`
}

func (q *Queries) GetPendingMessagesForRecipient(ctx context.Context, arg GetPendingMessagesForRecipientParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getPendingMessagesForRecipient, arg.RecipientID, arg.Limit, arg.SessionCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.DeliveredToRecipientPrimary,
			&i.SyncedToSenderPrimary,
			&i.DeletedBySender,
			&i.DeletedByRecipient,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingSenderSyncMessages = `-- name: GetPendingSenderSyncMessages :many
SELECT id, chat_id, sender_id, recipient_id, content, message_type, file_id, file_name, file_size, file_mime_type, file_token_id, file_token_secret, file_token_expiry, thumbnail_file_id, thumbnail_token_id, thumbnail_token_secret, delivered_to_recipient, delivered_to_recipient_primary, synced_to_sender_primary, deleted_by_sender, deleted_by_recipient, delivery_attempts, expires_at, created_at, updated_at
FROM messages
WHERE
    sender_id = $1
    AND deleted_by_sender = FALSE
    AND expires_at > now()
ORDER BY created_at ASC
LIMIT $2
`

type GetPendingSenderSyncMessagesParams struct {
	SenderID uuid.UUID `json:"sender_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) GetPendingSenderSyncMessages(ctx context.Context, arg GetPendingSenderSyncMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getPendingSenderSyncMessages, arg.SenderID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.MessageType,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.FileTokenID,
			&i.FileTokenSecret,
			&i.FileTokenExpiry,
			&i.ThumbnailFileID,
			&i.ThumbnailTokenID,
			&i.ThumbnailTokenSecret,
			&i.DeliveredToRecipient,
			&i.DeliveredToRecipientPrimary,
			&i.SyncedToSenderPrimary,
			&i.DeletedBySender,
			&i.DeletedByRecipient,
			&i.DeliveryAttempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingSyncActions = `-- name: GetPendingSyncActions :many
SELECT id, user_id, action_type, payload, delivered_to_primary, created_at, updated_at
FROM message_sync_actions
WHERE
    user_id = $1
    AND delivered_to_primary = FALSE
ORDER BY created_at ASC
LIMIT $2
`

type GetPendingSyncActionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetPendingSyncActions(ctx context.Context, arg GetPendingSyncActionsParams) ([]MessageSyncAction, error) {
	rows, err := q.db.Query(ctx, getPendingSyncActions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageSyncAction
	for rows.Next() {
		var i MessageSyncAction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActionType,
			&i.Payload,
			&i.DeliveredToPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChatsLite = `-- name: GetUserChatsLite :many
SELECT
    c.id,
    c.participant_1_id,
    c.participant_2_id,
    c.p1_unread_count,
    c.p2_unread_count,
    c.p1_last_read_at,
    c.p2_last_read_at,
    c.p1_last_delivered_at,
    c.p2_last_delivered_at,
    c.p1_last_message_content,
    c.p2_last_message_content,
    c.p1_last_message_type,
    c.p2_last_message_type,
    c.last_message_created_at,
    c.created_at,
    c.updated_at,
    c.last_message_sender_id,
    c.last_message_id,
    (CASE
        WHEN c.participant_1_id = $1 THEN c.participant_2_id
        ELSE c.participant_1_id
    END)::UUID AS other_user_id,

(CASE
    WHEN c.participant_1_id = $1 THEN c.p1_unread_count
    ELSE c.p2_unread_count
END)::INT AS unread_count,

(CASE
    WHEN c.participant_1_id = $1 THEN COALESCE(c.p1_last_message_content, '')
    ELSE COALESCE(c.p2_last_message_content, '')
END)::TEXT AS last_message_content,
(CASE
    WHEN c.participant_1_id = $1 THEN COALESCE(c.p1_last_message_type, '')
    ELSE COALESCE(c.p2_last_message_type, '')
END)::TEXT AS last_message_type,

(CASE
    WHEN c.last_message_created_at IS NULL THEN ''
    WHEN c.last_message_created_at <= (
        CASE
            WHEN c.participant_1_id = $1 THEN COALESCE(c.p2_last_read_at, '0001-01-01T00:00:00Z'::TIMESTAMPTZ)
            ELSE COALESCE(c.p1_last_read_at, '0001-01-01T00:00:00Z'::TIMESTAMPTZ)
        END
    ) THEN 'read'
    WHEN c.last_message_created_at <= (
        CASE
            WHEN c.participant_1_id = $1 THEN COALESCE(c.p2_last_delivered_at, '0001-01-01T00:00:00Z'::TIMESTAMPTZ)
            ELSE COALESCE(c.p1_last_delivered_at, '0001-01-01T00:00:00Z'::TIMESTAMPTZ)
        END
    ) THEN 'delivered'
    ELSE 'sent'
END)::TEXT AS last_message_status,
(CASE
    WHEN c.participant_1_id = $1 THEN COALESCE(c.p2_last_read_at, '0001-01-01T00:00:00Z'::TIMESTAMPTZ)
    ELSE COALESCE(c.p1_last_read_at, '0001-01-01T00:00:00Z'::TIMESTAMPTZ)
END)::TIMESTAMPTZ AS other_user_last_read_at,
(CASE
    WHEN c.participant_1_id = $1 THEN COALESCE(c.p2_last_delivered_at, '0001-01-01T00:00:00Z'::TIMESTAMPTZ)
    ELSE COALESCE(c.p1_last_delivered_at, '0001-01-01T00:00:00Z'::TIMESTAMPTZ)
END)::TIMESTAMPTZ AS other_user_last_delivered_at
FROM chats c
WHERE
    c.participant_1_id = $1
    OR c.participant_2_id = $1
ORDER BY c.updated_at DESC
`

type GetUserChatsLiteRow struct {
	ID                       uuid.UUID  `json:"id"`
	Participant1ID           uuid.UUID  `json:"participant_1_id"`
	Participant2ID           uuid.UUID  `json:"participant_2_id"`
	P1UnreadCount            int32      `json:"p1_unread_count"`
	P2UnreadCount            int32      `json:"p2_unread_count"`
	P1LastReadAt             *time.Time `json:"p1_last_read_at"`
	P2LastReadAt             *time.Time `json:"p2_last_read_at"`
	P1LastDeliveredAt        *time.Time `json:"p1_last_delivered_at"`
	P2LastDeliveredAt        *time.Time `json:"p2_last_delivered_at"`
	P1LastMessageContent     *string    `json:"p1_last_message_content"`
	P2LastMessageContent     *string    `json:"p2_last_message_content"`
	P1LastMessageType        *string    `json:"p1_last_message_type"`
	P2LastMessageType        *string    `json:"p2_last_message_type"`
	LastMessageCreatedAt     *time.Time `json:"last_message_created_at"`
	CreatedAt                time.Time  `json:"created_at"`
	UpdatedAt                time.Time  `json:"updated_at"`
	LastMessageSenderID      *uuid.UUID `json:"last_message_sender_id"`
	LastMessageID            *uuid.UUID `json:"last_message_id"`
	OtherUserID              uuid.UUID  `json:"other_user_id"`
	UnreadCount              int32      `json:"unread_count"`
	LastMessageContent       string     `json:"last_message_content"`
	LastMessageType          string     `json:"last_message_type"`
	LastMessageStatus        string     `json:"last_message_status"`
	OtherUserLastReadAt      time.Time  `json:"other_user_last_read_at"`
	OtherUserLastDeliveredAt time.Time  `json:"other_user_last_delivered_at"`
}

// Lite version: reads ONLY from chats table.
// Profile hydration (name, username, avatar, privacy) is delegated
// to the personalProfilePersonalChatProvider at the service layer.
// Unread Count (From Metadata)
// Per-Participant Last Message Preview
// Last Message Status (Calculated from chat metadata only)
func (q *Queries) GetUserChatsLite(ctx context.Context, participant1ID uuid.UUID) ([]GetUserChatsLiteRow, error) {
	rows, err := q.db.Query(ctx, getUserChatsLite, participant1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserChatsLiteRow
	for rows.Next() {
		var i GetUserChatsLiteRow
		if err := rows.Scan(
			&i.ID,
			&i.Participant1ID,
			&i.Participant2ID,
			&i.P1UnreadCount,
			&i.P2UnreadCount,
			&i.P1LastReadAt,
			&i.P2LastReadAt,
			&i.P1LastDeliveredAt,
			&i.P2LastDeliveredAt,
			&i.P1LastMessageContent,
			&i.P2LastMessageContent,
			&i.P1LastMessageType,
			&i.P2LastMessageType,
			&i.LastMessageCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessageSenderID,
			&i.LastMessageID,
			&i.OtherUserID,
			&i.UnreadCount,
			&i.LastMessageContent,
			&i.LastMessageType,
			&i.LastMessageStatus,
			&i.OtherUserLastReadAt,
			&i.OtherUserLastDeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementDeliveryAttempts = `-- name: IncrementDeliveryAttempts :exec
UPDATE messages
SET
    delivery_attempts = delivery_attempts + 1,
    updated_at = now()
WHERE
    id = $1
`

func (q *Queries) IncrementDeliveryAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementDeliveryAttempts, id)
	return err
}

const isChatParticipant = `-- name: IsChatParticipant :one


SELECT EXISTS (
        SELECT 1
        FROM chats
        WHERE
            id = $1::uuid
            AND (
                $2::uuid = participant_1_id
                OR $2::uuid = participant_2_id
            )
    )
`

type IsChatParticipantParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
}

// ===========================================
// Messaging Eligibility Checks
// ===========================================
func (q *Queries) IsChatParticipant(ctx context.Context, arg IsChatParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatParticipant, arg.Column1, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markChatMessagesAsRead = `-- name: MarkChatMessagesAsRead :exec
UPDATE messages
SET
    delivered_to_recipient = TRUE,
    updated_at = now()
WHERE
    chat_id = $1
    AND recipient_id = $2
    AND delivered_to_recipient = FALSE
`

type MarkChatMessagesAsReadParams struct {
	ChatID      uuid.UUID `json:"chat_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkChatMessagesAsRead(ctx context.Context, arg MarkChatMessagesAsReadParams) error {
	_, err := q.db.Exec(ctx, markChatMessagesAsRead, arg.ChatID, arg.RecipientID)
	return err
}

const markChatMessagesAsReadPrimary = `-- name: MarkChatMessagesAsReadPrimary :exec
UPDATE messages
SET
    delivered_to_recipient_primary = TRUE,
    delivered_to_recipient = TRUE, -- Implicitly true
    updated_at = now()
WHERE
    chat_id = $1
    AND recipient_id = $2
    AND delivered_to_recipient_primary = FALSE
`

type MarkChatMessagesAsReadPrimaryParams struct {
	ChatID      uuid.UUID `json:"chat_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkChatMessagesAsReadPrimary(ctx context.Context, arg MarkChatMessagesAsReadPrimaryParams) error {
	_, err := q.db.Exec(ctx, markChatMessagesAsReadPrimary, arg.ChatID, arg.RecipientID)
	return err
}

const markMessageDeletedByRecipient = `-- name: MarkMessageDeletedByRecipient :exec
UPDATE messages
SET
    deleted_by_recipient = TRUE,
    delivered_to_recipient_primary = TRUE,
    updated_at = now()
WHERE
    id = $1
    AND recipient_id = $2
`

type MarkMessageDeletedByRecipientParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkMessageDeletedByRecipient(ctx context.Context, arg MarkMessageDeletedByRecipientParams) error {
	_, err := q.db.Exec(ctx, markMessageDeletedByRecipient, arg.ID, arg.RecipientID)
	return err
}

const markMessageDeletedBySender = `-- name: MarkMessageDeletedBySender :exec
UPDATE messages
SET
    deleted_by_sender = TRUE,
    synced_to_sender_primary = TRUE,
    updated_at = now()
WHERE
    id = $1
    AND sender_id = $2
`

type MarkMessageDeletedBySenderParams struct {
	ID       uuid.UUID `json:"id"`
	SenderID uuid.UUID `json:"sender_id"`
}

func (q *Queries) MarkMessageDeletedBySender(ctx context.Context, arg MarkMessageDeletedBySenderParams) error {
	_, err := q.db.Exec(ctx, markMessageDeletedBySender, arg.ID, arg.SenderID)
	return err
}

const markMessageDeliveredToRecipient = `-- name: MarkMessageDeliveredToRecipient :exec
UPDATE messages
SET
    delivered_to_recipient = TRUE,
    updated_at = now()
WHERE
    id = $1
    AND delivered_to_recipient = FALSE
`

func (q *Queries) MarkMessageDeliveredToRecipient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageDeliveredToRecipient, id)
	return err
}

const markMessageDeliveredToRecipientPrimary = `-- name: MarkMessageDeliveredToRecipientPrimary :exec
UPDATE messages
SET
    delivered_to_recipient_primary = TRUE,
    delivered_to_recipient = TRUE,
    updated_at = now()
WHERE
    id = $1
    AND delivered_to_recipient_primary = FALSE
`

func (q *Queries) MarkMessageDeliveredToRecipientPrimary(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageDeliveredToRecipientPrimary, id)
	return err
}

const markMessageSyncedToSenderPrimary = `-- name: MarkMessageSyncedToSenderPrimary :exec
UPDATE messages
SET
    synced_to_sender_primary = TRUE,
    updated_at = now()
WHERE
    id = $1
    AND synced_to_sender_primary = FALSE
`

func (q *Queries) MarkMessageSyncedToSenderPrimary(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageSyncedToSenderPrimary, id)
	return err
}

const markOlderMessagesAsDeliveredToRecipientPrimary = `-- name: MarkOlderMessagesAsDeliveredToRecipientPrimary :exec
UPDATE messages
SET
    delivered_to_recipient_primary = TRUE,
    delivered_to_recipient = TRUE,
    updated_at = now()
WHERE
    chat_id = $1
    AND recipient_id = $2
    AND created_at <= $3
    AND message_type = 'text'
    AND delivered_to_recipient_primary = FALSE
`

type MarkOlderMessagesAsDeliveredToRecipientPrimaryParams struct {
	ChatID      uuid.UUID `json:"chat_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
	CreatedAt   time.Time `json:"created_at"`
}

// Marks all messages in a chat as delivered to primary if they are older than a specific message
// and are of type 'text' (plain messages). This prevents relay bloat.
func (q *Queries) MarkOlderMessagesAsDeliveredToRecipientPrimary(ctx context.Context, arg MarkOlderMessagesAsDeliveredToRecipientPrimaryParams) error {
	_, err := q.db.Exec(ctx, markOlderMessagesAsDeliveredToRecipientPrimary, arg.ChatID, arg.RecipientID, arg.CreatedAt)
	return err
}

const resetChatReadStatus = `-- name: ResetChatReadStatus :exec
UPDATE chats
SET
    p1_unread_count = CASE
        WHEN participant_1_id = $2 THEN 0
        ELSE p1_unread_count
    END,
    p1_last_read_at = CASE
        WHEN participant_1_id = $2 THEN now()
        ELSE p1_last_read_at
    END,
    p2_unread_count = CASE
        WHEN participant_2_id = $2 THEN 0
        ELSE p2_unread_count
    END,
    p2_last_read_at = CASE
        WHEN participant_2_id = $2 THEN now()
        ELSE p2_last_read_at
    END,
    updated_at = now()
WHERE
    id = $1
    AND (
        participant_1_id = $2
        OR participant_2_id = $2
    )
`

type ResetChatReadStatusParams struct {
	ID             uuid.UUID `json:"id"`
	Participant1ID uuid.UUID `json:"participant_1_id"`
}

func (q *Queries) ResetChatReadStatus(ctx context.Context, arg ResetChatReadStatusParams) error {
	_, err := q.db.Exec(ctx, resetChatReadStatus, arg.ID, arg.Participant1ID)
	return err
}

const updateChatLastDeliveredAt = `-- name: UpdateChatLastDeliveredAt :exec
UPDATE chats
SET
    p1_last_delivered_at = CASE
        WHEN participant_1_id = $1 THEN GREATEST(
            COALESCE(
                p1_last_delivered_at,
                '0001-01-01'::TIMESTAMPTZ
            ),
            $2::TIMESTAMPTZ
        )
        ELSE p1_last_delivered_at
    END,
    p2_last_delivered_at = CASE
        WHEN participant_2_id = $1 THEN GREATEST(
            COALESCE(
                p2_last_delivered_at,
                '0001-01-01'::TIMESTAMPTZ
            ),
            $2::TIMESTAMPTZ
        )
        ELSE p2_last_delivered_at
    END,
    updated_at = now()
WHERE
    id = $3
`

type UpdateChatLastDeliveredAtParams struct {
	ParticipantID   uuid.UUID `json:"participant_id"`
	LastDeliveredAt time.Time `json:"last_delivered_at"`
	ChatID          uuid.UUID `json:"chat_id"`
}

func (q *Queries) UpdateChatLastDeliveredAt(ctx context.Context, arg UpdateChatLastDeliveredAtParams) error {
	_, err := q.db.Exec(ctx, updateChatLastDeliveredAt, arg.ParticipantID, arg.LastDeliveredAt, arg.ChatID)
	return err
}

const updateChatStatus = `-- name: UpdateChatStatus :exec

UPDATE chats
SET
    p1_last_message_content = $2,
    p2_last_message_content = $2,
    last_message_created_at = $3,
    p1_last_message_type = $4,
    p2_last_message_type = $4,
    last_message_sender_id = $5,
    last_message_id = $6,
    p1_unread_count = CASE
        WHEN participant_1_id != $5 THEN p1_unread_count + 1
        ELSE p1_unread_count
    END,
    p2_unread_count = CASE
        WHEN participant_2_id != $5 THEN p2_unread_count + 1
        ELSE p2_unread_count
    END,
    updated_at = now()
WHERE
    id = $1
`

type UpdateChatStatusParams struct {
	ID                   uuid.UUID  `json:"id"`
	P1LastMessageContent *string    `json:"p1_last_message_content"`
	LastMessageCreatedAt *time.Time `json:"last_message_created_at"`
	P1LastMessageType    *string    `json:"p1_last_message_type"`
	LastMessageSenderID  *uuid.UUID `json:"last_message_sender_id"`
	LastMessageID        *uuid.UUID `json:"last_message_id"`
}

// ===========================================
// Chat Status Update Operations (Phase 2b)
// ===========================================
func (q *Queries) UpdateChatStatus(ctx context.Context, arg UpdateChatStatusParams) error {
	_, err := q.db.Exec(ctx, updateChatStatus,
		arg.ID,
		arg.P1LastMessageContent,
		arg.LastMessageCreatedAt,
		arg.P1LastMessageType,
		arg.LastMessageSenderID,
		arg.LastMessageID,
	)
	return err
}

const updateChatUnsendDecrement = `-- name: UpdateChatUnsendDecrement :exec
UPDATE chats
SET
    p1_unread_count = CASE
        WHEN participant_1_id = $1 THEN GREATEST(
            0,
            p1_unread_count - $2::int
        )
        ELSE p1_unread_count
    END,
    p2_unread_count = CASE
        WHEN participant_2_id = $1 THEN GREATEST(
            0,
            p2_unread_count - $2::int
        )
        ELSE p2_unread_count
    END,
    updated_at = now()
WHERE
    id = $3
`

type UpdateChatUnsendDecrementParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	Amount      int32     `json:"amount"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateChatUnsendDecrement(ctx context.Context, arg UpdateChatUnsendDecrementParams) error {
	_, err := q.db.Exec(ctx, updateChatUnsendDecrement, arg.RecipientID, arg.Amount, arg.ID)
	return err
}

const updateChatUnsendPreview = `-- name: UpdateChatUnsendPreview :exec
UPDATE chats
SET
    p1_last_message_content = 'Message unsent',
    p2_last_message_content = 'Message unsent',
    p1_last_message_type = 'unsent',
    p2_last_message_type = 'unsent',
    updated_at = now()
WHERE
    id = $1
    AND last_message_id = $2
`

type UpdateChatUnsendPreviewParams struct {
	ID            uuid.UUID  `json:"id"`
	LastMessageID *uuid.UUID `json:"last_message_id"`
}

func (q *Queries) UpdateChatUnsendPreview(ctx context.Context, arg UpdateChatUnsendPreviewParams) error {
	_, err := q.db.Exec(ctx, updateChatUnsendPreview, arg.ID, arg.LastMessageID)
	return err
}

const updateMessageFileToken = `-- name: UpdateMessageFileToken :exec
UPDATE messages
SET
    file_token_id = $2,
    file_token_secret = $3,
    file_token_expiry = $4,
    updated_at = now()
WHERE
    id = $1
`

type UpdateMessageFileTokenParams struct {
	ID              uuid.UUID  `json:"id"`
	FileTokenID     *string    `json:"file_token_id"`
	FileTokenSecret *string    `json:"file_token_secret"`
	FileTokenExpiry *time.Time `json:"file_token_expiry"`
}

func (q *Queries) UpdateMessageFileToken(ctx context.Context, arg UpdateMessageFileTokenParams) error {
	_, err := q.db.Exec(ctx, updateMessageFileToken,
		arg.ID,
		arg.FileTokenID,
		arg.FileTokenSecret,
		arg.FileTokenExpiry,
	)
	return err
}

const updateMessageToUnsent = `-- name: UpdateMessageToUnsent :exec
UPDATE messages
SET
    content = 'Message unsent',
    message_type = 'unsent',
    updated_at = now()
WHERE
    id = $1
`

func (q *Queries) UpdateMessageToUnsent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateMessageToUnsent, id)
	return err
}

const uploadHistorySyncPayload = `-- name: UploadHistorySyncPayload :execrows
UPDATE history_sync 
SET payload = $1, updated_at = now() 
WHERE id = $2 AND user_id = $3 AND expires_at > now()
`

type UploadHistorySyncPayloadParams struct {
	Payload []byte    `json:"payload"`
	ID      uuid.UUID `json:"id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) UploadHistorySyncPayload(ctx context.Context, arg UploadHistorySyncPayloadParams) (int64, error) {
	result, err := q.db.Exec(ctx, uploadHistorySyncPayload, arg.Payload, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertHistorySync = `-- name: UpsertHistorySync :one
INSERT INTO history_sync (
    id, user_id, session_id, chats_json, expires_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, now(), now()
)
ON CONFLICT (session_id) DO UPDATE SET
    id = EXCLUDED.id,
    chats_json = EXCLUDED.chats_json,
    payload = NULL,
    expires_at = EXCLUDED.expires_at,
    updated_at = now()
RETURNING id
`

type UpsertHistorySyncParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	SessionID uuid.UUID `json:"session_id"`
	ChatsJson []byte    `json:"chats_json"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) UpsertHistorySync(ctx context.Context, arg UpsertHistorySyncParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertHistorySync,
		arg.ID,
		arg.UserID,
		arg.SessionID,
		arg.ChatsJson,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
