// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package personal_chat_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckMessageExists(ctx context.Context, id uuid.UUID) (bool, error)
	CleanupFullyAcknowledgedReadMessagesInChat(ctx context.Context, chatID uuid.UUID) error
	// Bounded cleanup batch: deletes sync actions for chats between blocked users.
	// Controlled from Go with a batch_size parameter and a time budget.
	CleanupSyncActionsForBlockedUsersBatch(ctx context.Context, batchSize int32) (int64, error)
	// ===========================================
	// Per-Participant Preview Operations
	// ===========================================
	// Clears the last message preview for a specific participant only (used by Delete for Me).
	// Only fires if the deleted message is the current preview message.
	ClearLastMessageForParticipant(ctx context.Context, arg ClearLastMessageForParticipantParams) error
	ClearMessageFileFields(ctx context.Context, id uuid.UUID) error
	ConsumeSyncAction(ctx context.Context, id uuid.UUID) error
	// ===========================================
	// Chat Queries for sqlc
	// ===========================================
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	// ===========================================
	// Message Operations
	// ===========================================
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// ===========================================
	// File Messaging Operations
	// ===========================================
	CreateMessageWithFile(ctx context.Context, arg CreateMessageWithFileParams) (Message, error)
	// ===========================================
	// Sync Action Operations
	// ===========================================
	CreateSyncAction(ctx context.Context, arg CreateSyncActionParams) (MessageSyncAction, error)
	// Bounded cleanup batch: deletes no-file messages in chats between blocked users.
	// Controlled from Go with a batch_size parameter and a time budget.
	DeleteBlockedUserMessagesWithoutFilesBatch(ctx context.Context, batchSize int32) (int64, error)
	// Bounded cleanup batch: deletes expired history-sync records.
	// Controlled from Go with a batch_size parameter and a time budget.
	DeleteExpiredHistorySyncBatch(ctx context.Context, batchSize int32) (int64, error)
	// Bounded cleanup batch: deletes expired messages without attached files.
	// Controlled from Go with a batch_size parameter and a time budget.
	DeleteExpiredMessagesWithoutFilesBatch(ctx context.Context, batchSize int32) (int64, error)
	// Bounded cleanup batch: deletes text-only messages fully acknowledged by both primaries, read, and read ACKed by sender.
	// Controlled from Go with a batch_size parameter and a time budget.
	DeleteFullyAcknowledgedMessagesWithoutFilesBatch(ctx context.Context, batchSize int32) (int64, error)
	DeleteHistorySync(ctx context.Context, arg DeleteHistorySyncParams) (int64, error)
	DeleteMessage(ctx context.Context, id uuid.UUID) error
	DeleteMessagesByChatID(ctx context.Context, chatID uuid.UUID) error
	// Bounded cleanup batch: deletes sync actions older than 30 days.
	// Controlled from Go with a batch_size parameter and a time budget.
	DeleteOldSyncActionsBatch(ctx context.Context, batchSize int32) (int64, error)
	GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error)
	GetChatByParticipants(ctx context.Context, arg GetChatByParticipantsParams) (Chat, error)
	GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]Message, error)
	GetExpiredMessagesWithFiles(ctx context.Context, arg GetExpiredMessagesWithFilesParams) ([]Message, error)
	GetHistorySyncForDownload(ctx context.Context, arg GetHistorySyncForDownloadParams) ([]byte, error)
	GetHistorySyncMeta(ctx context.Context, id uuid.UUID) (GetHistorySyncMetaRow, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error)
	GetMessagesByIds(ctx context.Context, messageIds []uuid.UUID) ([]GetMessagesByIdsRow, error)
	GetMessagesWithFilesByChatID(ctx context.Context, chatID uuid.UUID) ([]Message, error)
	// ===========================================
	// Block Cleanup Operations (Background Worker)
	// ===========================================
	// Fetches messages with files for chats between blocked users for cleanup.
	GetMessagesWithFilesForBlockedUsers(ctx context.Context, arg GetMessagesWithFilesForBlockedUsersParams) ([]Message, error)
	GetPendingMessagesForRecipient(ctx context.Context, arg GetPendingMessagesForRecipientParams) ([]Message, error)
	GetPendingSenderSyncMessages(ctx context.Context, arg GetPendingSenderSyncMessagesParams) ([]Message, error)
	GetPendingSyncActions(ctx context.Context, arg GetPendingSyncActionsParams) ([]MessageSyncAction, error)
	// Lite version: reads ONLY from chats table.
	// Profile hydration (name, username, avatar, privacy) is delegated
	// to the personalProfilePersonalChatProvider at the service layer.
	// Unread Count (From Metadata)
	// Per-Participant Last Message Preview
	// Last Message Status (Calculated from chat metadata only)
	GetUserChatsLite(ctx context.Context, participant1ID uuid.UUID) ([]GetUserChatsLiteRow, error)
	// ===========================================
	// Messaging Eligibility Checks
	// ===========================================
	IsChatParticipant(ctx context.Context, arg IsChatParticipantParams) (bool, error)
	MarkMessageDeletedByRecipient(ctx context.Context, arg MarkMessageDeletedByRecipientParams) error
	MarkMessageDeletedBySender(ctx context.Context, arg MarkMessageDeletedBySenderParams) error
	MarkMessageDeliveredToRecipient(ctx context.Context, id uuid.UUID) error
	MarkMessageDeliveredToRecipientPrimary(ctx context.Context, id uuid.UUID) error
	MarkMessageSyncedToSenderPrimary(ctx context.Context, id uuid.UUID) error
	MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) ([]MarkMessagesAsReadRow, error)
	MarkMessagesDeliveredToRecipientBatch(ctx context.Context, arg MarkMessagesDeliveredToRecipientBatchParams) ([]MarkMessagesDeliveredToRecipientBatchRow, error)
	MarkMessagesDeliveredToRecipientPrimaryBatch(ctx context.Context, arg MarkMessagesDeliveredToRecipientPrimaryBatchParams) ([]MarkMessagesDeliveredToRecipientPrimaryBatchRow, error)
	MarkMessagesReadAckedBySender(ctx context.Context, arg MarkMessagesReadAckedBySenderParams) ([]uuid.UUID, error)
	ResetChatReadStatus(ctx context.Context, arg ResetChatReadStatusParams) error
	StripDeliveredMessagePayload(ctx context.Context, id uuid.UUID) error
	UpdateChatLastDeliveredAt(ctx context.Context, arg UpdateChatLastDeliveredAtParams) error
	// ===========================================
	// Chat Status Update Operations (Phase 2b)
	// ===========================================
	UpdateChatStatus(ctx context.Context, arg UpdateChatStatusParams) error
	UpdateChatUnsendDecrement(ctx context.Context, arg UpdateChatUnsendDecrementParams) error
	UpdateChatUnsendPreview(ctx context.Context, arg UpdateChatUnsendPreviewParams) error
	UpdateMessageToUnsent(ctx context.Context, id uuid.UUID) error
	UploadHistorySyncPayload(ctx context.Context, arg UploadHistorySyncPayloadParams) (int64, error)
	UpsertHistorySync(ctx context.Context, arg UpsertHistorySyncParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
