// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package personal_chat_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Deletes all messages in a chat that are fully acknowledged (both primary flags TRUE)
	// and are older than or equal to a specific timestamp, but ONLY if they are plain text.
	CleanupOlderFullyAcknowledgedMessages(ctx context.Context, arg CleanupOlderFullyAcknowledgedMessagesParams) error
	// ===========================================
	// Per-Participant Preview Operations
	// ===========================================
	// Clears the last message preview for a specific participant only (used by Delete for Me).
	// Only fires if the deleted message is the current preview message.
	ClearLastMessageForParticipant(ctx context.Context, arg ClearLastMessageForParticipantParams) error
	ConsumeSyncAction(ctx context.Context, id uuid.UUID) error
	// ===========================================
	// Chat Queries for sqlc
	// ===========================================
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	// ===========================================
	// Message Operations
	// ===========================================
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// ===========================================
	// File Messaging Operations
	// ===========================================
	CreateMessageWithFile(ctx context.Context, arg CreateMessageWithFileParams) (Message, error)
	// ===========================================
	// Sync Action Operations
	// ===========================================
	CreateSyncAction(ctx context.Context, arg CreateSyncActionParams) (MessageSyncAction, error)
	DeleteExpiredMessages(ctx context.Context) error
	DeleteMessage(ctx context.Context, id uuid.UUID) error
	DeleteOldSyncActions(ctx context.Context) error
	DeletePendingMessagesBetweenUsers(ctx context.Context, arg DeletePendingMessagesBetweenUsersParams) error
	GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error)
	GetChatByParticipants(ctx context.Context, arg GetChatByParticipantsParams) (Chat, error)
	GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]Message, error)
	GetChatsByUserID(ctx context.Context, participant1ID uuid.UUID) ([]Chat, error)
	GetDeliveredMessagesByChat(ctx context.Context, arg GetDeliveredMessagesByChatParams) ([]Message, error)
	GetExpiredMessagesWithFiles(ctx context.Context, limit int32) ([]Message, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error)
	GetMessagesWithExpiredFileTokens(ctx context.Context, limit int32) ([]Message, error)
	GetPendingMessagesForRecipient(ctx context.Context, arg GetPendingMessagesForRecipientParams) ([]Message, error)
	GetPendingSenderSyncMessages(ctx context.Context, arg GetPendingSenderSyncMessagesParams) ([]Message, error)
	GetPendingSyncActions(ctx context.Context, arg GetPendingSyncActionsParams) ([]MessageSyncAction, error)
	// Lite version: reads ONLY from chats table.
	// Profile hydration (name, username, avatar, privacy) is delegated
	// to the personalProfilePersonalChatProvider at the service layer.
	// Unread Count (From Metadata)
	// Per-Participant Last Message Preview
	// Last Message Status (Calculated from chat metadata only)
	GetUserChatsLite(ctx context.Context, participant1ID uuid.UUID) ([]GetUserChatsLiteRow, error)
	IncrementDeliveryAttempts(ctx context.Context, id uuid.UUID) error
	// ===========================================
	// Messaging Eligibility Checks
	// ===========================================
	IsChatParticipant(ctx context.Context, arg IsChatParticipantParams) (bool, error)
	MarkChatMessagesAsRead(ctx context.Context, arg MarkChatMessagesAsReadParams) error
	MarkChatMessagesAsReadPrimary(ctx context.Context, arg MarkChatMessagesAsReadPrimaryParams) error
	MarkMessageDeletedByRecipient(ctx context.Context, arg MarkMessageDeletedByRecipientParams) error
	MarkMessageDeletedBySender(ctx context.Context, arg MarkMessageDeletedBySenderParams) error
	MarkMessageDeliveredToRecipient(ctx context.Context, id uuid.UUID) error
	MarkMessageDeliveredToRecipientPrimary(ctx context.Context, id uuid.UUID) error
	MarkMessageSyncedToSenderPrimary(ctx context.Context, id uuid.UUID) error
	// Marks all messages in a chat as delivered to primary if they are older than a specific message
	// and are of type 'text' (plain messages). This prevents relay bloat.
	MarkOlderMessagesAsDeliveredToRecipientPrimary(ctx context.Context, arg MarkOlderMessagesAsDeliveredToRecipientPrimaryParams) error
	ResetChatReadStatus(ctx context.Context, arg ResetChatReadStatusParams) error
	UpdateChatLastDeliveredAt(ctx context.Context, arg UpdateChatLastDeliveredAtParams) error
	// ===========================================
	// Chat Status Update Operations (Phase 2b)
	// ===========================================
	UpdateChatStatus(ctx context.Context, arg UpdateChatStatusParams) error
	UpdateChatUnsendDecrement(ctx context.Context, arg UpdateChatUnsendDecrementParams) error
	UpdateChatUnsendPreview(ctx context.Context, arg UpdateChatUnsendPreviewParams) error
	UpdateMessageFileToken(ctx context.Context, arg UpdateMessageFileTokenParams) error
	UpdateMessageToUnsent(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
