AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ChatBasket Backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  GoEchoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      PackageType: Image
      Architectures:
      - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          AWS_LWA_ASYNC_INIT: true
          AWS_LWA_PASS_THROUGH_PATH: '/'
          APPWRITE_ENDPOINT: https://fra.cloud.appwrite.io/v1
          APPWRITE_PROJECT_ID: 6858ed4d0005c859ea03
          APPWRITE_API_KEY: standard_5958b9abaa3f22c5a051eb25de37f943ce39a86e9737215b12e80da16416065aafd73e114545ac1d9ee74b91886f82eee8e80a40636d12ccaab79ae3c380196e2baf8679250c71cf4633d5c9f190b26786cf0adcb0715dd6912481ae2059adc1868f368e223bafd8165f6bde2d859afcd2192e464decf471361d48dd190725bd
          APPWRITE_DATABASE_ID: 68594901002d7369d75e
          APPWRITE_USERS_COLLECTION_ID: 685ab6cb000736ee8cb1
          APPWRITE_POSTS_COLLECTION_ID: 685abd5b00016ef23268
          APPWRITE_REFRESH_TOKENS_COLLECTION_ID: 685ac128003b92b09842
          APPWRITE_LIKES_COLLECTION_ID: 685ce962002427320c96
          APPWRITE_FOLLOW_COLLECTION_ID: 685bd51a000807f5c052
          APPWRITE_COMMENTS_COLLECTION_ID: 685cea22000f2922bafa
          APPWRITE_BLOCK_COLLECTION_ID: 685ced200037ffe8a854
          APPWRITE_FOLLOW_REQUESTS_COLLECTION_ID: 6869f98300075c94ad09
          APPWRITE_TEMP_OTP_COLLECTION_ID: 686a06e80028dd47b429
      Events:
        APIEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  ApiUrl:
    Description: "ChatBasket backend API URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod"