AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ChatBasket Backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  GoEchoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      PackageType: Image
      Architectures:
      - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          AWS_LWA_ASYNC_INIT: true
          AWS_LWA_PASS_THROUGH_PATH: '/'
          APPWRITE_ENDPOINT: https://fra.cloud.appwrite.io/v1
          APPWRITE_PROJECT_ID: 6858ed4d0005c859ea03
          APPWRITE_API_KEY: standard_43edde15e7b72c9e99504b39015b7849dcf023d32befb601bd77bcb74342ed9f9291262de5e2e1721c8182fa5eaba5c4c9c18cecc4bc2d1953162887e47da6a2eb6518595b93a99f42d81e8f955501f5c39a4166ad7f16cc65ac5f740a988c900af0b4ccf2587bfc713563a415af0f5f54fed5a62c3825f77019b4b55ecc34c6
          APPWRITE_DATABASE_ID: 68594901002d7369d75e
          APPWRITE_USERS_COLLECTION_ID: 685ab6cb000736ee8cb1
          APPWRITE_POSTS_COLLECTION_ID: 685abd5b00016ef23268
          APPWRITE_REFRESH_TOKENS_COLLECTION_ID: 685ac128003b92b09842
          APPWRITE_LIKES_COLLECTION_ID: 685ce962002427320c96
          APPWRITE_FOLLOW_COLLECTION_ID: 685bd51a000807f5c052
          APPWRITE_COMMENTS_COLLECTION_ID: 685cea22000f2922bafa
          APPWRITE_BLOCK_COLLECTION_ID: 685ced200037ffe8a854
          APPWRITE_FOLLOW_REQUESTS_COLLECTION_ID: 6869f98300075c94ad09
          APPWRITE_TEMP_OTP_COLLECTION_ID: 686a06e80028dd47b429
      Events:
        APIEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  ApiUrl:
    Description: "ChatBasket backend API URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod"