// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_uploads.sql

package pending_uploads_store

import (
	"context"
	"time"
)

const deletePendingUpload = `-- name: DeletePendingUpload :exec
DELETE FROM pending_uploads
WHERE file_id = $1
`

// Removes a pending upload by file_id (after successful confirm).
func (q *Queries) DeletePendingUpload(ctx context.Context, fileID string) error {
	_, err := q.db.Exec(ctx, deletePendingUpload, fileID)
	return err
}

const getExpiredPendingUploadsBatch = `-- name: GetExpiredPendingUploadsBatch :many
SELECT file_id, bucket_name, r2_key, expires_at
FROM pending_uploads
WHERE expires_at < now()
  AND file_id > $1
ORDER BY file_id ASC
LIMIT $2
`

type GetExpiredPendingUploadsBatchParams struct {
	LastFileID string `json:"last_file_id"`
	BatchSize  int32  `json:"batch_size"`
}

type GetExpiredPendingUploadsBatchRow struct {
	FileID     string    `json:"file_id"`
	BucketName string    `json:"bucket_name"`
	R2Key      string    `json:"r2_key"`
	ExpiresAt  time.Time `json:"expires_at"`
}

// Fetches a batch of expired pending uploads. Uses keyset pagination on file_id (text)
// for efficient cleanup of large tables.
func (q *Queries) GetExpiredPendingUploadsBatch(ctx context.Context, arg GetExpiredPendingUploadsBatchParams) ([]GetExpiredPendingUploadsBatchRow, error) {
	rows, err := q.db.Query(ctx, getExpiredPendingUploadsBatch, arg.LastFileID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredPendingUploadsBatchRow
	for rows.Next() {
		var i GetExpiredPendingUploadsBatchRow
		if err := rows.Scan(
			&i.FileID,
			&i.BucketName,
			&i.R2Key,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingUpload = `-- name: GetPendingUpload :one
SELECT file_id, bucket_name, r2_key, expires_at
FROM pending_uploads
WHERE file_id = $1
`

type GetPendingUploadRow struct {
	FileID     string    `json:"file_id"`
	BucketName string    `json:"bucket_name"`
	R2Key      string    `json:"r2_key"`
	ExpiresAt  time.Time `json:"expires_at"`
}

// Fetches a pending upload by file_id. Returns sql.ErrNoRows if not found.
func (q *Queries) GetPendingUpload(ctx context.Context, fileID string) (GetPendingUploadRow, error) {
	row := q.db.QueryRow(ctx, getPendingUpload, fileID)
	var i GetPendingUploadRow
	err := row.Scan(
		&i.FileID,
		&i.BucketName,
		&i.R2Key,
		&i.ExpiresAt,
	)
	return i, err
}

const insertPendingUpload = `-- name: InsertPendingUpload :exec

INSERT INTO pending_uploads (file_id, bucket_name, r2_key, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertPendingUploadParams struct {
	FileID     string    `json:"file_id"`
	BucketName string    `json:"bucket_name"`
	R2Key      string    `json:"r2_key"`
	ExpiresAt  time.Time `json:"expires_at"`
}

// ===========================================
// Pending Upload Operations (R2 lifecycle)
// ===========================================
// Registers a new presigned upload in the tracking table.
// created_at/updated_at are auto-populated by the set_timestamps() trigger.
func (q *Queries) InsertPendingUpload(ctx context.Context, arg InsertPendingUploadParams) error {
	_, err := q.db.Exec(ctx, insertPendingUpload,
		arg.FileID,
		arg.BucketName,
		arg.R2Key,
		arg.ExpiresAt,
	)
	return err
}
