// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pending_uploads_store

import (
	"context"
)

type Querier interface {
	// Removes a pending upload by file_id (after successful confirm).
	DeletePendingUpload(ctx context.Context, fileID string) error
	// Fetches a batch of expired pending uploads. Uses keyset pagination on file_id (text)
	// for efficient cleanup of large tables.
	GetExpiredPendingUploadsBatch(ctx context.Context, arg GetExpiredPendingUploadsBatchParams) ([]GetExpiredPendingUploadsBatchRow, error)
	// Fetches a pending upload by file_id. Returns sql.ErrNoRows if not found.
	GetPendingUpload(ctx context.Context, fileID string) (GetPendingUploadRow, error)
	// ===========================================
	// Pending Upload Operations (R2 lifecycle)
	// ===========================================
	// Registers a new presigned upload in the tracking table.
	// created_at/updated_at are auto-populated by the set_timestamps() trigger.
	InsertPendingUpload(ctx context.Context, arg InsertPendingUploadParams) error
}

var _ Querier = (*Queries)(nil)
