// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_sse.sql

package personal_sse_store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSseOutboxRow = `-- name: CreateSseOutboxRow :exec

INSERT INTO personal_sse_outbox (
    id,
    command,
    target_user_id,
    target_session_id,
    exclude_session_id,
    payload,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSseOutboxRowParams struct {
	ID               uuid.UUID  `json:"id"`
	Command          string     `json:"command"`
	TargetUserID     uuid.UUID  `json:"target_user_id"`
	TargetSessionID  *uuid.UUID `json:"target_session_id"`
	ExcludeSessionID *uuid.UUID `json:"exclude_session_id"`
	Payload          []byte     `json:"payload"`
	ExpiresAt        time.Time  `json:"expires_at"`
}

// ===========================================
// Personal SSE Outbox Operations (cluster fanout)
// ===========================================
// Large SSE events (>7000-byte NOTIFY payload) are stored here.
// NOTIFY carries only the row id; the listener hydrates the full
// event, broadcasts locally. IDs and expiry come
// from Go (uuid.New, now+3min). Rows live until TTL so every cluster
// node can hydrate; sweeper clears orphans and expired rows.
func (q *Queries) CreateSseOutboxRow(ctx context.Context, arg CreateSseOutboxRowParams) error {
	_, err := q.db.Exec(ctx, createSseOutboxRow,
		arg.ID,
		arg.Command,
		arg.TargetUserID,
		arg.TargetSessionID,
		arg.ExcludeSessionID,
		arg.Payload,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSseOutboxBatch = `-- name: DeleteExpiredSseOutboxBatch :execrows
WITH batch AS (
  SELECT id FROM personal_sse_outbox
  WHERE expires_at < now()
  FOR UPDATE SKIP LOCKED
  LIMIT $1
)
DELETE FROM personal_sse_outbox AS o
USING batch
WHERE o.id = batch.id
`

// Bounded cleanup batch: deletes expired outbox orphans in small
// batches so a huge pile makes progress instead of rolling back one
// giant DELETE on timeout.
func (q *Queries) DeleteExpiredSseOutboxBatch(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSseOutboxBatch, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSseOutboxRow = `-- name: GetSseOutboxRow :one
SELECT payload
FROM personal_sse_outbox
WHERE id = $1
`

// Fetches only the event payload: routing fields already arrived
// inside the NOTIFY JSON envelope, so selecting them again would
// transfer redundant columns on every hydrate.
func (q *Queries) GetSseOutboxRow(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSseOutboxRow, id)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}
