// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package personal_sse_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ===========================================
	// Personal SSE Outbox Operations (cluster fanout)
	// ===========================================
	// Large SSE events (>7000-byte NOTIFY payload) are stored here.
	// NOTIFY carries only the row id; the listener hydrates the full
	// event, broadcasts locally. IDs and expiry come
	// from Go (uuid.New, now+3min). Rows live until TTL so every cluster
	// node can hydrate; sweeper clears orphans and expired rows.
	CreateSseOutboxRow(ctx context.Context, arg CreateSseOutboxRowParams) error
	// Bounded cleanup batch: deletes expired outbox orphans in small
	// batches so a huge pile makes progress instead of rolling back one
	// giant DELETE on timeout.
	DeleteExpiredSseOutboxBatch(ctx context.Context, batchSize int32) (int64, error)
	// Fetches only the event payload: routing fields already arrived
	// inside the NOTIFY JSON envelope, so selecting them again would
	// transfer redundant columns on every hydrate.
	GetSseOutboxRow(ctx context.Context, id uuid.UUID) ([]byte, error)
}

var _ Querier = (*Queries)(nil)
