// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptContactRequest(ctx context.Context, arg AcceptContactRequestParams) (string, error)
	// ===========================================
	// Messaging Eligibility Checks
	// ===========================================
	CanSendMessage(ctx context.Context, arg CanSendMessageParams) (string, error)
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	// Checks if the user already has a central device
	CheckHasCentralDevice(ctx context.Context, authUserID uuid.UUID) (bool, error)
	// ======================================
	// Auth Queries
	// ======================================
	// Checks if a session is valid for a specific user and not expired
	CheckSessionIsValid(ctx context.Context, arg CheckSessionIsValidParams) (bool, error)
	// Deletes all messages in a chat that are fully acknowledged (both primary flags TRUE)
	// and are older than or equal to a specific timestamp, but ONLY if they are plain text.
	CleanupOlderFullyAcknowledgedMessages(ctx context.Context, arg CleanupOlderFullyAcknowledgedMessagesParams) error
	// ===========================================
	// Per-Participant Preview Operations
	// ===========================================
	// Clears the last message preview for a specific participant only (used by Delete for Me).
	// Only fires if the deleted message is the current preview message.
	ClearLastMessageForParticipant(ctx context.Context, arg ClearLastMessageForParticipantParams) error
	ConsumeSyncAction(ctx context.Context, id uuid.UUID) error
	CreateAloneUsername(ctx context.Context, arg CreateAloneUsernameParams) (AloneUsername, error)
	CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error)
	// Inserts a new avatar and returns all columns
	CreateAvatar(ctx context.Context, arg CreateAvatarParams) (Avatar, error)
	// ===========================================
	// Chat Queries for sqlc
	// ===========================================
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	// ===========================================
	// Message Operations
	// ===========================================
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// ===========================================
	// File Messaging Operations
	// ===========================================
	CreateMessageWithFile(ctx context.Context, arg CreateMessageWithFileParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// ===========================================
	// Sync Action Operations
	// ===========================================
	CreateSyncAction(ctx context.Context, arg CreateSyncActionParams) (MessageSyncAction, error)
	// ======================================
	// Users Table Queries for sqlc
	// ======================================
	// Inserts a new user and returns all columns
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserBlock(ctx context.Context, arg CreateUserBlockParams) error
	CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error)
	CreateVerificationCodeWithUpdateID(ctx context.Context, arg CreateVerificationCodeWithUpdateIDParams) (VerificationCode, error)
	DeleteAllUserSessions(ctx context.Context, authUserID uuid.UUID) error
	DeleteAllVerificationCodesForEmail(ctx context.Context, arg DeleteAllVerificationCodesForEmailParams) error
	DeleteAndInsertContactRequest(ctx context.Context, arg DeleteAndInsertContactRequestParams) error
	// Delete auth user (cascade will automatically delete sessions and verification_codes)
	DeleteAuthUser(ctx context.Context, id uuid.UUID) error
	// Deletes the main profile avatar for a user
	DeleteAvatar(ctx context.Context, userID uuid.UUID) error
	DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error)
	DeleteExpiredMessages(ctx context.Context) error
	DeleteMessage(ctx context.Context, id uuid.UUID) error
	DeleteOldSyncActions(ctx context.Context) error
	DeletePendingMessagesBetweenUsers(ctx context.Context, arg DeletePendingMessagesBetweenUsersParams) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	DeleteSessionByToken(ctx context.Context, arg DeleteSessionByTokenParams) error
	DeleteVerificationCode(ctx context.Context, id uuid.UUID) error
	GetAuthUserByEmail(ctx context.Context, email string) (AuthUser, error)
	// Returns auth user by ID
	GetAuthUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error)
	// Returns the details of the central session for a user
	GetCentralSession(ctx context.Context, authUserID uuid.UUID) (Session, error)
	GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error)
	GetChatByParticipants(ctx context.Context, arg GetChatByParticipantsParams) (Chat, error)
	GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]Message, error)
	GetChatsByUserID(ctx context.Context, participant1ID uuid.UUID) ([]Chat, error)
	GetContactRequestStatus(ctx context.Context, arg GetContactRequestStatusParams) (string, error)
	GetDeliveredMessagesByChat(ctx context.Context, arg GetDeliveredMessagesByChatParams) ([]Message, error)
	GetExpiredMessagesWithFiles(ctx context.Context, limit int32) ([]Message, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error)
	GetMessagesWithExpiredFileTokens(ctx context.Context, limit int32) ([]Message, error)
	GetPendingContactRequests(ctx context.Context, exemptedUserID uuid.UUID) ([]GetPendingContactRequestsRow, error)
	GetPendingMessagesForRecipient(ctx context.Context, arg GetPendingMessagesForRecipientParams) ([]Message, error)
	GetPendingSenderSyncMessages(ctx context.Context, arg GetPendingSenderSyncMessagesParams) ([]Message, error)
	GetPendingSyncActions(ctx context.Context, arg GetPendingSyncActionsParams) ([]MessageSyncAction, error)
	GetSentContactRequests(ctx context.Context, exemptedUserID uuid.UUID) ([]GetSentContactRequestsRow, error)
	GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (Session, error)
	// ===========================================
	// Contact existence helpers
	// ===========================================
	GetUserByHashedUsername(ctx context.Context, hmacSha256HexUsername string) (User, error)
	// Unread Count (From Metadata)
	// Per-Participant Last Message Preview
	// Last Message Status (Calculated)
	// Raw avatar data
	// Privacy flags
	GetUserChats(ctx context.Context, participant1ID uuid.UUID) ([]GetUserChatsRow, error)
	// ===========================================
	// Contacts Queries for sqlc
	// ===========================================
	// Retrieves user contacts (people YOU added) with raw restriction data for Go processing
	GetUserContacts(ctx context.Context, exemptedUserID uuid.UUID) ([]GetUserContactsRow, error)
	// Minimal user profile without avatar join
	GetUserCoreProfile(ctx context.Context, id uuid.UUID) (User, error)
	// Returns user's primary device session (for Phase 6 messaging eligibility)
	GetUserPrimarySession(ctx context.Context, authUserID uuid.UUID) (Session, error)
	// Returns full user record along with its profile avatar tokens and file_id
	GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error)
	// ===========================================
	// People Who Added You Query
	// ===========================================
	// Retrieves users who have added YOU as a contact with raw restriction data for Go processing
	GetUsersWhoAddedYou(ctx context.Context, exemptedUserID uuid.UUID) ([]GetUsersWhoAddedYouRow, error)
	// Get the verification code by User ID (PK) and Type
	GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error)
	HasPendingRequest(ctx context.Context, arg HasPendingRequestParams) (bool, error)
	IncrementDeliveryAttempts(ctx context.Context, id uuid.UUID) error
	InsertContactRequest(ctx context.Context, arg InsertContactRequestParams) error
	InsertUserContact(ctx context.Context, arg InsertUserContactParams) error
	IsAlreadyContact(ctx context.Context, arg IsAlreadyContactParams) (bool, error)
	IsChatParticipant(ctx context.Context, arg IsChatParticipantParams) (bool, error)
	// ===========================================
	// Avatar Privacy Circuit Breaker Logic
	// ===========================================
	// Both queries return RAW restriction flags for Go to process.
	// Go applies the following priority order (circuit breaker pattern):
	//
	// Priority 1: Global PROFILE restriction
	//   → If restrict_profile = TRUE AND exception_profile = FALSE → HIDE avatar
	//   → If restrict_profile = TRUE AND exception_profile = TRUE → SHOW avatar
	//   → Otherwise, continue to Priority 2
	//
	// Priority 2: Global AVATAR restriction
	//   → If restrict_avatar = TRUE AND exception_avatar = FALSE → HIDE avatar
	//   → If restrict_avatar = TRUE AND exception_avatar = TRUE → SHOW avatar
	//   → Otherwise, continue to Priority 3
	//
	// Priority 3: User-level PROFILE restriction
	//   → If user_restrict_profile = TRUE → HIDE avatar
	//   → Otherwise, continue to Priority 4
	//
	// Priority 4: User-level AVATAR restriction
	//   → If user_restrict_avatar = TRUE → HIDE avatar
	//   → Otherwise, SHOW avatar
	//
	// Each level short-circuits evaluation (circuit breaker pattern).
	// Privacy checks work identically for both queries because:
	//   - cu.id = the contact being viewed (their restrictions apply)
	//   - $1 = the viewer (you, checking if you're restricted/exempted)
	//   - Direction of contact relationship doesn't affect privacy logic
	// ===========================================
	// ===========================================
	// Contact creation helpers
	// ===========================================
	// Returns 0 if no block, 1 if blocker is $1 (requester blocked target), 2 if blocker is $2 (target blocked requester)
	IsEitherBlocked(ctx context.Context, arg IsEitherBlockedParams) (int32, error)
	// Returns true if the user is admin-blocked
	IsUserAdminBlocked(ctx context.Context, id uuid.UUID) (bool, error)
	IsUserExists(ctx context.Context, id uuid.UUID) (bool, error)
	// Checks if the user exists and has a main profile picture
	IsUserProfilePicExists(ctx context.Context, id uuid.UUID) (bool, error)
	// Returns users created before a certain timestamp (keyset pagination)
	ListUsersAfter(ctx context.Context, arg ListUsersAfterParams) ([]User, error)
	MarkChatMessagesAsRead(ctx context.Context, arg MarkChatMessagesAsReadParams) error
	MarkChatMessagesAsReadPrimary(ctx context.Context, arg MarkChatMessagesAsReadPrimaryParams) error
	MarkMessageDeletedByRecipient(ctx context.Context, arg MarkMessageDeletedByRecipientParams) error
	MarkMessageDeletedBySender(ctx context.Context, arg MarkMessageDeletedBySenderParams) error
	MarkMessageDeliveredToRecipient(ctx context.Context, id uuid.UUID) error
	MarkMessageDeliveredToRecipientPrimary(ctx context.Context, id uuid.UUID) error
	MarkMessageSyncedToSenderPrimary(ctx context.Context, id uuid.UUID) error
	// Marks all messages in a chat as delivered to primary if they are older than a specific message
	// and are of type 'text' (plain messages). This prevents relay bloat.
	MarkOlderMessagesAsDeliveredToRecipientPrimary(ctx context.Context, arg MarkOlderMessagesAsDeliveredToRecipientPrimaryParams) error
	RejectContactRequest(ctx context.Context, arg RejectContactRequestParams) (string, error)
	// Sets is_central = false for ALL sessions of this user (Upgrade preparation)
	ResetCentralSessions(ctx context.Context, authUserID uuid.UUID) error
	ResetChatReadStatus(ctx context.Context, arg ResetChatReadStatusParams) error
	// Sets is_central = true for a specific session
	SetSessionCentral(ctx context.Context, arg SetSessionCentralParams) error
	// Sets is_central = true for a session identified by token hash
	SetSessionCentralByToken(ctx context.Context, arg SetSessionCentralByTokenParams) error
	UndoContactRequest(ctx context.Context, arg UndoContactRequestParams) (string, error)
	UpdateAuthUserEmail(ctx context.Context, arg UpdateAuthUserEmailParams) error
	UpdateAuthUserEmailVerified(ctx context.Context, arg UpdateAuthUserEmailVerifiedParams) error
	UpdateAuthUserPassword(ctx context.Context, arg UpdateAuthUserPasswordParams) error
	// Updates token_id, token_secret, and token_expiry for the main profile avatar (where user_id == file_id)
	UpdateAvatarTokens(ctx context.Context, arg UpdateAvatarTokensParams) (Avatar, error)
	UpdateChatLastDeliveredAt(ctx context.Context, arg UpdateChatLastDeliveredAtParams) error
	// ===========================================
	// Chat Status Update Operations (Phase 2b)
	// ===========================================
	UpdateChatStatus(ctx context.Context, arg UpdateChatStatusParams) error
	UpdateChatUnsendDecrement(ctx context.Context, arg UpdateChatUnsendDecrementParams) error
	UpdateChatUnsendPreview(ctx context.Context, arg UpdateChatUnsendPreviewParams) error
	UpdateContactNickname(ctx context.Context, arg UpdateContactNicknameParams) (bool, error)
	UpdateMessageFileToken(ctx context.Context, arg UpdateMessageFileTokenParams) error
	UpdateMessageToUnsent(ctx context.Context, id uuid.UUID) error
	UpdateSessionDeviceToken(ctx context.Context, arg UpdateSessionDeviceTokenParams) error
	// Updates user profile fields conditionally based on provided values (NULL values are ignored)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
