// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresCode

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AloneUsername struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Avatar struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	FileID      string             `json:"file_id"`
	AvatarType  string             `json:"avatar_type"`
	TokenID     *string            `json:"token_id"`
	TokenSecret *string            `json:"token_secret"`
	TokenExpiry pgtype.Timestamptz `json:"token_expiry"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                                uuid.UUID          `json:"id"`
	Name                              string             `json:"name"`
	Bio                               *string            `json:"bio"`
	Contacts                          int32              `json:"contacts"`
	ProfileType                       string             `json:"profile_type"`
	IsAdminBlocked                    bool               `json:"is_admin_blocked"`
	AdminBlockReason                  *string            `json:"admin_block_reason"`
	HmacSha256HexUsername             string             `json:"hmac_sha256_hex_username"`
	B64CipherChacha20poly1305Username string             `json:"b64_cipher_chacha20poly1305_username"`
	CreatedAt                         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                         pgtype.Timestamptz `json:"updated_at"`
}
