// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_tokens.sql

package postgresCode

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateSessionTokens = `-- name: DeactivateSessionTokens :exec
UPDATE tokens
SET
    is_active = FALSE,
    updated_at = now()
WHERE
    sha256_hex_session_id = $1
    AND user_id = $2
`

type DeactivateSessionTokensParams struct {
	Sha256HexSessionID string    `json:"sha256_hex_session_id"`
	UserID             uuid.UUID `json:"user_id"`
}

// Marks all tokens for a specific session as inactive (useful for logout)
func (q *Queries) DeactivateSessionTokens(ctx context.Context, arg DeactivateSessionTokensParams) error {
	_, err := q.db.Exec(ctx, deactivateSessionTokens, arg.Sha256HexSessionID, arg.UserID)
	return err
}

const deactivateUserTokens = `-- name: DeactivateUserTokens :exec
UPDATE tokens
SET
    is_active = FALSE,
    updated_at = now()
WHERE
    user_id = $1
`

// Marks all tokens for a user as inactive (useful for logout from all sessions)
func (q *Queries) DeactivateUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUserTokens, userID)
	return err
}

const deleteInactiveTokens = `-- name: DeleteInactiveTokens :exec
DELETE FROM tokens WHERE is_active = FALSE AND updated_at < $1
`

// Cleanup query: deletes tokens that have been inactive for a specified period
func (q *Queries) DeleteInactiveTokens(ctx context.Context, updatedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteInactiveTokens, updatedAt)
	return err
}

const getActiveTokensByType = `-- name: GetActiveTokensByType :many
SELECT id, user_id, sha256_hex_session_id, token, type, is_active, created_at, updated_at
FROM tokens
WHERE
    user_id = $1
    AND type = $2
    AND is_active = TRUE
ORDER BY created_at DESC
`

type GetActiveTokensByTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Type   string    `json:"type"`
}

// Returns all active tokens for a user filtered by type (fcm or apn)
func (q *Queries) GetActiveTokensByType(ctx context.Context, arg GetActiveTokensByTypeParams) ([]Token, error) {
	rows, err := q.db.Query(ctx, getActiveTokensByType, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Sha256HexSessionID,
			&i.Token,
			&i.Type,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveTokensByUser = `-- name: GetActiveTokensByUser :many
SELECT id, user_id, sha256_hex_session_id, token, type, is_active, created_at, updated_at
FROM tokens
WHERE
    user_id = $1
    AND is_active = TRUE
ORDER BY created_at DESC
`

// Returns all active tokens for a user (for sending push notifications)
func (q *Queries) GetActiveTokensByUser(ctx context.Context, userID uuid.UUID) ([]Token, error) {
	rows, err := q.db.Query(ctx, getActiveTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Sha256HexSessionID,
			&i.Token,
			&i.Type,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertToken = `-- name: UpsertToken :one

INSERT INTO
    tokens (
        id,
        user_id,
        sha256_hex_session_id,
        token,
        type,
        is_active
    )
VALUES ($1, $2, $3, $4, $5, TRUE)
ON CONFLICT (
    sha256_hex_session_id,
    user_id,
    type
) DO
UPDATE
SET
    token = EXCLUDED.token,
    is_active = TRUE,
    updated_at = now()
RETURNING
    id, user_id, sha256_hex_session_id, token, type, is_active, created_at, updated_at
`

type UpsertTokenParams struct {
	ID                 uuid.UUID `json:"id"`
	UserID             uuid.UUID `json:"user_id"`
	Sha256HexSessionID string    `json:"sha256_hex_session_id"`
	Token              string    `json:"token"`
	Type               string    `json:"type"`
}

// ======================================
// Tokens Table Queries for sqlc
// ======================================
// Inserts or updates a push notification token for a user session
// If the (session_id, user_id, type) combination exists, updates the token and marks it active
func (q *Queries) UpsertToken(ctx context.Context, arg UpsertTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, upsertToken,
		arg.ID,
		arg.UserID,
		arg.Sha256HexSessionID,
		arg.Token,
		arg.Type,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sha256HexSessionID,
		&i.Token,
		&i.Type,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
