// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_contacts.sql

package postgresCode

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserContacts = `-- name: GetUserContacts :many

SELECT
    cu.id,
    cu.name,
    cu.b64_cipher_chacha20poly1305_username AS username,
    cu.bio,
    uc.created_at AS contact_created_at,
    
    -- Raw avatar data (Go applies visibility logic)
    a.file_id AS avatar_file_id,
    a.token_id AS avatar_token_id,
    a.token_secret AS avatar_token_secret,
    a.token_expiry AS avatar_token_expiry,
    
    -- Global restriction flags (Priority 1 & 2)
    COALESCE(ugr.restrict_profile, FALSE) AS global_restrict_profile,
    COALESCE(ugr.restrict_avatar, FALSE) AS global_restrict_avatar,
    
    -- Global exemption flags (Priority 1 & 2 override)
    COALESCE(ugre.exception_profile, FALSE) AS exception_global_profile,
    COALESCE(ugre.exception_avatar, FALSE) AS exception_global_avatar,
    
    -- User-level restriction flags (Priority 3 & 4)
    COALESCE(ur.restrict_profile, FALSE) AS user_restrict_profile,
    COALESCE(ur.restrict_avatar, FALSE) AS user_restrict_avatar

FROM user_contacts uc
INNER JOIN users cu 
    ON uc.contact_user_id = cu.id 
    AND cu.is_admin_blocked IS FALSE
    AND cu.profile_type IN ('public', 'personal')
LEFT JOIN avatars a 
    ON cu.id = a.user_id 
    AND a.avatar_type = 'profile'
LEFT JOIN user_global_restrictions ugr 
    ON cu.id = ugr.user_id
LEFT JOIN user_global_restriction_exemptions ugre 
    ON cu.id = ugre.user_id 
    AND ugre.exempted_user_id = $1
LEFT JOIN user_restrictions ur 
    ON cu.id = ur.user_id 
    AND ur.restricted_user_id = $1
WHERE uc.owner_user_id = $1
ORDER BY uc.created_at DESC
`

type GetUserContactsRow struct {
	ID                     uuid.UUID          `json:"id"`
	Name                   string             `json:"name"`
	Username               string             `json:"username"`
	Bio                    *string            `json:"bio"`
	ContactCreatedAt       pgtype.Timestamptz `json:"contact_created_at"`
	AvatarFileID           *string            `json:"avatar_file_id"`
	AvatarTokenID          *string            `json:"avatar_token_id"`
	AvatarTokenSecret      *string            `json:"avatar_token_secret"`
	AvatarTokenExpiry      pgtype.Timestamptz `json:"avatar_token_expiry"`
	GlobalRestrictProfile  bool               `json:"global_restrict_profile"`
	GlobalRestrictAvatar   bool               `json:"global_restrict_avatar"`
	ExceptionGlobalProfile bool               `json:"exception_global_profile"`
	ExceptionGlobalAvatar  bool               `json:"exception_global_avatar"`
	UserRestrictProfile    bool               `json:"user_restrict_profile"`
	UserRestrictAvatar     bool               `json:"user_restrict_avatar"`
}

// ===========================================
// Contacts Queries for sqlc
// ===========================================
// Retrieves user contacts (people YOU added) with raw restriction data for Go processing
func (q *Queries) GetUserContacts(ctx context.Context, exemptedUserID uuid.UUID) ([]GetUserContactsRow, error) {
	rows, err := q.db.Query(ctx, getUserContacts, exemptedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserContactsRow
	for rows.Next() {
		var i GetUserContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Bio,
			&i.ContactCreatedAt,
			&i.AvatarFileID,
			&i.AvatarTokenID,
			&i.AvatarTokenSecret,
			&i.AvatarTokenExpiry,
			&i.GlobalRestrictProfile,
			&i.GlobalRestrictAvatar,
			&i.ExceptionGlobalProfile,
			&i.ExceptionGlobalAvatar,
			&i.UserRestrictProfile,
			&i.UserRestrictAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWhoAddedYou = `-- name: GetUsersWhoAddedYou :many

SELECT
    cu.id,
    cu.name,
    cu.b64_cipher_chacha20poly1305_username AS username,
    cu.bio,
    uc.created_at AS contact_created_at,
    
    -- Raw avatar data (Go applies visibility logic)
    a.file_id AS avatar_file_id,
    a.token_id AS avatar_token_id,
    a.token_secret AS avatar_token_secret,
    a.token_expiry AS avatar_token_expiry,
    
    -- Global restriction flags (Priority 1 & 2)
    COALESCE(ugr.restrict_profile, FALSE) AS global_restrict_profile,
    COALESCE(ugr.restrict_avatar, FALSE) AS global_restrict_avatar,
    
    -- Global exemption flags (Priority 1 & 2 override)
    COALESCE(ugre.exception_profile, FALSE) AS exception_global_profile,
    COALESCE(ugre.exception_avatar, FALSE) AS exception_global_avatar,
    
    -- User-level restriction flags (Priority 3 & 4)
    COALESCE(ur.restrict_profile, FALSE) AS user_restrict_profile,
    COALESCE(ur.restrict_avatar, FALSE) AS user_restrict_avatar

FROM user_contacts uc
INNER JOIN users cu 
    ON uc.owner_user_id = cu.id 
    AND cu.is_admin_blocked IS FALSE
    AND cu.profile_type IN ('public', 'personal')
LEFT JOIN avatars a 
    ON cu.id = a.user_id 
    AND a.avatar_type = 'profile'
LEFT JOIN user_global_restrictions ugr 
    ON cu.id = ugr.user_id
LEFT JOIN user_global_restriction_exemptions ugre 
    ON cu.id = ugre.user_id 
    AND ugre.exempted_user_id = $1
LEFT JOIN user_restrictions ur 
    ON cu.id = ur.user_id 
    AND ur.restricted_user_id = $1
WHERE uc.contact_user_id = $1
ORDER BY uc.created_at DESC
`

type GetUsersWhoAddedYouRow struct {
	ID                     uuid.UUID          `json:"id"`
	Name                   string             `json:"name"`
	Username               string             `json:"username"`
	Bio                    *string            `json:"bio"`
	ContactCreatedAt       pgtype.Timestamptz `json:"contact_created_at"`
	AvatarFileID           *string            `json:"avatar_file_id"`
	AvatarTokenID          *string            `json:"avatar_token_id"`
	AvatarTokenSecret      *string            `json:"avatar_token_secret"`
	AvatarTokenExpiry      pgtype.Timestamptz `json:"avatar_token_expiry"`
	GlobalRestrictProfile  bool               `json:"global_restrict_profile"`
	GlobalRestrictAvatar   bool               `json:"global_restrict_avatar"`
	ExceptionGlobalProfile bool               `json:"exception_global_profile"`
	ExceptionGlobalAvatar  bool               `json:"exception_global_avatar"`
	UserRestrictProfile    bool               `json:"user_restrict_profile"`
	UserRestrictAvatar     bool               `json:"user_restrict_avatar"`
}

// ===========================================
// People Who Added You Query
// ===========================================
// Retrieves users who have added YOU as a contact with raw restriction data for Go processing
func (q *Queries) GetUsersWhoAddedYou(ctx context.Context, exemptedUserID uuid.UUID) ([]GetUsersWhoAddedYouRow, error) {
	rows, err := q.db.Query(ctx, getUsersWhoAddedYou, exemptedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWhoAddedYouRow
	for rows.Next() {
		var i GetUsersWhoAddedYouRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Bio,
			&i.ContactCreatedAt,
			&i.AvatarFileID,
			&i.AvatarTokenID,
			&i.AvatarTokenSecret,
			&i.AvatarTokenExpiry,
			&i.GlobalRestrictProfile,
			&i.GlobalRestrictAvatar,
			&i.ExceptionGlobalProfile,
			&i.ExceptionGlobalAvatar,
			&i.UserRestrictProfile,
			&i.UserRestrictAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
