// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package personal_contact_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptContactRequest(ctx context.Context, arg AcceptContactRequestParams) (string, error)
	// Removes contact requests that should have been deleted when block was created
	CleanupOrphanedContactRequestsFromBlocks(ctx context.Context) error
	// ===========================================
	// Cleanup queries for orphaned data
	// ===========================================
	// Removes contact relationships that should have been deleted by block trigger
	CleanupOrphanedContactsFromBlocks(ctx context.Context) error
	CreateUserBlock(ctx context.Context, arg CreateUserBlockParams) error
	DeleteAndInsertContactRequest(ctx context.Context, arg DeleteAndInsertContactRequestParams) error
	DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error)
	// Finds contact requests that exist despite blocks (trigger failure detection)
	DetectOrphanedContactRequestsFromBlocks(ctx context.Context) ([]DetectOrphanedContactRequestsFromBlocksRow, error)
	// Finds contacts that exist despite blocks (trigger failure detection)
	DetectOrphanedContactsFromBlocks(ctx context.Context) ([]DetectOrphanedContactsFromBlocksRow, error)
	GetContactRequestStatus(ctx context.Context, arg GetContactRequestStatusParams) (string, error)
	// Block filtering: exclude requests if either user has blocked the other
	GetPendingContactRequests(ctx context.Context, exemptedUserID uuid.UUID) ([]GetPendingContactRequestsRow, error)
	// Block filtering: exclude requests if either user has blocked the other
	GetSentContactRequests(ctx context.Context, exemptedUserID uuid.UUID) ([]GetSentContactRequestsRow, error)
	// ===========================================
	// Contact existence helpers
	// ===========================================
	GetUserByHashedUsername(ctx context.Context, hmacSha256HexUsername string) (User, error)
	// ===========================================
	// Contacts Queries for sqlc
	// ===========================================
	// Retrieves user contacts (people YOU added) with raw restriction data for Go processing
	// Block filtering: exclude contacts if either user has blocked the other
	GetUserContacts(ctx context.Context, exemptedUserID uuid.UUID) ([]GetUserContactsRow, error)
	// ===========================================
	// People Who Added You Query
	// ===========================================
	// Retrieves users who have added YOU as a contact with raw restriction data for Go processing
	// Block filtering: exclude users if either has blocked the other
	GetUsersWhoAddedYou(ctx context.Context, exemptedUserID uuid.UUID) ([]GetUsersWhoAddedYouRow, error)
	HasPendingRequest(ctx context.Context, arg HasPendingRequestParams) (bool, error)
	InsertContactRequest(ctx context.Context, arg InsertContactRequestParams) error
	InsertUserContact(ctx context.Context, arg InsertUserContactParams) error
	IsAlreadyContact(ctx context.Context, arg IsAlreadyContactParams) (bool, error)
	// ===========================================
	// Avatar Privacy Circuit Breaker Logic
	// ===========================================
	// Both queries return RAW restriction flags for Go to process.
	// Go applies the following priority order (circuit breaker pattern):
	//
	// Priority 1: Global PROFILE restriction
	//   → If restrict_profile = TRUE AND exception_profile = FALSE → HIDE avatar
	//   → If restrict_profile = TRUE AND exception_profile = TRUE → SHOW avatar
	//   → Otherwise, continue to Priority 2
	//
	// Priority 2: Global AVATAR restriction
	//   → If restrict_avatar = TRUE AND exception_avatar = FALSE → HIDE avatar
	//   → If restrict_avatar = TRUE AND exception_avatar = TRUE → SHOW avatar
	//   → Otherwise, continue to Priority 3
	//
	// Priority 3: User-level PROFILE restriction
	//   → If user_restrict_profile = TRUE → HIDE avatar
	//   → Otherwise, continue to Priority 4
	//
	// Priority 4: User-level AVATAR restriction
	//   → If user_restrict_avatar = TRUE → HIDE avatar
	//   → Otherwise, SHOW avatar
	//
	// Each level short-circuits evaluation (circuit breaker pattern).
	// Privacy checks work identically for both queries because:
	//   - cu.id = the contact being viewed (their restrictions apply)
	//   - $1 = the viewer (you, checking if you're restricted/exempted)
	//   - Direction of contact relationship doesn't affect privacy logic
	// ===========================================
	// ===========================================
	// Contact creation helpers
	// ===========================================
	// Returns 0 if no block, 1 if blocker is $1 (requester blocked target), 2 if blocker is $2 (target blocked requester)
	IsEitherBlocked(ctx context.Context, arg IsEitherBlockedParams) (int32, error)
	RejectContactRequest(ctx context.Context, arg RejectContactRequestParams) (string, error)
	UndoContactRequest(ctx context.Context, arg UndoContactRequestParams) (string, error)
	UpdateContactNickname(ctx context.Context, arg UpdateContactNicknameParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
