// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package core_auth_store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	IsEmailVerified bool               `json:"is_email_verified"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID          uuid.UUID          `json:"id"`
	AuthUserID  uuid.UUID          `json:"auth_user_id"`
	TokenHash   string             `json:"token_hash"`
	DeviceToken *string            `json:"device_token"`
	Platform    *string            `json:"platform"`
	DeviceName  *string            `json:"device_name"`
	IsCentral   bool               `json:"is_central"`
	UserAgent   *string            `json:"user_agent"`
	IpAddress   *string            `json:"ip_address"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type VerificationCode struct {
	ID        uuid.UUID          `json:"id"`
	UpdateID  pgtype.UUID        `json:"update_id"`
	Email     string             `json:"email"`
	CodeHash  string             `json:"code_hash"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
