// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package core_auth_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	// Checks if the user already has a central device
	CheckHasCentralDevice(ctx context.Context, authUserID uuid.UUID) (bool, error)
	// ======================================
	// Auth Queries
	// ======================================
	// Checks if a session is valid for a specific user and not expired
	CheckSessionIsValid(ctx context.Context, arg CheckSessionIsValidParams) (bool, error)
	CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error)
	CreateVerificationCodeWithUpdateID(ctx context.Context, arg CreateVerificationCodeWithUpdateIDParams) (VerificationCode, error)
	DeleteAllUserSessions(ctx context.Context, authUserID uuid.UUID) error
	DeleteAllVerificationCodesForEmail(ctx context.Context, arg DeleteAllVerificationCodesForEmailParams) error
	// Delete auth user (cascade will automatically delete sessions and verification_codes)
	DeleteAuthUser(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	DeleteSessionByToken(ctx context.Context, arg DeleteSessionByTokenParams) error
	DeleteVerificationCode(ctx context.Context, id uuid.UUID) error
	GetAuthUserByEmail(ctx context.Context, email string) (AuthUser, error)
	// Returns auth user by ID
	GetAuthUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error)
	// Returns the details of the central session for a user
	GetCentralSession(ctx context.Context, authUserID uuid.UUID) (Session, error)
	GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (Session, error)
	// Returns user's primary device session (for Phase 6 messaging eligibility)
	GetUserPrimarySession(ctx context.Context, authUserID uuid.UUID) (Session, error)
	// Get the verification code by User ID (PK) and Type
	GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error)
	// Sets is_central = false for ALL sessions of this user (Upgrade preparation)
	ResetCentralSessions(ctx context.Context, authUserID uuid.UUID) error
	// Sets is_central = true for a specific session
	SetSessionCentral(ctx context.Context, arg SetSessionCentralParams) error
	// Sets is_central = true for a session identified by token hash
	SetSessionCentralByToken(ctx context.Context, arg SetSessionCentralByTokenParams) error
	UpdateAuthUserEmail(ctx context.Context, arg UpdateAuthUserEmailParams) error
	UpdateAuthUserEmailVerified(ctx context.Context, arg UpdateAuthUserEmailVerifiedParams) error
	UpdateAuthUserPassword(ctx context.Context, arg UpdateAuthUserPasswordParams) error
	UpdateSessionDeviceToken(ctx context.Context, arg UpdateSessionDeviceTokenParams) error
}

var _ Querier = (*Queries)(nil)
